import {
  Briefcase, TrendingUp, Heart, Mic, Building2, Dna,
  GraduationCap, Users, ShoppingBag, UserCheck, Crown, Wallet, Shield,
} from 'lucide-react';

export const AI_AGENTS = [
  {
    id: 'executive_chief_of_staff',
    name: 'Executive Chief of Staff',
    short: 'Chief of Staff',
    role: 'Personal Executive Assistant',
    icon: Briefcase,
    color: 'indigo',
    tier: 'free',
    tagline: 'Daily briefings, planning & meeting prep',
    capabilities: ['Daily Briefing', 'Weekly Planning', 'Calendar Summary', 'Executive Reminders', 'Meeting Preparation', 'Task Prioritization', 'Goal Tracking', 'Decision Journal', 'Action Items'],
  },
  {
    id: 'career_ai',
    name: 'Career AI',
    short: 'Career',
    role: 'Career Strategist',
    icon: TrendingUp,
    color: 'blue',
    tier: 'free',
    tagline: 'Resume, promotion roadmap & job matching',
    capabilities: ['Resume Builder', 'ATS Optimization', 'Promotion Roadmap', 'Career Planning', 'LinkedIn Optimization', 'Interview Prep', 'Salary Benchmark', 'Career Gap Analysis', 'Job Matching', 'Executive Readiness'],
  },
  {
    id: 'executive_coach',
    name: 'Executive Coach',
    short: 'Coach',
    role: 'Leadership Coach',
    icon: Heart,
    color: 'rose',
    tier: 'professional',
    tagline: 'Leadership coaching & executive presence',
    capabilities: ['Leadership Coaching', 'Executive Presence', 'Communication', 'Conflict Resolution', 'Delegation', 'Performance Management', 'Decision Making', 'Influence', 'Negotiation', 'Executive Confidence'],
  },
  {
    id: 'interview_ai',
    name: 'Interview AI',
    short: 'Interview',
    role: 'Recruiter & Mock Interviewer',
    icon: Mic,
    color: 'amber',
    tier: 'professional',
    tagline: 'Mock interviews & executive panels',
    capabilities: ['Mock Interviews', 'Executive Panels', 'Behavioral Interviews', 'Leadership Interviews', 'Board Interviews', 'Technical Interviews', 'Confidence Scoring', 'Leadership Assessment', 'Communication Scoring', 'Business Acumen'],
  },
  {
    id: 'board_advisor',
    name: 'Board Advisor',
    short: 'Board',
    role: 'Strategy & Governance Advisor',
    icon: Building2,
    color: 'purple',
    tier: 'executive',
    tagline: 'Board reports, strategy & M&A guidance',
    capabilities: ['Board Reports', 'Strategy', 'SWOT Analysis', 'OKRs', 'Risk Management', 'Transformation', 'M&A', 'Growth Strategy', 'Governance', 'Executive Presentations'],
  },
  {
    id: 'leadership_dna_ai',
    name: 'Leadership DNA AI',
    short: 'DNA',
    role: 'Competency Analyzer',
    icon: Dna,
    color: 'violet',
    tier: 'professional',
    tagline: 'Continuously updates your leadership profile',
    capabilities: ['Leadership Profile', 'Communication Score', 'Strategic Thinking', 'Confidence Tracking', 'Decision Making', 'Influence Analysis', 'Commercial Awareness', 'Interview Readiness', 'Executive Presence', 'Learning Agility'],
  },
  {
    id: 'learning_ai',
    name: 'Learning AI',
    short: 'Learning',
    role: 'Personal Learning Concierge',
    icon: GraduationCap,
    color: 'cyan',
    tier: 'professional',
    tagline: 'Personalized learning paths from DNA gaps',
    capabilities: ['Personalized Learning Paths', 'Course Recommendations', 'Article Curation', 'Book Suggestions', 'Video Recommendations', 'Simulation Suggestions', 'Daily Challenges', 'Skill Gap Targeting', 'Learning Scheduling', 'Progress Tracking'],
  },
  {
    id: 'networking_ai',
    name: 'Networking AI',
    short: 'Networking',
    role: 'Strategic Connection Builder',
    icon: Users,
    color: 'green',
    tier: 'executive',
    tagline: 'Suggests mentors, boards & partners',
    capabilities: ['Executive Connections', 'Mentor Matching', 'Board Member Suggestions', 'Community Recommendations', 'Event Suggestions', 'Partner Matching', 'Recruiter Introductions', 'Founder Networking', 'Company Targeting', 'Relationship Strategy'],
  },
  {
    id: 'marketplace_ai',
    name: 'Marketplace AI',
    short: 'Marketplace',
    role: 'Opportunity Scout',
    icon: ShoppingBag,
    color: 'pink',
    tier: 'executive',
    tagline: 'Finds board seats, fractional roles & advisory',
    capabilities: ['Board Seats', 'Fractional Roles', 'Executive Jobs', 'Consulting Opportunities', 'Speaking Engagements', 'Mentorship Opportunities', 'Strategic Partnerships', 'Advisory Roles', 'Opportunity Matching', 'Application Tracking'],
  },
  {
    id: 'recruiter_ai',
    name: 'Recruiter AI',
    short: 'Recruiter',
    role: 'Executive Talent Search',
    icon: UserCheck,
    color: 'emerald',
    tier: 'enterprise',
    tagline: 'Enterprise: find ranked executive candidates',
    capabilities: ['Talent Search', 'Leadership DNA Matching', 'Executive Identity Verification', 'Skills Assessment', 'Experience Analysis', 'Culture Fit Analysis', 'Executive Scoring', 'Ranked Candidates', 'Talent Intelligence', 'Leadership Benchmarking'],
  },
  {
    id: 'founder_ai',
    name: 'Founder AI',
    short: 'Founder',
    role: 'Founding Member Concierge',
    icon: Crown,
    color: 'amber',
    tier: 'founding',
    tagline: 'Exclusive: founder benefits & lifetime perks',
    capabilities: ['Founder Benefits', 'Savings Calculator', 'Lifetime Discounts', 'Referral Strategy', 'Wallet Insights', 'Early Access', 'Community Access', 'Roadmap Voting', 'Exclusive Events', 'Lifetime AI Benefits'],
  },
  {
    id: 'wallet_ai',
    name: 'Executive Wallet AI',
    short: 'Wallet',
    role: 'Financial Benefits Advisor',
    icon: Wallet,
    color: 'teal',
    tier: 'free',
    tagline: 'Tracks earnings & suggests optimizations',
    capabilities: ['Referral Earnings Tracking', 'Wallet Credits', 'Subscription Savings', 'Discount Usage', 'Commission Tracking', 'Projected Earnings', 'Upgrade Timing', 'Credit Utilization', 'Referral Opportunities', 'Savings Optimization'],
  },
  {
    id: 'security_ai',
    name: 'Security AI',
    short: 'Security',
    role: 'Account Protection Guardian',
    icon: Shield,
    color: 'red',
    tier: 'free',
    tagline: 'Monitors threats & recommends actions',
    capabilities: ['Suspicious Login Detection', 'Identity Fraud Monitoring', 'Credential Abuse Detection', 'Impossible Travel Alerts', 'Account Takeover Prevention', 'High Risk Activity Alerts', 'Password Reset Recommendations', 'MFA Suggestions', 'Identity Verification', 'Security Reviews'],
  },
];

export const TIER_LABELS = {
  free: 'Free',
  professional: 'Professional',
  executive: 'Executive',
  founding: 'Founding Member',
  enterprise: 'Enterprise',
};

export const TIER_LEVELS = { free: 0, professional: 1, executive: 2, founding: 3, enterprise: 2 };

export const AGENT_COLORS = {
  indigo: { badge: 'bg-indigo-500/10 text-indigo-300 border-indigo-500/20', icon: 'text-indigo-400', dot: 'bg-indigo-400', gradient: 'from-indigo-500/15 to-indigo-600/5' },
  blue: { badge: 'bg-blue-500/10 text-blue-300 border-blue-500/20', icon: 'text-blue-400', dot: 'bg-blue-400', gradient: 'from-blue-500/15 to-blue-600/5' },
  rose: { badge: 'bg-rose-500/10 text-rose-300 border-rose-500/20', icon: 'text-rose-400', dot: 'bg-rose-400', gradient: 'from-rose-500/15 to-rose-600/5' },
  amber: { badge: 'bg-amber-500/10 text-amber-300 border-amber-500/20', icon: 'text-amber-400', dot: 'bg-amber-400', gradient: 'from-amber-500/15 to-amber-600/5' },
  purple: { badge: 'bg-purple-500/10 text-purple-300 border-purple-500/20', icon: 'text-purple-400', dot: 'bg-purple-400', gradient: 'from-purple-500/15 to-purple-600/5' },
  violet: { badge: 'bg-violet-500/10 text-violet-300 border-violet-500/20', icon: 'text-violet-400', dot: 'bg-violet-400', gradient: 'from-violet-500/15 to-violet-600/5' },
  cyan: { badge: 'bg-cyan-500/10 text-cyan-300 border-cyan-500/20', icon: 'text-cyan-400', dot: 'bg-cyan-400', gradient: 'from-cyan-500/15 to-cyan-600/5' },
  green: { badge: 'bg-green-500/10 text-green-300 border-green-500/20', icon: 'text-green-400', dot: 'bg-green-400', gradient: 'from-green-500/15 to-green-600/5' },
  pink: { badge: 'bg-pink-500/10 text-pink-300 border-pink-500/20', icon: 'text-pink-400', dot: 'bg-pink-400', gradient: 'from-pink-500/15 to-pink-600/5' },
  emerald: { badge: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/20', icon: 'text-emerald-400', dot: 'bg-emerald-400', gradient: 'from-emerald-500/15 to-emerald-600/5' },
  teal: { badge: 'bg-teal-500/10 text-teal-300 border-teal-500/20', icon: 'text-teal-400', dot: 'bg-teal-400', gradient: 'from-teal-500/15 to-teal-600/5' },
  red: { badge: 'bg-red-500/10 text-red-300 border-red-500/20', icon: 'text-red-400', dot: 'bg-red-400', gradient: 'from-red-500/15 to-red-600/5' },
};

export function getAgent(id) {
  return AI_AGENTS.find(a => a.id === id);
}

export function getAgentColor(color) {
  return AGENT_COLORS[color] || AGENT_COLORS.indigo;
}

export const QUICK_TASKS = [
  { label: 'Prepare me for tomorrow\'s Board Meeting', agent: 'executive_chief_of_staff' },
  { label: 'Update my resume', agent: 'career_ai' },
  { label: 'Find CTO jobs', agent: 'marketplace_ai' },
  { label: 'Recommend leadership books', agent: 'learning_ai' },
  { label: 'Generate a board presentation', agent: 'board_advisor' },
  { label: 'Draft an executive email', agent: 'executive_chief_of_staff' },
  { label: 'Track my promotion readiness', agent: 'career_ai' },
  { label: 'Practice a mock interview', agent: 'interview_ai' },
  { label: 'Analyze my leadership gaps', agent: 'leadership_dna_ai' },
  { label: 'Suggest networking connections', agent: 'networking_ai' },
];