// ============================================================
// COMPANY INTELLIGENCE SEED DATA
// Core profiles for 150+ organizations across all categories.
// AI enrichment (companyEnrichment.js) fills detailed exec intel.
// ============================================================

export const COMPANY_CATEGORIES = [
  { id: "all", label: "All Organizations", icon: "🌍" },
  { id: "fortune_500", label: "Fortune 500", icon: "🏆" },
  { id: "global_500", label: "Global 500", icon: "🌐" },
  { id: "forbes_2000", label: "Forbes Global 2000", icon: "📊" },
  { id: "magnificent_seven", label: "Magnificent Seven", icon: "💎" },
  { id: "faang", label: "FAANG", icon: "📱" },
  { id: "big_four", label: "Big Four", icon: "📋" },
  { id: "government", label: "Government Agencies", icon: "🏛️" },
  { id: "technology", label: "Technology", icon: "💻" },
  { id: "healthcare", label: "Healthcare", icon: "🏥" },
  { id: "banking", label: "Banking & Finance", icon: "🏦" },
  { id: "manufacturing", label: "Manufacturing", icon: "🏭" },
  { id: "energy", label: "Energy", icon: "⚡" },
  { id: "retail", label: "Retail", icon: "🛒" },
  { id: "telecommunications", label: "Telecommunications", icon: "📡" },
  { id: "airlines", label: "Airlines", icon: "✈️" },
  { id: "logistics", label: "Logistics", icon: "📦" },
  { id: "consulting", label: "Consulting", icon: "💼" },
  { id: "unicorns", label: "Unicorns & Startups", icon: "🦄" },
];

// Helper to keep seed data compact
const c = (name, data) => ({ name, ...data });

export const SEED_COMPANIES = [
  // === MAGNIFICENT SEVEN ===
  c("Apple", { industry: "Technology", headquarters: "Cupertino, CA", country: "USA", ceo: "Tim Cook", company_type: "public", stock_symbol: "AAPL", founded: 1976, category: "magnificent_seven", fortune_ranking: "#3 Fortune 500", market_cap: "$3.4T", employee_count: 161000, countries_count: 175, cloud_provider: "AWS + iCloud", tags: ["Magnificent Seven", "FAANG", "Fortune 500"] }),
  c("Microsoft", { industry: "Technology", headquarters: "Redmond, WA", country: "USA", ceo: "Satya Nadella", company_type: "public", stock_symbol: "MSFT", founded: 1975, category: "magnificent_seven", fortune_ranking: "#8 Fortune 500", market_cap: "$3.1T", employee_count: 221000, countries_count: 190, cloud_provider: "Azure", tags: ["Magnificent Seven", "Fortune 500"] }),
  c("Alphabet", { industry: "Technology", headquarters: "Mountain View, CA", country: "USA", ceo: "Sundar Pichai", company_type: "public", stock_symbol: "GOOGL", founded: 1998, category: "magnificent_seven", fortune_ranking: "#9 Fortune 500", market_cap: "$2.2T", employee_count: 182000, countries_count: 200, cloud_provider: "Google Cloud", tags: ["Magnificent Seven", "FAANG", "Fortune 500"] }),
  c("Amazon", { industry: "E-Commerce / Cloud", headquarters: "Seattle, WA", country: "USA", ceo: "Andy Jassy", company_type: "public", stock_symbol: "AMZN", founded: 1994, category: "magnificent_seven", fortune_ranking: "#2 Fortune 500", market_cap: "$2.0T", employee_count: 1525000, countries_count: 200, cloud_provider: "AWS", tags: ["Magnificent Seven", "FAANG", "Fortune 500"] }),
  c("NVIDIA", { industry: "Semiconductors", headquarters: "Santa Clara, CA", country: "USA", ceo: "Jensen Huang", company_type: "public", stock_symbol: "NVDA", founded: 1993, category: "magnificent_seven", fortune_ranking: "#22 Fortune 500", market_cap: "$3.0T", employee_count: 29600, countries_count: 50, cloud_provider: "NVIDIA DGX Cloud", tags: ["Magnificent Seven", "Fortune 500"] }),
  c("Meta", { industry: "Technology", headquarters: "Menlo Park, CA", country: "USA", ceo: "Mark Zuckerberg", company_type: "public", stock_symbol: "META", founded: 2004, category: "magnificent_seven", fortune_ranking: "#27 Fortune 500", market_cap: "$1.4T", employee_count: 67317, countries_count: 180, cloud_provider: "Meta Infrastructure", tags: ["Magnificent Seven", "FAANG", "Fortune 500"] }),
  c("Tesla", { industry: "Automotive / Energy", headquarters: "Austin, TX", country: "USA", ceo: "Elon Musk", company_type: "public", stock_symbol: "TSLA", founded: 2003, category: "magnificent_seven", fortune_ranking: "#42 Fortune 500", market_cap: "$0.8T", employee_count: 140473, countries_count: 30, cloud_provider: "AWS", tags: ["Magnificent Seven", "Fortune 500"] }),

  // === FAANG (Netflix is the N) ===
  c("Netflix", { industry: "Entertainment / Streaming", headquarters: "Los Gatos, CA", country: "USA", ceo: "Ted Sarandos / Greg Peters", company_type: "public", stock_symbol: "NFLX", founded: 1997, category: "faang", fortune_ranking: "#117 Fortune 500", market_cap: "$0.3T", employee_count: 13000, countries_count: 190, cloud_provider: "AWS", tags: ["FAANG", "Fortune 500"] }),

  // === FORTUNE 500 TOP ===
  c("Walmart", { industry: "Retail", headquarters: "Bentonville, AR", country: "USA", ceo: "Doug McMillon", company_type: "public", stock_symbol: "WMT", founded: 1962, category: "fortune_500", fortune_ranking: "#1 Fortune 500", global_ranking: "#1 Global 500", market_cap: "$0.7T", employee_count: 2100000, countries_count: 24, tags: ["Fortune 500", "Global 500", "Forbes 2000"] }),
  c("CVS Health", { industry: "Healthcare / Retail", headquarters: "Woonsocket, RI", country: "USA", ceo: "David Joyner", company_type: "public", stock_symbol: "CVS", founded: 1963, category: "fortune_500", fortune_ranking: "#6 Fortune 500", employee_count: 300000, tags: ["Fortune 500"] }),
  c("UnitedHealth Group", { industry: "Healthcare / Insurance", headquarters: "Minnetonka, MN", country: "USA", ceo: "Stephen Hemsley", company_type: "public", stock_symbol: "UNH", founded: 1977, category: "fortune_500", fortune_ranking: "#5 Fortune 500", market_cap: "$0.5T", employee_count: 440000, tags: ["Fortune 500", "Forbes 2000"] }),
  c("Exxon Mobil", { industry: "Oil & Gas", headquarters: "Spring, TX", country: "USA", ceo: "Darren Woods", company_type: "public", stock_symbol: "XOM", founded: 1999, category: "fortune_500", fortune_ranking: "#7 Fortune 500", market_cap: "$0.5T", employee_count: 62000, tags: ["Fortune 500", "Energy"] }),
  c("Berkshire Hathaway", { industry: "Conglomerate", headquarters: "Omaha, NE", country: "USA", ceo: "Warren Buffett", company_type: "public", stock_symbol: "BRK.A", founded: 1839, category: "fortune_500", fortune_ranking: "#4 Fortune 500", market_cap: "$0.9T", employee_count: 396500, tags: ["Fortune 500"] }),
  c("McKesson", { industry: "Healthcare Distribution", headquarters: "Irving, TX", country: "USA", ceo: "Brian Tyler", company_type: "public", stock_symbol: "MCK", founded: 1833, category: "fortune_500", fortune_ranking: "#10 Fortune 500", employee_count: 51000, tags: ["Fortune 500"] }),
  c("Chevron", { industry: "Oil & Gas", headquarters: "San Ramon, CA", country: "USA", ceo: "Mike Wirth", company_type: "public", stock_symbol: "CVX", founded: 1879, category: "fortune_500", fortune_ranking: "#11 Fortune 500", market_cap: "$0.3T", employee_count: 43700, tags: ["Fortune 500", "Energy"] }),
  c("Costco", { industry: "Retail", headquarters: "Issaquah, WA", country: "USA", ceo: "Ron Vachris", company_type: "public", stock_symbol: "COST", founded: 1983, category: "fortune_500", fortune_ranking: "#12 Fortune 500", market_cap: "$0.4T", employee_count: 316000, tags: ["Fortune 500", "Retail"] }),
  c("Home Depot", { industry: "Retail", headquarters: "Atlanta, GA", country: "USA", ceo: "Ted Decker", company_type: "public", stock_symbol: "HD", founded: 1978, category: "fortune_500", fortune_ranking: "#14 Fortune 500", market_cap: "$0.4T", employee_count: 471600, tags: ["Fortune 500", "Retail"] }),
  c("JPMorgan Chase", { industry: "Banking", headquarters: "New York, NY", country: "USA", ceo: "Jamie Dimon", company_type: "public", stock_symbol: "JPM", founded: 2000, category: "fortune_500", fortune_ranking: "#15 Fortune 500", market_cap: "$0.6T", employee_count: 309926, tags: ["Fortune 500", "Banking"] }),
  c("Verizon", { industry: "Telecommunications", headquarters: "New York, NY", country: "USA", ceo: "Hans Vestberg", company_type: "public", stock_symbol: "VZ", founded: 2000, category: "fortune_500", fortune_ranking: "#16 Fortune 500", employee_count: 339000, tags: ["Fortune 500", "Telecommunications"] }),

  // === GLOBAL 500 (international) ===
  c("State Grid", { industry: "Utilities", headquarters: "Beijing", country: "China", ceo: "Zhang Zhihua", company_type: "government", founded: 2002, category: "global_500", global_ranking: "#3 Global 500", revenue: "$545B", employee_count: 870000, tags: ["Global 500"] }),
  c("China National Petroleum", { industry: "Oil & Gas", headquarters: "Beijing", country: "China", ceo: "Dai Houliang", company_type: "government", founded: 1988, category: "global_500", global_ranking: "#5 Global 500", employee_count: 1037000, tags: ["Global 500"] }),
  c("Sinopec", { industry: "Oil & Gas", headquarters: "Beijing", country: "China", ceo: "Ma Yongsheng", company_type: "public", stock_symbol: "0386.HK", founded: 1998, category: "global_500", global_ranking: "#6 Global 500", employee_count: 374800, tags: ["Global 500"] }),
  c("Toyota", { industry: "Automotive", headquarters: "Toyota, Aichi", country: "Japan", ceo: "Koji Sato", company_type: "public", stock_symbol: "7203.T", founded: 1937, category: "global_500", global_ranking: "#10 Global 500", market_cap: "$0.3T", employee_count: 380000, tags: ["Global 500", "Forbes 2000"] }),
  c("Volkswagen", { industry: "Automotive", headquarters: "Wolfsburg", country: "Germany", ceo: "Oliver Blume", company_type: "public", stock_symbol: "VOW3.DE", founded: 1937, category: "global_500", global_ranking: "#11 Global 500", employee_count: 684000, tags: ["Global 500"] }),
  c("Saudi Aramco", { industry: "Oil & Gas", headquarters: "Dhahran", country: "Saudi Arabia", ceo: "Amin Nasser", company_type: "public", stock_symbol: "2222.SR", founded: 1933, category: "global_500", global_ranking: "#4 Global 500", market_cap: "$1.8T", employee_count: 70496, tags: ["Global 500", "Energy"] }),
  c("Samsung Electronics", { industry: "Technology / Electronics", headquarters: "Suwon", country: "South Korea", ceo: "Han Jong-hee", company_type: "public", stock_symbol: "005930.KS", founded: 1969, category: "global_500", global_ranking: "#15 Global 500", market_cap: "$0.4T", employee_count: 267937, tags: ["Global 500", "Forbes 2000"] }),
  c("Shell", { industry: "Oil & Gas", headquarters: "London", country: "UK", ceo: "Wael Sawan", company_type: "public", stock_symbol: "SHEL.L", founded: 1907, category: "global_500", global_ranking: "#12 Global 500", employee_count: 93000, tags: ["Global 500", "Energy"] }),
  c("BYD", { industry: "Automotive / EV", headquarters: "Shenzhen", country: "China", ceo: "Wang Chuanfu", company_type: "public", stock_symbol: "1211.HK", founded: 1995, category: "global_500", global_ranking: "#143 Global 500", employee_count: 700000, tags: ["Global 500"] }),

  // === BIG FOUR ===
  c("Deloitte", { industry: "Professional Services", headquarters: "London", country: "UK", ceo: "Joe Ucuzoglu", company_type: "private", founded: 1845, category: "big_four", revenue: "$64.9B", employee_count: 457000, countries_count: 150, tags: ["Big Four", "Consulting"] }),
  c("PwC", { industry: "Professional Services", headquarters: "London", country: "UK", ceo: "Paul Griggs / Bob Moritz", company_type: "private", founded: 1998, category: "big_four", revenue: "$54.3B", employee_count: 364000, countries_count: 152, tags: ["Big Four", "Consulting"] }),
  c("EY", { industry: "Professional Services", headquarters: "London", country: "UK", ceo: "Jan Triskatis / Janet Truncale", company_type: "private", founded: 1989, category: "big_four", revenue: "$51.4B", employee_count: 395000, countries_count: 150, tags: ["Big Four", "Consulting"] }),
  c("KPMG", { industry: "Professional Services", headquarters: "Amstelveen", country: "Netherlands", ceo: "Bill Thomas", company_type: "private", founded: 1987, category: "big_four", revenue: "$38.4B", employee_count: 273000, countries_count: 143, tags: ["Big Four", "Consulting"] }),

  // === GOVERNMENT AGENCIES ===
  c("U.S. Department of Defense", { industry: "Government / Defense", headquarters: "Arlington, VA", country: "USA", ceo: "Pete Hegseth (Secretary)", company_type: "government", founded: 1947, category: "government", employee_count: 2900000, tags: ["Government"] }),
  c("U.S. General Services Administration", { industry: "Government", headquarters: "Washington, DC", country: "USA", ceo: "Stephen Ehikian (Acting)", company_type: "government", founded: 1949, category: "government", employee_count: 11000, tags: ["Government"] }),
  c("U.S. Department of Health & Human Services", { industry: "Government / Healthcare", headquarters: "Washington, DC", country: "USA", ceo: "Robert F. Kennedy Jr. (Secretary)", company_type: "government", founded: 1953, category: "government", employee_count: 80000, tags: ["Government"] }),
  c("U.S. Department of Veterans Affairs", { industry: "Government / Healthcare", headquarters: "Washington, DC", country: "USA", ceo: "Doug Collins (Secretary)", company_type: "government", founded: 1989, category: "government", employee_count: 413000, tags: ["Government"] }),
  c("NASA", { industry: "Government / Aerospace", headquarters: "Washington, DC", country: "USA", ceo: "Sean Duffy (Acting Admin)", company_type: "government", founded: 1958, category: "government", employee_count: 18000, tags: ["Government", "Aerospace"] }),
  c("U.S. Department of Homeland Security", { industry: "Government / Security", headquarters: "Washington, DC", country: "USA", ceo: "Kristi Noem (Secretary)", company_type: "government", founded: 2002, category: "government", employee_count: 240000, tags: ["Government"] }),
  c("U.S. Postal Service", { industry: "Government / Logistics", headquarters: "Washington, DC", country: "USA", ceo: "David Steiner (Postmaster Gen.)", company_type: "government", founded: 1775, category: "government", employee_count: 640000, tags: ["Government", "Logistics"] }),

  // === TECHNOLOGY ===
  c("Oracle", { industry: "Technology / Software", headquarters: "Austin, TX", country: "USA", ceo: "Safra Catz", company_type: "public", stock_symbol: "ORCL", founded: 1977, category: "technology", fortune_ranking: "#41 Fortune 500", market_cap: "$0.5T", employee_count: 164000, cloud_provider: "Oracle Cloud", tags: ["Technology", "Fortune 500"] }),
  c("IBM", { industry: "Technology", headquarters: "Armonk, NY", country: "USA", ceo: "Arvind Krishna", company_type: "public", stock_symbol: "IBM", founded: 1911, category: "technology", fortune_ranking: "#63 Fortune 500", employee_count: 282000, cloud_provider: "IBM Cloud", tags: ["Technology", "Fortune 500"] }),
  c("Intel", { industry: "Semiconductors", headquarters: "Santa Clara, CA", country: "USA", ceo: "Lip-Bu Tan", company_type: "public", stock_symbol: "INTC", founded: 1968, category: "technology", fortune_ranking: "#50 Fortune 500", employee_count: 108900, tags: ["Technology", "Fortune 500"] }),
  c("AMD", { industry: "Semiconductors", headquarters: "Santa Clara, CA", country: "USA", ceo: "Lisa Su", company_type: "public", stock_symbol: "AMD", founded: 1969, category: "technology", fortune_ranking: "#48 Fortune 500", market_cap: "$0.3T", employee_count: 26000, tags: ["Technology", "Fortune 500"] }),
  c("Salesforce", { industry: "Technology / SaaS", headquarters: "San Francisco, CA", country: "USA", ceo: "Marc Benioff", company_type: "public", stock_symbol: "CRM", founded: 1999, category: "technology", fortune_ranking: "#61 Fortune 500", market_cap: "$0.3T", employee_count: 72972, cloud_provider: "AWS + GCP", tags: ["Technology", "Fortune 500"] }),
  c("Adobe", { industry: "Technology / Software", headquarters: "San Jose, CA", country: "USA", ceo: "Shantanu Narayen", company_type: "public", stock_symbol: "ADBE", founded: 1982, category: "technology", fortune_ranking: "#90 Fortune 500", market_cap: "$0.2T", employee_count: 30000, cloud_provider: "AWS + Azure", tags: ["Technology", "Fortune 500"] }),
  c("Cisco", { industry: "Technology / Networking", headquarters: "San Jose, CA", country: "USA", ceo: "Chuck Robbins", company_type: "public", stock_symbol: "CSCO", founded: 1984, category: "technology", fortune_ranking: "#53 Fortune 500", employee_count: 84900, tags: ["Technology", "Fortune 500"] }),
  c("SAP", { industry: "Technology / Software", headquarters: "Walldorf", country: "Germany", ceo: "Christian Klein", company_type: "public", stock_symbol: "SAP.DE", founded: 1972, category: "technology", employee_count: 108000, cloud_provider: "SAP Cloud", tags: ["Technology", "Forbes 2000"] }),
  c("ServiceNow", { industry: "Technology / SaaS", headquarters: "Santa Clara, CA", country: "USA", ceo: "Bill McDermott", company_type: "public", stock_symbol: "NOW", founded: 2004, category: "technology", fortune_ranking: "#172 Fortune 500", employee_count: 22907, cloud_provider: "AWS", tags: ["Technology", "Fortune 500"] }),
  c("Snowflake", { industry: "Technology / Data", headquarters: "Bozeman, MT", country: "USA", ceo: "Sridhar Ramaswamy", company_type: "public", stock_symbol: "SNOW", founded: 2012, category: "technology", employee_count: 3900, cloud_provider: "AWS + Azure + GCP", tags: ["Technology"] }),
  c("Palantir", { industry: "Technology / Data", headquarters: "Denver, CO", country: "USA", ceo: "Alex Karp", company_type: "public", stock_symbol: "PLTR", founded: 2003, category: "technology", employee_count: 4300, tags: ["Technology"] }),
  c("Dell Technologies", { industry: "Technology", headquarters: "Round Rock, TX", country: "USA", ceo: "Michael Dell", company_type: "public", stock_symbol: "DELL", founded: 1984, category: "technology", fortune_ranking: "#31 Fortune 500", employee_count: 120000, tags: ["Technology", "Fortune 500"] }),
  c("HP", { industry: "Technology", headquarters: "Palo Alto, CA", country: "USA", ceo: "Enrique Lores", company_type: "public", stock_symbol: "HPQ", founded: 1939, category: "technology", fortune_ranking: "#62 Fortune 500", employee_count: 58000, tags: ["Technology", "Fortune 500"] }),
  c("VMware", { industry: "Technology / Software", headquarters: "Palo Alto, CA", country: "USA", ceo: "Hariharan Subramanian", company_type: "subsidiary", founded: 1998, category: "technology", employee_count: 38000, tags: ["Technology"] }),

  // === HEALTHCARE ===
  c("Johnson & Johnson", { industry: "Healthcare / Pharma", headquarters: "New Brunswick, NJ", country: "USA", ceo: "Joaquin Duato", company_type: "public", stock_symbol: "JNJ", founded: 1886, category: "healthcare", fortune_ranking: "#35 Fortune 500", market_cap: "$0.4T", employee_count: 137800, tags: ["Healthcare", "Fortune 500"] }),
  c("Pfizer", { industry: "Pharmaceuticals", headquarters: "New York, NY", country: "USA", ceo: "Albert Bourla", company_type: "public", stock_symbol: "PFE", founded: 1849, category: "healthcare", fortune_ranking: "#46 Fortune 500", employee_count: 88000, tags: ["Healthcare", "Fortune 500"] }),
  c("AbbVie", { industry: "Pharmaceuticals", headquarters: "North Chicago, IL", country: "USA", ceo: "Robert Michael", company_type: "public", stock_symbol: "ABBV", founded: 2013, category: "healthcare", fortune_ranking: "#77 Fortune 500", employee_count: 76600, tags: ["Healthcare", "Fortune 500"] }),
  c("Merck", { industry: "Pharmaceuticals", headquarters: "Rahway, NJ", country: "USA", ceo: "Robert Davis", company_type: "public", stock_symbol: "MRK", founded: 1891, category: "healthcare", fortune_ranking: "#75 Fortune 500", employee_count: 69000, tags: ["Healthcare", "Fortune 500"] }),
  c("Abbott Laboratories", { industry: "Healthcare / Medical Devices", headquarters: "Abbott Park, IL", country: "USA", ceo: "Robert Ford", company_type: "public", stock_symbol: "ABT", founded: 1888, category: "healthcare", fortune_ranking: "#80 Fortune 500", employee_count: 114000, tags: ["Healthcare", "Fortune 500"] }),
  c("Medtronic", { industry: "Medical Devices", headquarters: "Galway", country: "Ireland", ceo: "Geoff Martha", company_type: "public", stock_symbol: "MDT", founded: 1949, category: "healthcare", employee_count: 95000, countries_count: 150, tags: ["Healthcare"] }),
  c("Eli Lilly", { industry: "Pharmaceuticals", headquarters: "Indianapolis, IN", country: "USA", ceo: "David Ricks", company_type: "public", stock_symbol: "LLY", founded: 1876, category: "healthcare", fortune_ranking: "#128 Fortune 500", market_cap: "$0.7T", employee_count: 43000, tags: ["Healthcare", "Fortune 500"] }),
  c("Novartis", { industry: "Pharmaceuticals", headquarters: "Basel", country: "Switzerland", ceo: "Vas Narasimhan", company_type: "public", stock_symbol: "NOVN.SW", founded: 1996, category: "healthcare", employee_count: 76000, tags: ["Healthcare", "Forbes 2000"] }),
  c("Roche", { industry: "Pharmaceuticals", headquarters: "Basel", country: "Switzerland", ceo: "Thomas Schinecker", company_type: "public", stock_symbol: "ROG.SW", founded: 1896, category: "healthcare", employee_count: 100000, tags: ["Healthcare", "Forbes 2000"] }),
  c("Boston Scientific", { industry: "Medical Devices", headquarters: "Marlborough, MA", country: "USA", ceo: "Mike Mahoney", company_type: "public", stock_symbol: "BSX", founded: 1979, category: "healthcare", employee_count: 41000, tags: ["Healthcare"] }),

  // === BANKING & FINANCE ===
  c("Bank of America", { industry: "Banking", headquarters: "Charlotte, NC", country: "USA", ceo: "Brian Moynihan", company_type: "public", stock_symbol: "BAC", founded: 1998, category: "banking", fortune_ranking: "#25 Fortune 500", market_cap: "$0.3T", employee_count: 213000, tags: ["Banking", "Fortune 500"] }),
  c("Citigroup", { industry: "Banking", headquarters: "New York, NY", country: "USA", ceo: "Jane Fraser", company_type: "public", stock_symbol: "C", founded: 1812, category: "banking", fortune_ranking: "#33 Fortune 500", employee_count: 229000, tags: ["Banking", "Fortune 500"] }),
  c("Wells Fargo", { industry: "Banking", headquarters: "San Francisco, CA", country: "USA", ceo: "Charlie Scharf", company_type: "public", stock_symbol: "WFC", founded: 1852, category: "banking", fortune_ranking: "#34 Fortune 500", employee_count: 218000, tags: ["Banking", "Fortune 500"] }),
  c("Goldman Sachs", { industry: "Investment Banking", headquarters: "New York, NY", country: "USA", ceo: "David Solomon", company_type: "public", stock_symbol: "GS", founded: 1869, category: "banking", fortune_ranking: "#55 Fortune 500", employee_count: 45500, tags: ["Banking", "Fortune 500"] }),
  c("Morgan Stanley", { industry: "Investment Banking", headquarters: "New York, NY", country: "USA", ceo: "Ted Pick", company_type: "public", stock_symbol: "MS", founded: 1935, category: "banking", fortune_ranking: "#66 Fortune 500", employee_count: 80000, tags: ["Banking", "Fortune 500"] }),
  c("HSBC", { industry: "Banking", headquarters: "London", country: "UK", ceo: "Georges Elhedery", company_type: "public", stock_symbol: "HSBA.L", founded: 1865, category: "banking", employee_count: 219000, countries_count: 62, tags: ["Banking", "Forbes 2000"] }),
  c("Barclays", { industry: "Banking", headquarters: "London", country: "UK", ceo: "C.S. Venkatakrishnan", company_type: "public", stock_symbol: "BARC.L", founded: 1690, category: "banking", employee_count: 85000, tags: ["Banking", "Forbes 2000"] }),
  c("Deutsche Bank", { industry: "Banking", headquarters: "Frankfurt", country: "Germany", ceo: "Christian Sewing", company_type: "public", stock_symbol: "DBK.DE", founded: 1870, category: "banking", employee_count: 90000, tags: ["Banking", "Forbes 2000"] }),
  c("UBS", { industry: "Banking", headquarters: "Zurich", country: "Switzerland", ceo: "Sergio Ermotti", company_type: "public", stock_symbol: "UBSG.SW", founded: 1862, category: "banking", employee_count: 108000, tags: ["Banking", "Forbes 2000"] }),
  c("Visa", { industry: "Financial Services", headquarters: "San Francisco, CA", country: "USA", ceo: "Ryan McInerney", company_type: "public", stock_symbol: "V", founded: 1958, category: "banking", fortune_ranking: "#137 Fortune 500", market_cap: "$0.6T", employee_count: 26500, tags: ["Banking", "Fortune 500"] }),

  // === MANUFACTURING ===
  c("Boeing", { industry: "Aerospace / Manufacturing", headquarters: "Arlington, VA", country: "USA", ceo: "Kelly Ortberg", company_type: "public", stock_symbol: "BA", founded: 1916, category: "manufacturing", fortune_ranking: "#57 Fortune 500", employee_count: 171000, tags: ["Manufacturing", "Fortune 500"] }),
  c("General Electric", { industry: "Conglomerate / Manufacturing", headquarters: "Cincinnati, OH", country: "USA", ceo: "Larry Culp", company_type: "public", stock_symbol: "GE", founded: 1892, category: "manufacturing", fortune_ranking: "#88 Fortune 500", employee_count: 80000, tags: ["Manufacturing", "Fortune 500"] }),
  c("Caterpillar", { industry: "Manufacturing / Heavy Equipment", headquarters: "Irving, TX", country: "USA", ceo: "Joe Creed", company_type: "public", stock_symbol: "CAT", founded: 1925, category: "manufacturing", fortune_ranking: "#47 Fortune 500", employee_count: 113000, tags: ["Manufacturing", "Fortune 500"] }),
  c("3M", { industry: "Manufacturing / Conglomerate", headquarters: "Saint Paul, MN", country: "USA", ceo: "William Brown", company_type: "public", stock_symbol: "MMM", founded: 1902, category: "manufacturing", fortune_ranking: "#120 Fortune 500", employee_count: 93000, tags: ["Manufacturing", "Fortune 500"] }),
  c("Honeywell", { industry: "Conglomerate / Manufacturing", headquarters: "Charlotte, NC", country: "USA", ceo: "Vimal Kapur", company_type: "public", stock_symbol: "HON", founded: 1906, category: "manufacturing", fortune_ranking: "#82 Fortune 500", employee_count: 102000, tags: ["Manufacturing", "Fortune 500"] }),
  c("Siemens", { industry: "Manufacturing / Technology", headquarters: "Munich", country: "Germany", ceo: "Roland Busch", company_type: "public", stock_symbol: "SIE.DE", founded: 1847, category: "manufacturing", employee_count: 320000, tags: ["Manufacturing", "Forbes 2000"] }),
  c("Lockheed Martin", { industry: "Aerospace / Defense", headquarters: "Bethesda, MD", country: "USA", ceo: "Jim Taiclet", company_type: "public", stock_symbol: "LMT", founded: 1995, category: "manufacturing", fortune_ranking: "#64 Fortune 500", employee_count: 122000, tags: ["Manufacturing", "Fortune 500"] }),
  c("Raytheon Technologies", { industry: "Aerospace / Defense", headquarters: "Arlington, VA", country: "USA", ceo: "Gregory Hayes", company_type: "public", stock_symbol: "RTX", founded: 2020, category: "manufacturing", fortune_ranking: "#45 Fortune 500", employee_count: 171000, tags: ["Manufacturing", "Fortune 500"] }),
  c("Deere & Company", { industry: "Manufacturing / Agriculture", headquarters: "Moline, IL", country: "USA", ceo: "John May", company_type: "public", stock_symbol: "DE", founded: 1837, category: "manufacturing", fortune_ranking: "#70 Fortune 500", employee_count: 83000, tags: ["Manufacturing", "Fortune 500"] }),

  // === ENERGY ===
  c("ConocoPhillips", { industry: "Oil & Gas", headquarters: "Houston, TX", country: "USA", ceo: "Ryan Lance", company_type: "public", stock_symbol: "COP", founded: 1917, category: "energy", fortune_ranking: "#93 Fortune 500", employee_count: 11400, tags: ["Energy", "Fortune 500"] }),
  c("TotalEnergies", { industry: "Oil & Gas", headquarters: "Courbevoie", country: "France", ceo: "Patrick Pouyanné", company_type: "public", stock_symbol: "TTE.PA", founded: 1924, category: "energy", employee_count: 102579, tags: ["Energy", "Forbes 2000"] }),
  c("BP", { industry: "Oil & Gas", headquarters: "London", country: "UK", ceo: "Murray Auchincloss", company_type: "public", stock_symbol: "BP.L", founded: 1908, category: "energy", employee_count: 67600, tags: ["Energy", "Forbes 2000"] }),
  c("NextEra Energy", { industry: "Renewable Energy", headquarters: "Juno Beach, FL", country: "USA", ceo: "John Ketchum", company_type: "public", stock_symbol: "NEE", founded: 1984, category: "energy", fortune_ranking: "#95 Fortune 500", employee_count: 14900, tags: ["Energy", "Fortune 500"] }),
  c("Duke Energy", { industry: "Utilities", headquarters: "Charlotte, NC", country: "USA", ceo: "Lynn Good", company_type: "public", stock_symbol: "DUK", founded: 1904, category: "energy", fortune_ranking: "#104 Fortune 500", employee_count: 28800, tags: ["Energy", "Fortune 500"] }),

  // === RETAIL ===
  c("Target", { industry: "Retail", headquarters: "Minneapolis, MN", country: "USA", ceo: "Brian Cornell", company_type: "public", stock_symbol: "TGT", founded: 1902, category: "retail", fortune_ranking: "#29 Fortune 500", employee_count: 415000, tags: ["Retail", "Fortune 500"] }),
  c("Lowe's", { industry: "Retail", headquarters: "Mooresville, NC", country: "USA", ceo: "Marvin Ellison", company_type: "public", stock_symbol: "LOW", founded: 1921, category: "retail", fortune_ranking: "#36 Fortune 500", employee_count: 300000, tags: ["Retail", "Fortune 500"] }),
  c("Kroger", { industry: "Retail / Grocery", headquarters: "Cincinnati, OH", country: "USA", ceo: "Rodney McMullen", company_type: "public", stock_symbol: "KR", founded: 1883, category: "retail", fortune_ranking: "#23 Fortune 500", employee_count: 420000, tags: ["Retail", "Fortune 500"] }),
  c("TJX Companies", { industry: "Retail", headquarters: "Framingham, MA", country: "USA", ceo: "Ernie Herrman", company_type: "public", stock_symbol: "TJX", founded: 1976, category: "retail", fortune_ranking: "#52 Fortune 500", employee_count: 321000, tags: ["Retail", "Fortune 500"] }),
  c("Walgreens", { industry: "Retail / Pharmacy", headquarters: "Deerfield, IL", country: "USA", ceo: "Tim Wentworth", company_type: "public", stock_symbol: "WBA", founded: 1901, category: "retail", fortune_ranking: "#19 Fortune 500", employee_count: 330000, tags: ["Retail", "Fortune 500"] }),

  // === TELECOMMUNICATIONS ===
  c("AT&T", { industry: "Telecommunications", headquarters: "Dallas, TX", country: "USA", ceo: "John Stankey", company_type: "public", stock_symbol: "T", founded: 1983, category: "telecommunications", fortune_ranking: "#13 Fortune 500", employee_count: 101000, tags: ["Telecommunications", "Fortune 500"] }),
  c("T-Mobile", { industry: "Telecommunications", headquarters: "Bellevue, WA", country: "USA", ceo: "Mike Sievert", company_type: "public", stock_symbol: "TMUS", founded: 1994, category: "telecommunications", fortune_ranking: "#51 Fortune 500", employee_count: 71000, tags: ["Telecommunications", "Fortune 500"] }),
  c("Comcast", { industry: "Telecommunications / Media", headquarters: "Philadelphia, PA", country: "USA", ceo: "Mike Cavanagh / Brian Roberts", company_type: "public", stock_symbol: "CMCSA", founded: 1963, category: "telecommunications", fortune_ranking: "#20 Fortune 500", employee_count: 300000, tags: ["Telecommunications", "Fortune 500"] }),
  c("Charter Communications", { industry: "Telecommunications", headquarters: "Stamford, CT", country: "USA", ceo: "Chris Winfrey", company_type: "public", stock_symbol: "CHTR", founded: 1993, category: "telecommunications", fortune_ranking: "#74 Fortune 500", employee_count: 95000, tags: ["Telecommunications", "Fortune 500"] }),
  c("Vodafone", { industry: "Telecommunications", headquarters: "Newbury", country: "UK", ceo: "Margherita Della Valle", company_type: "public", stock_symbol: "VOD.L", founded: 1991, category: "telecommunications", employee_count: 95000, tags: ["Telecommunications", "Forbes 2000"] }),
  c("Deutsche Telekom", { industry: "Telecommunications", headquarters: "Bonn", country: "Germany", ceo: "Tim Höttges", company_type: "public", stock_symbol: "DTE.DE", founded: 1995, category: "telecommunications", employee_count: 224000, tags: ["Telecommunications", "Forbes 2000"] }),

  // === AIRLINES ===
  c("Delta Air Lines", { industry: "Airlines", headquarters: "Atlanta, GA", country: "USA", ceo: "Ed Bastian", company_type: "public", stock_symbol: "DAL", founded: 1925, category: "airlines", fortune_ranking: "#67 Fortune 500", employee_count: 91561, tags: ["Airlines", "Fortune 500"] }),
  c("American Airlines", { industry: "Airlines", headquarters: "Fort Worth, TX", country: "USA", ceo: "Robert Isom", company_type: "public", stock_symbol: "AAL", founded: 1926, category: "airlines", fortune_ranking: "#49 Fortune 500", employee_count: 134700, tags: ["Airlines", "Fortune 500"] }),
  c("United Airlines", { industry: "Airlines", headquarters: "Chicago, IL", country: "USA", ceo: "Scott Kirby", company_type: "public", stock_symbol: "UAL", founded: 1926, category: "airlines", fortune_ranking: "#59 Fortune 500", employee_count: 110000, tags: ["Airlines", "Fortune 500"] }),
  c("Southwest Airlines", { industry: "Airlines", headquarters: "Dallas, TX", country: "USA", ceo: "Bob Jordan", company_type: "public", stock_symbol: "LUV", founded: 1967, category: "airlines", fortune_ranking: "#103 Fortune 500", employee_count: 71900, tags: ["Airlines", "Fortune 500"] }),
  c("Emirates", { industry: "Airlines", headquarters: "Dubai", country: "UAE", ceo: "Sheikh Ahmed bin Saeed Al Maktoum", company_type: "government", founded: 1985, category: "airlines", employee_count: 62776, tags: ["Airlines"] }),
  c("Lufthansa", { industry: "Airlines", headquarters: "Cologne", country: "Germany", ceo: "Carsten Spohr", company_type: "public", stock_symbol: "LHA.DE", founded: 1953, category: "airlines", employee_count: 105000, tags: ["Airlines", "Forbes 2000"] }),

  // === LOGISTICS ===
  c("FedEx", { industry: "Logistics", headquarters: "Memphis, TN", country: "USA", ceo: "Raj Subramaniam", company_type: "public", stock_symbol: "FDX", founded: 1971, category: "logistics", fortune_ranking: "#21 Fortune 500", employee_count: 504000, tags: ["Logistics", "Fortune 500"] }),
  c("UPS", { industry: "Logistics", headquarters: "Atlanta, GA", country: "USA", ceo: "Carol Tomé", company_type: "public", stock_symbol: "UPS", founded: 1907, category: "logistics", fortune_ranking: "#26 Fortune 500", employee_count: 490000, tags: ["Logistics", "Fortune 500"] }),
  c("Maersk", { industry: "Logistics / Shipping", headquarters: "Copenhagen", country: "Denmark", ceo: "Vincent Clerc", company_type: "public", stock_symbol: "MAERSK-B.CO", founded: 1904, category: "logistics", employee_count: 100000, tags: ["Logistics", "Forbes 2000"] }),
  c("DHL", { industry: "Logistics", headquarters: "Bonn", country: "Germany", ceo: "Tobias Meyer", company_type: "subsidiary", founded: 1969, category: "logistics", employee_count: 594000, countries_count: 220, tags: ["Logistics"] }),

  // === CONSULTING ===
  c("McKinsey & Company", { industry: "Management Consulting", headquarters: "New York, NY", country: "USA", ceo: "Bob Sternfels", company_type: "private", founded: 1926, category: "consulting", employee_count: 45000, countries_count: 65, tags: ["Consulting"] }),
  c("Boston Consulting Group", { industry: "Management Consulting", headquarters: "Boston, MA", country: "USA", ceo: "Christoph Schweizer", company_type: "private", founded: 1963, category: "consulting", employee_count: 32000, countries_count: 50, tags: ["Consulting"] }),
  c("Bain & Company", { industry: "Management Consulting", headquarters: "Boston, MA", country: "USA", ceo: "Christophe De Vusser", company_type: "private", founded: 1973, category: "consulting", employee_count: 19000, countries_count: 40, tags: ["Consulting"] }),
  c("Accenture", { industry: "Professional Services / Technology", headquarters: "Dublin", country: "Ireland", ceo: "Julie Sweet", company_type: "public", stock_symbol: "ACN", founded: 1989, category: "consulting", fortune_ranking: "#18 Fortune 500", employee_count: 774000, countries_count: 120, tags: ["Consulting", "Fortune 500"] }),
  c("Booz Allen Hamilton", { industry: "Consulting / Government", headquarters: "McLean, VA", country: "USA", ceo: "Horacio Rozanski", company_type: "public", stock_symbol: "BAH", founded: 1914, category: "consulting", fortune_ranking: "#165 Fortune 500", employee_count: 33700, tags: ["Consulting", "Fortune 500"] }),

  // === UNICORNS & STARTUPS ===
  c("SpaceX", { industry: "Aerospace / Space", headquarters: "Hawthorne, CA", country: "USA", ceo: "Elon Musk", company_type: "private", founded: 2002, category: "unicorns", employee_count: 13000, tags: ["Unicorn", "Aerospace"] }),
  c("OpenAI", { industry: "Artificial Intelligence", headquarters: "San Francisco, CA", country: "USA", ceo: "Sam Altman", company_type: "private", founded: 2015, category: "unicorns", employee_count: 2600, tags: ["Unicorn", "AI"] }),
  c("Stripe", { industry: "Financial Technology", headquarters: "South San Francisco, CA", country: "USA", ceo: "Patrick Collison", company_type: "private", founded: 2010, category: "unicorns", employee_count: 8000, tags: ["Unicorn", "Fintech"] }),
  c("Databricks", { industry: "Data / AI", headquarters: "San Francisco, CA", country: "USA", ceo: "Ali Ghodsi", company_type: "private", founded: 2013, category: "unicorns", employee_count: 7000, cloud_provider: "AWS + Azure + GCP", tags: ["Unicorn", "AI"] }),
  c("Canva", { industry: "Technology / Design", headquarters: "Sydney", country: "Australia", ceo: "Melanie Perkins", company_type: "private", founded: 2013, category: "unicorns", employee_count: 4500, tags: ["Unicorn"] }),
  c("ByteDance", { industry: "Technology / Social Media", headquarters: "Beijing", country: "China", ceo: "Liang Rubo", company_type: "private", founded: 2012, category: "unicorns", employee_count: 150000, tags: ["Unicorn"] }),
  c("Revolut", { industry: "Financial Technology", headquarters: "London", country: "UK", ceo: "Nikolay Storonsky", company_type: "private", founded: 2015, category: "unicorns", employee_count: 8000, tags: ["Unicorn", "Fintech"] }),
  c("Anthropic", { industry: "Artificial Intelligence", headquarters: "San Francisco, CA", country: "USA", ceo: "Dario Amodei", company_type: "private", founded: 2021, category: "unicorns", employee_count: 1000, tags: ["Unicorn", "AI"] }),
  c("Klarna", { industry: "Financial Technology", headquarters: "Stockholm", country: "Sweden", ceo: "Sebastian Siemiatkowski", company_type: "private", founded: 2005, category: "unicorns", employee_count: 5000, tags: ["Unicorn", "Fintech"] }),
  c("xAI", { industry: "Artificial Intelligence", headquarters: "Germantown, TN", country: "USA", ceo: "Elon Musk", company_type: "private", founded: 2023, category: "unicorns", employee_count: 600, tags: ["Unicorn", "AI"] }),
];