// Executive Business Case™ PDF generator (jsPDF). Produces a professional,
// procurement-ready report from customer inputs and ROI results.
import { jsPDF } from "jspdf";
import { fmtCurrency, fmtNum, fmtPct } from "@/lib/enterpriseRoiEngine";

export function generateBusinessCasePdf(inputs, assumptions, roi, insights) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const M = 48;
  let y = 60;

  const h = (txt, size, bold) => { doc.setFont("helvetica", bold ? "bold" : "normal"); doc.setFontSize(size); doc.text(txt, M, y); y += size + 8; };
  const p = (txt, size = 10) => { doc.setFont("helvetica", "normal"); doc.setFontSize(size); const lines = doc.splitTextToSize(txt, W - M * 2); doc.text(lines, M, y); y += lines.length * (size + 3) + 4; };
  const section = (txt) => { y += 10; h(txt, 13, true); };
  const row = (label, val) => { doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.text(label, M, y); doc.text(String(val), W - M, y, { align: "right" }); y += 16; };

  h("Executive Business Case™", 20, true);
  p(`Prepared for: ${inputs.organizationName || "Organization"} · ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, 10);
  p("Generated by the EXECLEAD.AI Enterprise Leadership ROI Calculator™. Scenario-based estimates from customer inputs and configurable assumptions — not guarantees.", 9);

  section("1. Executive Summary");
  p(`This business case estimates the potential financial and organizational value of deploying EXECLEAD.AI across a leadership population of ${fmtNum(inputs.leadershipPopulation)} leaders. Estimated annual net business impact: ${fmtCurrency(roi.annualNetValue)}. Estimated three-year ROI: ${fmtPct(roi.threeYearROI)}. Confidence: ${roi.confidence.label}.`);

  section("2. Organization Profile");
  row("Organization", inputs.organizationName || "—");
  row("Industry", inputs.industry || "—");
  row("Country", inputs.country || "—");
  row("Employees", fmtNum(inputs.employees));
  row("Leadership Population", fmtNum(inputs.leadershipPopulation));

  section("3. Current Leadership Investment");
  row("Leadership Development Budget", fmtCurrency(inputs.leadershipDevBudget));
  row("Executive Coaching Budget", fmtCurrency(inputs.executiveCoachingBudget));
  row("Avg Coaching Cost / Leader", fmtCurrency(inputs.avgCoachingCostPerLeader));
  row("Assessment Budget", fmtCurrency(inputs.leadershipAssessmentBudget));
  row("External Recruitment Spend", fmtCurrency(inputs.externalRecruitmentSpend));
  row("Avg Executive Hiring Cost", fmtCurrency(inputs.avgExecutiveHiringCost));
  row("Planned EXECLEAD.AI Investment", fmtCurrency(inputs.plannedExecleadInvestment));

  section("4. Financial Assumptions");
  Object.entries(assumptions).forEach(([k, v]) => row(k, `${v}${k === "loadedLaborRate" ? " $/hr" : "%"}`));

  section("5. Estimated Operational Improvements");
  row("Administrative Hours Saved / yr", `${fmtNum(roi.adminTimeSavedHours)} hrs`);
  row("Reporting Hours Saved / yr", `${fmtNum(roi.reportingTimeSavedHours)} hrs`);
  row("Coaching Capacity", `${fmtNum(roi.newCoachingCapacity)} leaders`);
  row("Assessment Throughput Increase", `${fmtNum(roi.assessmentThroughputIncrease)}`);
  row("Leadership Coverage", `${fmtPct(roi.coverageCurrentPct)} → ${fmtPct(roi.coverageNewPct)}`);

  section("6. Estimated Financial Impact");
  row("Annual Gross Value", fmtCurrency(roi.annualGrossValue));
  row("Annual Investment", fmtCurrency(roi.annualInvestment));
  row("Annual Net Business Impact", fmtCurrency(roi.annualNetValue));
  row("Three-Year Value", fmtCurrency(roi.threeYearValue));
  row("Three-Year ROI", fmtPct(roi.threeYearROI));
  row("Payback Estimate", roi.paybackMonths ? `${roi.paybackMonths} months` : "—");

  section("7. Three-Year Projection");
  [1, 2, 3].forEach((yr) => row(`Year ${yr} (Value / Investment)`, `${fmtCurrency(roi.annualGrossValue * yr)} / ${fmtCurrency(roi.annualInvestment * yr)}`));

  section("8. Executive Readiness, Succession & Leadership Benefits");
  p(`Internal promotions supported: ${fmtNum(roi.hiringAvoided)} (value ${fmtCurrency(roi.internalPromotionValue)}). Leadership coverage expansion: ${fmtNum(roi.coverageExpansionLeaders)} leaders. Coaching capacity gain: ${fmtNum(roi.coachingCapacityIncrease)} leaders. Assessment throughput gain: ${fmtNum(roi.assessmentThroughputIncrease)} assessments.`);

  if (insights && insights.length) {
    section("9. AI Executive Insights™");
    insights.forEach((ins, idx) => p(`${idx + 1}. ${ins}`, 10));
    p("AI-generated observations based on the information you provided. These are estimates for planning purposes and not guarantees.", 9);
  }

  section("10. Risk & Assumption Notes");
  p("Results are scenario-based estimates. Actual outcomes depend on implementation, organizational adoption, leadership engagement, and operational factors. EXECLEAD.AI does not guarantee financial results. Every figure is derived from the customer inputs and assumptions shown above; no hidden formulas are used.");

  section("11. Recommended Next Steps");
  p("1. Review this business case with HR, Finance, and Procurement stakeholders. 2. Validate assumptions against your organizational data. 3. Request an Executive Demo to tailor the deployment plan. 4. Pilot with a leadership cohort and measure readiness improvement.");

  doc.save(`EXECLEAD-Executive-Business-Case-${(inputs.organizationName || "Organization").replace(/\s+/g, "-")}.pdf`);
}