// Executive Business Case™ PDF generator (jsPDF) — V2 with audience variants.
import { jsPDF } from "jspdf";
import { fmtCurrency, fmtNum, fmtPct } from "@/lib/enterpriseRoiEngine";

const AUDIENCES = {
  default: { title: "Executive Business Case™", sections: "all" },
  cfo: { title: "CFO Summary — Executive Business Case™", sections: ["exec", "investment", "assumptions", "impact", "projection", "risks", "next"] },
  chro: { title: "CHRO Summary — Executive Business Case™", sections: ["exec", "profile", "operations", "leadership", "readiness", "succession", "risks", "next"] },
  board: { title: "Board Presentation — Executive Business Case™", sections: ["exec", "impact", "projection", "readiness", "succession", "risks", "next"] },
  procurement: { title: "Procurement Package — Executive Business Case™", sections: ["exec", "profile", "investment", "assumptions", "impact", "risks", "next"] },
  presentation: { title: "Executive Presentation — Executive Business Case™", sections: ["exec", "impact", "projection", "leadership", "next"] },
};

export function generateBusinessCasePdf(inputs, assumptions, roi, insights, audience = "default") {
  const cfg = AUDIENCES[audience] || AUDIENCES.default;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const M = 48;
  let y = 60;
  const has = (k) => cfg.sections === "all" || cfg.sections.includes(k);

  const h = (t, s, b) => { doc.setFont("helvetica", b ? "bold" : "normal"); doc.setFontSize(s); doc.text(t, M, y); y += s + 8; };
  const p = (t, s = 10) => { doc.setFont("helvetica", "normal"); doc.setFontSize(s); const l = doc.splitTextToSize(t, W - M * 2); doc.text(l, M, y); y += l.length * (s + 3) + 4; };
  const sec = (t) => { y += 10; h(t, 13, true); };
  const row = (l, v) => { doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.text(l, M, y); doc.text(String(v), W - M, y, { align: "right" }); y += 16; };
  if (y > 760) { doc.addPage(); y = 60; }

  h(cfg.title, 20, true);
  p(`Prepared for: ${inputs.organizationName || "Organization"} · ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, 10);
  p("Generated by the EXECLEAD.AI Enterprise Leadership ROI Calculator™. Scenario-based planning estimates from customer inputs and configurable assumptions — not guarantees.", 9);

  if (has("exec")) {
    sec("1. Executive Summary");
    p(`This business case estimates the potential operational and financial value of deploying EXECLEAD.AI across a leadership population of ${fmtNum(inputs.leadershipPopulation)} leaders. Estimated annual net business impact: ${fmtCurrency(roi.annualNetValue)}. Estimated three-year ROI: ${fmtPct(roi.threeYearROI)}. Confidence: ${roi.confidence.label}.`);
  }
  if (has("profile")) {
    sec("2. Organization Profile");
    row("Organization", inputs.organizationName || "—");
    row("Industry", inputs.industry || "—");
    row("Country", inputs.country || "—");
    row("Employees", fmtNum(inputs.employees));
    row("Leadership Population", fmtNum(inputs.leadershipPopulation));
  }
  if (has("investment")) {
    sec("3. Current Leadership Investment");
    row("Leadership Development Budget", fmtCurrency(inputs.leadershipDevBudget));
    row("Executive Coaching Budget", fmtCurrency(inputs.executiveCoachingBudget));
    row("Avg Coaching Cost / Leader", fmtCurrency(inputs.avgCoachingCost));
    row("Assessment Budget", fmtCurrency(inputs.leadershipAssessmentBudget));
    row("Executive Recruitment Budget", fmtCurrency(inputs.executiveRecruitmentBudget));
    row("Avg Executive Hiring Cost", fmtCurrency(inputs.avgExecutiveHiringCost));
    row("Estimated Annual Platform Investment", fmtCurrency(inputs.estimatedAnnualPlatformInvestment));
  }
  if (has("operations")) {
    sec("4. Current Operating Model");
    row("Assessments / Year", fmtNum(inputs.assessmentsPerYear));
    row("Succession Reviews", fmtNum(inputs.successionReviews));
    row("Promotion Decisions", fmtNum(inputs.promotionDecisionsPerYear));
    row("Current Coaching Coverage", `${inputs.currentCoachingCoveragePct}%`);
    row("Internal Promotion Rate", `${inputs.internalPromotionPct}%`);
  }
  if (has("assumptions")) {
    sec("5. Financial Assumptions");
    Object.entries(assumptions).forEach(([k, v]) => row(k, `${v}${k === "loadedLaborRate" ? " $/hr" : "%"}`));
  }
  if (has("leadership") || has("readiness") || has("succession")) {
    sec("6. Leadership Intelligence & Readiness Benefits");
    if (has("leadership")) p(`Leadership coverage expansion: ${fmtNum(roi.leadershipCoverageIncrease)} leaders (${fmtPct(inputs.currentCoachingCoveragePct)} → ${fmtPct(roi.newCoveragePct)}). AI coaching capacity: ${fmtNum(roi.aiCoachingCapacity)} additional leaders reached.`);
    if (has("readiness")) p(`Assessment capacity increase: ${fmtNum(roi.assessmentCapacityIncrease)} assessments/year. Coaching capacity: ${fmtNum(roi.newCoachingCapacity)} leaders (from ${fmtNum(roi.currentCoachingCapacity)}).`);
    if (has("succession")) p(`Internal promotion opportunity: ${fmtNum(roi.internalPromotionOpportunity)} leaders. Executive hiring savings: ${fmtCurrency(roi.executiveHiringSavings)} through ${fmtNum(roi.executiveHiringReduction)} avoided external hires.`);
  }
  if (has("impact")) {
    sec("7. Financial Impact");
    row("Annual Gross Value", fmtCurrency(roi.annualGrossValue));
    row("Annual Investment", fmtCurrency(roi.annualPlatformInvestment));
    row("Annual Net Business Impact", fmtCurrency(roi.annualNetValue));
    row("Three-Year ROI", fmtPct(roi.threeYearROI));
    row("Payback Estimate", roi.paybackPeriod ? `${roi.paybackPeriod} months` : "—");
  }
  if (has("projection")) {
    sec("8. Three-Year Projection");
    [1, 2, 3].forEach((yr) => row(`Year ${yr} (Value / Investment)`, `${fmtCurrency(roi.annualGrossValue * yr)} / ${fmtCurrency(roi.annualPlatformInvestment * yr)}`));
  }
  if (insights && insights.length) {
    sec("9. AI Executive Insights™");
    insights.forEach((ins, idx) => p(`${idx + 1}. ${ins}`, 10));
    p("AI-generated planning insights based solely on the information you provided. Estimates for business planning, not guarantees.", 9);
  }
  if (has("risks")) {
    sec("10. Risks & Assumptions");
    p("Results are scenario-based planning estimates. Actual outcomes depend on implementation quality, organizational adoption, leadership engagement, operational practices, and business conditions. EXECLEAD.AI does not guarantee financial outcomes, productivity gains, or return on investment. Every figure is derived from the customer inputs and assumptions shown above; no hidden assumptions are used.");
  }
  if (has("next")) {
    sec("11. Recommended Next Steps");
    p("1. Review this business case with HR, Finance, and Procurement stakeholders. 2. Validate assumptions against your organizational data. 3. Request an Executive Demo to tailor the deployment plan. 4. Pilot with a leadership cohort and measure readiness improvement.");
  }

  doc.save(`EXECLEAD-${cfg.title.split(" ")[0]}-${(inputs.organizationName || "Organization").replace(/\s+/g, "-")}.pdf`);
}