import {
  LayoutDashboard, Fingerprint, Star, Trophy, BookOpen, Briefcase,
  FileText, GraduationCap, Store, Users, Wallet, BadgeCheck,
  CreditCard, Building2, Code2, Brain, MessageSquare, Network,
  BarChart3, Shield, Crown, Gift, Settings as SettingsIcon,
  UserCircle, Cpu, PenLine, TrendingUp, Wrench, Gauge,
  Zap, Receipt, DollarSign, KeyRound, ClipboardCheck, Sparkles,
  Calculator, Boxes, Mail,
} from "lucide-react";

/**
 * EXEC™ Platform Knowledge Index
 * -------------------------------
 * A single source of truth for every module on EXECLEAD.AI.
 * Powers "Where is X?" questions, global commands, and context-aware help.
 */
// ============================================================
// EXEC™ KNOWLEDGE SYNCHRONIZATION METADATA
// Tracks knowledge version, framework versions, and last sync.
// Visible in Developer Diagnostics → EXEC™ Knowledge Audit.
// ============================================================
export const EXEC_KNOWLEDGE_VERSION = "2.0";
export const EXEC_KNOWLEDGE_LAST_SYNC = "2026-07-11";
export const EXEC_PROMPT_VERSION = "2.0";
export const EXEC_PLATFORM_VERSION = "2.0";

// Framework Hierarchy: EELM™ → ELIM™ → EECF™ → ... → Executive Intelligence Profile™
// Every EXEC™ recommendation must align with this architecture.
export const EXEC_FRAMEWORK_HIERARCHY = [
  { id: "eelm", name: "EELM™", full: "EXECLEAD Executive Leadership Methodology™", version: "1.0", description: "The governing methodology that defines how EXECLEAD.AI evaluates, develops, validates, measures, and evolves executive leadership capability." },
  { id: "elim", name: "ELIM™", full: "EXECLEAD Leadership Intelligence Model™", version: "1.0", description: "The intelligence architecture mapping five frameworks, evidence sources, and scoring rules into AI-driven executive insights." },
  { id: "eecf", name: "EECF™", full: "EXECLEAD Executive Competency Framework™", version: "1.0", description: "The global leadership competency standard — six domains, 8-stage maturity model, and verified competency library." },
  { id: "leadership_dna", name: "Leadership DNA™", full: "Leadership DNA™", version: "1.0", description: "AI-powered assessment mapping leadership style, communication, decision-making, influence, and executive presence." },
  { id: "readiness", name: "Executive Readiness™", full: "Executive Readiness Engine™", version: "1.0", description: "Continuous evaluation of how prepared the executive is for their target role across 12 competency dimensions." },
  { id: "reputation", name: "Executive Reputation™", full: "Executive Reputation Framework™", version: "1.0", description: "Professional credit score for leadership (0–1000) growing with contributions, coaching, and community activity." },
  { id: "journey", name: "Executive Journey™", full: "Executive Journey Engine™", version: "1.0", description: "Unified progression system — every meaningful action contributes Journey Points toward one continuous journey." },
  { id: "trust", name: "Executive Trust™", full: "Executive Trust Framework™", version: "1.0", description: "Complete trust ecosystem with 7 trust levels and 11 trust factors scored 0-100." },
  { id: "passport", name: "Executive Passport™", full: "Executive Passport™", version: "1.0", description: "Portable professional identity that belongs to the member, not the employer." },
  { id: "intelligence_profile", name: "Executive Intelligence Profile™", full: "Executive Intelligence Profile™", version: "1.0", description: "The living AI-generated executive identity — single source of truth combining all frameworks." },
];

export const EXEC_KNOWLEDGE_INDEX = [
  {
    id: "dashboard",
    name: "Executive Dashboard",
    aliases: ["dashboard", "home", "main", "overview", "hub"],
    path: "/dashboard",
    category: "Core",
    icon: LayoutDashboard,
    description: "Your central hub tracking the entire leadership journey — metrics, progress, recent activity, and AI recommendations.",
    purpose: "Get a bird's-eye view of your leadership development and see what to work on next.",
    keyFeatures: ["Progress tracking", "Recent simulations", "AI recommendations", "Quick stats"],
    findIt: "Sidebar → Platform → Dashboard, or click the EXECLEAD.AI logo.",
  },
  {
    id: "journey",
    name: "Executive Intelligence Profile™",
    aliases: ["journey", "executive journey", "intelligence profile", "executive profile", "timeline", "journey points", "journey level", "progress", "milestones", "achievements", "archetype", "readiness hero", "executive potential", "ai confidence", "competency radar", "career readiness", "benchmarking", "profile history"],
    path: "/journey",
    category: "Insights",
    icon: TrendingUp,
    description: "The living AI-generated executive identity — a single source of truth that continuously evolves as you learn, practice, publish, and lead. Combines Executive Readiness, Trust, Reputation, Journey, Archetype, Competency Radar, Career Readiness, AI Insights, Growth Plan, Benchmarking, and Profile History into one premium experience.",
    purpose: "See who you are as a leader, how you're improving, what to do next, and where you can go. Your authoritative digital profile of executive development.",
    keyFeatures: ["Executive Readiness Hero", "Executive Potential Gauges", "AI Confidence Score", "Executive Archetype", "12-Competency Radar", "Career Readiness", "Reputation & Trust Summary", "Learning & Leadership Impact", "AI Insights from EXEC™", "Optimized Growth Plan", "Executive Benchmarking", "Profile History Replay", "Export (PDF, Portfolio, Recruiter, Board, Enterprise)"],
    findIt: "Sidebar → Insights → Executive Intelligence Profile.",
  },
  {
    id: "executive-readiness",
    name: "Executive Readiness Engine™",
    aliases: ["readiness", "executive readiness", "how ready am i", "promotion readiness", "capability", "competency", "readiness score", "readiness dimensions", "readiness coach"],
    path: "/executive-readiness",
    category: "Insights",
    icon: TrendingUp,
    description: "Continuously evaluates how prepared you are for your target leadership role. Measures capability across 12 dimensions with industry benchmarks and AI coaching.",
    purpose: "Understand your executive capability, identify gaps, and get AI recommendations for the fastest path to readiness.",
    keyFeatures: ["Readiness Score (0-100%)", "12 Competency Dimensions", "Industry Benchmarks", "AI Readiness Coach", "Career Alignment", "Estimated Timeline"],
    findIt: "Sidebar → Insights → Readiness.",
  },
  {
    id: "executive-passport",
    name: "Executive Passport™",
    aliases: ["passport", "executive passport", "portable identity", "professional identity", "executive identity", "shareable profile", "passport qr"],
    path: "/executive-passport",
    category: "Account",
    icon: TrendingUp,
    description: "A portable professional identity that belongs to you. Contains your Journey Level, Readiness, Trust, Reputation, Legacy, DNA, Career Timeline, and more.",
    purpose: "Carry your executive identity with you. Share public, recruiter, or private views. Export to PDF or QR. Your data always belongs to you.",
    keyFeatures: ["Journey & Readiness", "Trust & Reputation", "Leadership DNA", "Career Timeline", "Public/Recruiter/Private Views", "PDF Export", "QR Code", "Shareable URL"],
    findIt: "Sidebar → Account → Executive Passport.",
  },
  {
    id: "enterprise-intelligence",
    name: "Enterprise Intelligence Dashboard™",
    aliases: ["enterprise intelligence", "org intelligence", "leadership intelligence", "organization dashboard", "enterprise analytics"],
    path: "/enterprise-intelligence",
    category: "Enterprise",
    icon: TrendingUp,
    description: "Provides organizations with actionable leadership intelligence: readiness distribution, journey levels, high-potential talent, risk indicators, and promotion pipeline.",
    purpose: "Give enterprise leaders visibility into their organization's leadership capabilities and development pipeline.",
    keyFeatures: ["Leadership Distribution", "Readiness Heat Maps", "High-Potential Talent", "Risk Indicators", "Promotion Pipeline", "Top Contributors"],
    findIt: "Enterprise Workspace → Enterprise Intelligence.",
  },
  {
    id: "leadership-dna",
    name: "Leadership DNA™",
    aliases: ["leadership dna", "dna", "leadership assessment", "leadership strengths", "competency", "competencies"],
    path: "/leadership-dna",
    category: "Insights",
    icon: Fingerprint,
    description: "An AI-powered assessment that maps your leadership strengths, competencies, and growth areas into a personalized profile.",
    purpose: "Understand your unique leadership fingerprint and identify which competencies to develop next.",
    keyFeatures: ["Competency radar", "Strength & gap analysis", "Personalized growth recommendations"],
    findIt: "Sidebar → Insights → Leadership DNA.",
  },
  {
    id: "intelligence",
    name: "Executive Intelligence Center™",
    aliases: ["intelligence", "executive intelligence", "intelligence center", "competency radar", "domain radar", "elim radar", "maturity radar", "competency domains", "executive strengths", "growth opportunities", "leadership intelligence", "executive intelligence center"],
    path: "/intelligence",
    category: "Insights",
    icon: Brain,
    description: "The flagship intelligence module that transforms competency assessments into actionable executive intelligence. Visualize your six leadership domains, explore competency gaps, connect with Leadership DNA™, track readiness, and receive AI-powered growth recommendations from EXEC™.",
    purpose: "Understand your executive strengths, discover growth opportunities, and build leadership intelligence across all six ELIM™ capability domains.",
    keyFeatures: ["Interactive Domain Radar", "Six Capability Domains", "Competency Intelligence (Verified, Emerging, Developing, Gaps)", "Leadership DNA™ Relationship", "Executive Readiness™ Integration", "AI Executive Insights", "Historical Intelligence Timeline", "Export PNG/PDF", "Fullscreen Mode"],
    findIt: "Sidebar → Insights → Intelligence Center.",
  },
  {
    id: "reputation",
    name: "Executive Reputation™",
    aliases: ["reputation", "executive reputation", "reputation score", "credit score", "professional score"],
    path: "/reputation",
    category: "Insights",
    icon: Star,
    description: "A professional credit score for leadership (0–1000) that grows with your contributions, coaching, and community activity.",
    purpose: "Build a portable, verifiable measure of your leadership credibility.",
    keyFeatures: ["Multi-dimensional score", "Badges & achievements", "Tier progression", "AI improvement coaching"],
    findIt: "Sidebar → Insights → Executive Reputation.",
  },
  {
    id: "rankings",
    name: "Executive Rankings",
    aliases: ["rankings", "leaderboard", "ranking", "executive rankings", "top executives"],
    path: "/executive/rankings",
    category: "Insights",
    icon: Trophy,
    description: "Community leaderboards and peer recognition showcasing top executives by reputation, referrals, and contributions.",
    purpose: "See how you compare to peers and earn recognition for your leadership growth.",
    keyFeatures: ["Reputation leaderboard", "Referral rankings", "Share analytics", "Podium highlights"],
    findIt: "Sidebar → Insights → Executive Rankings.",
  },
  {
    id: "legacy-library",
    name: "Legacy Library",
    aliases: ["legacy library", "legacy", "letters", "leadership letters", "legacy letter"],
    path: "/legacy-library",
    category: "Insights",
    icon: BookOpen,
    description: "A curated collection of leadership letters and wisdom published by experienced executives, with AI-assisted editorial review.",
    purpose: "Learn from real executive experiences and publish your own leadership wisdom for the community.",
    keyFeatures: ["Published leadership letters", "Comments & reactions", "AI editorial review", "Collections & featured content"],
    findIt: "Sidebar → Insights → Legacy Library. Use 'Write Letter' to publish your own.",
  },
  {
    id: "career-studio",
    name: "Career Studio",
    aliases: ["career studio", "career", "career tools", "resume builder", "linkedin"],
    path: "/career-studio",
    category: "Career",
    icon: Briefcase,
    description: "An AI-powered suite for resume building, LinkedIn optimization, cover letters, executive bios, and achievement writing.",
    purpose: "Advance your career with polished, AI-enhanced executive application materials.",
    keyFeatures: ["Resume builder", "LinkedIn optimizer", "Cover letters", "Executive bio", "Achievement writer"],
    findIt: "Sidebar → Career → Career Studio.",
  },
  {
    id: "resume",
    name: "Resume AI",
    aliases: ["resume", "resume ai", "cv", "resume intelligence", "resume analysis"],
    path: "/resume",
    category: "Career",
    icon: FileText,
    description: "AI-powered resume analysis, enhancement, skill-gap detection, and interview preparation.",
    purpose: "Turn your resume into an executive-grade document and identify skills to develop.",
    keyFeatures: ["Resume upload & analysis", "Skill-gap analysis", "Truth Engine report", "Learning roadmap", "Version compare"],
    findIt: "Sidebar → Career → Resume AI.",
  },
  {
    id: "academy",
    name: "Executive Academy",
    aliases: ["academy", "courses", "learning", "lessons", "executive academy", "training", "certifications"],
    path: "/academy",
    category: "Platform",
    icon: GraduationCap,
    description: "Structured courses, learning paths, and certifications covering leadership foundations, strategy, and executive skills — adapted to every career stage from student to C-suite.",
    purpose: "Build executive capabilities through guided, AI-coached learning journeys.",
    keyFeatures: ["Course catalog", "AI coach per lesson", "Quizzes & certificates", "Learning path recommendations"],
    findIt: "Sidebar → Platform → Academy.",
  },
  {
    id: "marketplace",
    name: "Marketplace",
    aliases: ["marketplace", "bundles", "executive bundles", "premium content", "buy"],
    path: "/marketplace",
    category: "Platform",
    icon: Store,
    description: "Executive bundles, premium content collections, and company intelligence packages.",
    purpose: "Discover premium learning bundles and targeted intelligence to accelerate your goals.",
    keyFeatures: ["Executive bundles", "Company collections", "AI content tools", "One-click purchase"],
    findIt: "Sidebar → Platform → Marketplace.",
  },
  {
    id: "network",
    name: "Executive Network",
    aliases: ["network", "executive network", "connections", "mentors", "mentorship", "community", "events"],
    path: "/network",
    category: "Network",
    icon: Users,
    description: "Connect with executives, find mentors, join communities, attend events, and explore career opportunities and partnerships.",
    purpose: "Build the relationships that accelerate executive growth and opportunity.",
    keyFeatures: ["Executive directory", "Discussions & circles", "Mentorship", "Events", "Careers & partnerships"],
    findIt: "Sidebar → Network → Executive Network.",
  },
  {
    id: "wallet",
    name: "Executive Wallet",
    aliases: ["wallet", "executive wallet", "earnings", "commissions", "rewards", "withdrawal"],
    path: "/wallet",
    category: "Account",
    icon: Wallet,
    description: "Earn rewards through referrals and community contributions, track balances, and request withdrawals.",
    purpose: "Monetize your network and contributions to the EXECLEAD.AI community.",
    keyFeatures: ["Balance breakdown", "Transaction history", "Withdrawals", "Founder bonuses", "Ambassador progress"],
    findIt: "Sidebar → Account → Executive Wallet.",
  },
  {
    id: "identity-verification",
    name: "Identity Verification",
    aliases: ["identity verification", "verify identity", "verification", "verified", "trust", "kyc"],
    path: "/identity-verification",
    category: "Account",
    icon: BadgeCheck,
    description: "Verify your identity to build trust, unlock additional platform features, and earn a verification badge.",
    purpose: "Establish authentic executive credibility on the platform.",
    keyFeatures: ["Document upload", "Trust score", "Verification history", "Verified badge"],
    findIt: "Sidebar → Account → Identity Verification.",
  },
  {
    id: "billing",
    name: "Billing",
    aliases: ["billing", "subscription", "payment", "plan", "upgrade", "invoice"],
    path: "/billing",
    category: "Account",
    icon: CreditCard,
    description: "Manage your subscription, view payment history, upgrade plans, and access founding member pricing.",
    purpose: "Control your membership and billing in one place.",
    keyFeatures: ["Current plan", "Payment history", "Plan comparison", "Coupon input", "Founding member benefits"],
    findIt: "Sidebar → Account → Billing.",
  },
  {
    id: "organizations",
    name: "Organizations",
    aliases: ["organizations", "organization", "org admin", "company admin", "manage organization"],
    path: "/developer/organizations",
    category: "Administration",
    icon: Building2,
    description: "Platform administration for managing organizations, memberships, and enterprise accounts.",
    purpose: "Administer enterprise organizations and their configurations.",
    keyFeatures: ["Organization directory", "Membership management", "Audit logs"],
    findIt: "Platform/Developer workspace → Organizations (admin only).",
  },
  {
    id: "enterprise",
    name: "Enterprise Features",
    aliases: ["enterprise", "team", "organization dashboard", "hr", "succession", "sso", "team dashboard"],
    path: "/enterprise",
    category: "Enterprise",
    icon: Building2,
    description: "Team dashboards, succession planning, HR tools, leadership analytics, SSO, and learning assignments for organizations.",
    purpose: "Develop leadership capabilities across your entire organization.",
    keyFeatures: ["Team dashboard", "Succession planning", "HR dashboard", "Promotion readiness", "Learning assignments", "SSO"],
    findIt: "Switch to the Enterprise workspace → Enterprise Dashboard.",
  },
  {
    id: "developer",
    name: "Developer Workspace",
    aliases: ["developer", "developer workspace", "engineering", "feature flags", "api keys", "database", "deployments", "guardian"],
    path: "/developer",
    category: "Developer",
    icon: Code2,
    description: "Engineering workspace for feature flags, API keys, database tools, deployments, system health, and the Guardian™ consistency engine.",
    purpose: "Operate and maintain the platform infrastructure (admin/developer only).",
    keyFeatures: ["Feature flags", "API management", "Database explorer", "Deployment center", "System health", "Guardian™"],
    findIt: "Switch to the Developer workspace (admin/developer only).",
  },
  {
    id: "coach",
    name: "Executive Coach",
    aliases: ["coach", "coaching", "executive coach", "ai coach", "mentoring session"],
    path: "/coach",
    category: "Platform",
    icon: MessageSquare,
    description: "One-on-one AI coaching sessions tailored to your goals, competencies, and career stage — from aspiring leader to seasoned executive.",
    purpose: "Get personalized, on-demand executive guidance.",
    keyFeatures: ["AI coaching sessions", "Goal-aligned guidance", "Session history"],
    findIt: "Sidebar → Platform → Executive Coach.",
  },
  {
    id: "simulator",
    name: "Executive Simulator",
    aliases: ["simulator", "simulation", "executive simulator", "practice", "scenario"],
    path: "/simulator",
    category: "Platform",
    icon: Brain,
    description: "Practice high-stakes executive decisions through AI-driven realistic scenarios with performance scoring.",
    purpose: "Build decision-making confidence in a safe, repeatable environment.",
    keyFeatures: ["Realistic scenarios", "Performance scoring", "Debrief & feedback", "Session history"],
    findIt: "Sidebar → Platform → Executive Simulator.",
  },
  {
    id: "council",
    name: "Executive Council",
    aliases: ["council", "executive council", "debate", "decision", "advisory"],
    path: "/council",
    category: "Platform",
    icon: Network,
    description: "An AI advisory council that debates your strategic decisions from multiple executive perspectives.",
    purpose: "Pressure-test decisions before you make them.",
    keyFeatures: ["Multi-persona debate", "Risk matrix", "Decision brief", "Voting summary"],
    findIt: "Sidebar → Platform → Executive Council.",
  },
  {
    id: "companies",
    name: "Companies Intelligence",
    aliases: ["companies", "company", "company intelligence", "company library", "interview prep", "target company"],
    path: "/companies",
    category: "Career",
    icon: Building2,
    description: "Deep insights into companies — leadership culture, interview preparation, and career targeting intelligence.",
    purpose: "Research target companies and prepare for executive interviews.",
    keyFeatures: ["Company profiles", "Leadership culture insights", "Interview prep", "Compare companies", "Natural-language search"],
    findIt: "Sidebar → Career → Companies (also public at /company-library).",
  },
  {
    id: "analytics",
    name: "Analytics",
    aliases: ["analytics", "metrics", "leadership analytics", "growth", "progress analytics"],
    path: "/analytics",
    category: "Insights",
    icon: BarChart3,
    description: "Track your leadership growth, skill development, and progress over time with rich visualizations.",
    purpose: "Measure your development and spot trends in your leadership capabilities.",
    keyFeatures: ["Growth trends", "Skill development charts", "Progress benchmarks"],
    findIt: "Sidebar → Insights → Analytics.",
  },
  {
    id: "security",
    name: "Security Center",
    aliases: ["security", "security center", "devices", "sessions", "access control", "compliance"],
    path: "/security",
    category: "Account",
    icon: Shield,
    description: "Manage devices, sessions, access control, compliance, and review your account security posture.",
    purpose: "Keep your executive account secure and compliant.",
    keyFeatures: ["Device management", "Session manager", "Access control", "Compliance center", "Security audit log"],
    findIt: "Sidebar → Account → Security Center.",
  },
  {
    id: "founder",
    name: "Founder Portal",
    aliases: ["founder", "founder portal", "founding member", "founders", "founding"],
    path: "/founder",
    category: "Account",
    icon: Crown,
    description: "Exclusive portal for Founding Members — benefits, community, events, roadmap, referrals, rewards, certificates, and time capsule.",
    purpose: "Enjoy your founding membership privileges and shape the platform's future.",
    keyFeatures: ["Founder benefits", "Founder community", "Events", "Roadmap", "Rewards", "Certificates", "Time capsule"],
    findIt: "Sidebar → Account → Founder Portal (founding members only).",
  },
  {
    id: "referrals",
    name: "Executive Ambassador Program™",
    aliases: ["referrals", "referral", "refer", "invite", "ambassador", "ambassador program", "leadership impact", "community growth", "executive ambassador"],
    path: "/referrals",
    category: "Account",
    icon: Gift,
    description: "A leadership recognition program — not an affiliate program. Introduce future leaders to EXECLEAD.AI and earn platform value (Journey Points, EXEC™ Credits, Reputation, Badges) instead of cash commissions.",
    purpose: "Grow the executive community while being recognized for your leadership influence.",
    keyFeatures: ["Ambassador referral link", "QR code & share card", "Plan-based rewards (non-cash)", "7 Ambassador Levels (Explorer → Legacy Builder)", "Executive Impact Score", "Ambassador milestones", "Founder 1.5× multiplier", "Anti-fraud protection", "Executive Journey™ & Reputation™ integration"],
    findIt: "Sidebar → Account → Referrals.",
  },
  {
    id: "settings",
    name: "Settings",
    aliases: ["settings", "preferences", "appearance", "account settings", "configuration"],
    path: "/settings",
    category: "Account",
    icon: SettingsIcon,
    description: "Configure your profile, privacy, appearance, notifications, and account preferences.",
    purpose: "Personalize your EXECLEAD.AI experience.",
    keyFeatures: ["Profile editing", "Privacy controls", "Appearance & theme", "Notifications"],
    findIt: "Sidebar → Account → Settings.",
  },
  {
    id: "profile",
    name: "Profile",
    aliases: ["profile", "my profile", "executive profile", "public profile"],
    path: "/profile",
    category: "Account",
    icon: UserCircle,
    description: "Your executive profile — personal info, experience, education, skills, target career, and public visibility.",
    purpose: "Maintain the professional profile that powers your AI experience and public presence.",
    keyFeatures: ["Experience & education", "Skills", "Target career", "Public profile", "Resume sync"],
    findIt: "Sidebar → Account → Profile.",
  },
  {
    id: "ai-command-center",
    name: "AI Command Center",
    aliases: ["ai command center", "command center", "ai usage", "ai operations", "tokens"],
    path: "/ai-command-center",
    category: "Platform",
    icon: Cpu,
    description: "Monitor your AI usage, model activity, token consumption, and operational insights across the platform.",
    purpose: "Understand and optimize how you use EXECLEAD.AI's AI capabilities.",
    keyFeatures: ["Usage analytics", "Model analytics", "Token tracking", "Health score"],
    findIt: "Sidebar → Platform → AI Command Center.",
  },
  {
    id: "journal",
    name: "Executive Journal",
    aliases: ["journal", "executive journal", "reflections", "leadership journal", "notes"],
    path: "/journal",
    category: "Career",
    icon: PenLine,
    description: "A private leadership journal for reflections, decisions, and growth notes over time.",
    purpose: "Reflect on your leadership journey and track your thinking as it evolves.",
    keyFeatures: ["Journal entries", "Reflection prompts", "Search & filter"],
    findIt: "Sidebar → Career → Journal.",
  },
  {
    id: "executive-legacy",
    name: "Executive Legacy™",
    aliases: ["legacy", "executive legacy", "leadership legacy", "legacy building", "case studies", "legacy letters"],
    path: "/executive-legacy",
    category: "Insights",
    icon: Crown,
    description: "Your long-term executive impact — legacy building, case studies, and the enduring leadership narrative you leave behind.",
    purpose: "Shape and document the legacy you are building as an executive leader.",
    keyFeatures: ["Legacy case studies", "Leadership narrative", "Executive impact timeline", "Legacy letters"],
    findIt: "Sidebar → Insights → Executive Legacy.",
  },
  {
    id: "elim",
    name: "ELIM™ Management Center",
    aliases: ["elim", "elim management", "leadership intelligence model", "knowledge packs", "frameworks admin"],
    path: "/elim",
    category: "Platform",
    icon: Brain,
    description: "Administrative center for the EXECLEAD Leadership Intelligence Model™ — manage frameworks, knowledge packs, evidence rules, and research analytics.",
    purpose: "Configure and maintain the intelligence architecture powering every AI assessment and recommendation.",
    keyFeatures: ["Framework management", "Knowledge packs", "Evidence rules", "Scoring rules", "Research analytics"],
    findIt: "Sidebar → Platform → ELIM Management (admin only).",
  },
  {
    id: "methodology",
    name: "EELM™ Methodology",
    aliases: ["methodology", "eelm", "executive leadership methodology", "principles", "evidence model", "decision model", "maturity model", "governance", "research foundation", "transparency"],
    path: "/methodology",
    category: "Insights",
    icon: Brain,
    description: "The EXECLEAD Executive Leadership Methodology™ (EELM™) — the formal methodology governing how EXECLEAD.AI evaluates, develops, validates, measures, predicts, and continuously improves executive leadership capability. Defines the five principles (Assess, Develop, Validate, Measure, Evolve), the Executive Intelligence Loop, five core frameworks, the evidence model, the AI decision model, and the eight-stage leadership maturity model.",
    purpose: "Understand the scientific methodology behind every AI recommendation, assessment, and executive insight on the platform.",
    keyFeatures: ["Five Principles", "Executive Intelligence Loop", "Five Core Frameworks", "Evidence Model (20 sources)", "AI Decision Model", "8-Stage Maturity Model", "Methodology Governance", "Research Foundation", "Transparency Principles"],
    findIt: "Sidebar → Insights → EELM™ Methodology.",
  },
  {
    id: "self-healing",
    name: "Platform Self-Healing Engine™",
    aliases: ["self-healing", "auto repair", "self healing", "analyze platform", "repair platform", "platform manifest health", "manifest health", "repair manifest", "platform repair", "auto-repair", "self-healing engine", "platform self-healing"],
    path: "/developer/diagnostics",
    category: "Developer",
    icon: Wrench,
    description: "Automatically analyzes, validates, and safely repairs deterministic Platform Manifest™ issues while escalating architectural decisions for developer review. Transforms the Platform Governance Center™ from a passive monitoring dashboard into an intelligent operational system.",
    purpose: "Make the platform increasingly self-maintaining without hiding important governance decisions. Analyze, auto-repair safe issues, validate, and escalate remaining issues for developer review.",
    keyFeatures: ["Analyze Platform", "Auto-Repair Safe Issues", "Review Critical Issues", "Platform Manifest Health Score", "Self-Healing History", "Export Validation Report"],
    findIt: "Developer Workspace → Platform Governance Center™ → Self-Healing Engine™.",
  },
  {
    id: "intelligence_scores",
    name: "Intelligence Scores",
    aliases: ["intelligence scores", "elim scores", "intelligence score", "executive intelligence", "overall intelligence", "competency score", "why is my intelligence score low", "how is intelligence score calculated", "explain intelligence scores"],
    path: "/elim",
    category: "Platform",
    icon: Brain,
    description: "The Intelligence Scores workspace within the ELIM™ Management Center provides a comprehensive executive intelligence overview — Overall ELIM™ Intelligence Score, Competency Score, Leadership DNA™, Executive Readiness™, Executive Reputation™, Executive Journey™, Executive Trust™, radar chart, trend analysis, growth velocity, confidence score, score distribution, evidence sources, AI interpretation, and recommendations.",
    purpose: "Give executives a single pane of glass for their complete ELIM™ Intelligence profile, with AI-driven interpretation and actionable growth recommendations.",
    keyFeatures: ["Overall ELIM™ Intelligence Score", "Competency Radar", "Score Distribution", "Growth Velocity", "AI Interpretation", "Recommendations", "Evidence Sources", "Confidence Score"],
    findIt: "ELIM™ Management Center → Intelligence Scores tab.",
  },
  {
    id: "mission_control",
    name: "Mission Control",
    aliases: ["mission control", "platform health", "show platform health", "open mission control", "run self-healing", "review platform risks", "today's platform summary", "platform status", "platform governance", "platform command center", "platform operational status"],
    path: "/developer/diagnostics",
    category: "Developer",
    icon: Gauge,
    description: "The operational command center of EXECLEAD.AI — provides complete visibility into platform health, core platform services, Platform Manifest™, knowledge synchronization, self-healing, Guardian™, deployments, AI governance, and operational metrics. Features an AI-generated EXEC™ Mission Brief, a Platform Health Score computed from 8 signals, a live service status grid, a system timeline, and quick operational actions.",
    purpose: "Enable a founder, platform engineer, or administrator to understand the health of the entire platform within 30 seconds of opening Mission Control.",
    keyFeatures: ["EXEC™ Mission Brief", "Platform Health Score", "Live Platform Status Grid", "System Timeline", "Quick Actions", "Platform Metrics", "Service Drill-Down", "Self-Healing Integration"],
    findIt: "Developer Workspace → Platform Governance Center™ → Mission Control.",
  },
  {
    id: "platform_state_manager",
    name: "Platform State Manager™",
    aliases: ["platform state", "state manager", "platform state manager", "runtime state", "platform health", "readiness index", "platform readiness", "platform state version", "platform event bus", "live platform events"],
    path: "/developer/diagnostics",
    category: "Developer",
    icon: Gauge,
    description: "The single runtime source of truth for the entire platform. Maintains one authoritative runtime state — Platform Health, Platform Readiness Index™, Manifest Coverage, Knowledge Coverage, Guardian Health, Deployment Status, and all platform versions. Every dashboard, widget, and module consumes this service instead of computing health independently.",
    purpose: "Ensure every platform component displays identical runtime values after any platform operation (Analyze, Repair, Commit, Knowledge Sync, Deployment, Guardian Scan). No stale widgets, no conflicting values, no manual refresh.",
    keyFeatures: ["Platform Health Score", "Platform Readiness Index™", "Manifest & Knowledge Coverage", "Guardian & Deployment Status", "Platform Event Bus™", "Live Synchronization", "Cache Invalidation", "Platform State Events", "Developer Debug Panel"],
    findIt: "Developer Workspace → Platform Governance Center™ → Platform State Debug Panel.",
  },
  {
    id: "challenge",
    name: "Executive Challenge",
    aliases: ["challenge", "daily challenge", "executive challenge", "daily task", "quick challenge"],
    path: "/challenge",
    category: "Platform",
    icon: Zap,
    description: "Daily executive challenges that build leadership skills through short, focused exercises with AI scoring and streak tracking.",
    purpose: "Develop executive capabilities through consistent daily practice in a gamified format.",
    keyFeatures: ["Daily challenges", "AI scoring", "Streak tracking", "Journey Points", "Competency-linked exercises"],
    findIt: "Sidebar → Platform → Executive Challenge.",
  },
  {
    id: "debate",
    name: "Executive Debate",
    aliases: ["debate", "executive debate", "argument", "perspective debate", "multi-perspective"],
    path: "/debate",
    category: "Platform",
    icon: MessageSquare,
    description: "AI-driven debate platform where multiple executive perspectives argue different sides of a strategic question, helping you see all angles before deciding.",
    purpose: "Pressure-test your thinking by exploring opposing executive viewpoints on any strategic question.",
    keyFeatures: ["Multi-persona debate", "Opposing arguments", "Summary & synthesis", "Decision support"],
    findIt: "Sidebar → Platform → Executive Debate.",
  },
  {
    id: "career",
    name: "Career Advisor",
    aliases: ["career", "career advisor", "career path", "job search", "career guidance", "career coaching"],
    path: "/career",
    category: "Career",
    icon: Briefcase,
    description: "AI-powered career advisor that analyzes your profile, target role, and industry to recommend the optimal career path, skill gaps, and next steps.",
    purpose: "Get personalized, AI-driven career guidance aligned with your executive goals.",
    keyFeatures: ["AI career analysis", "Skill gap identification", "Career path recommendations", "Target role alignment"],
    findIt: "Sidebar → Career → Career Advisor.",
  },
  {
    id: "intelligence_competencies",
    name: "Competency Intelligence",
    aliases: ["competency intelligence", "competencies", "competency detail", "verified competencies", "emerging competencies", "developing competencies", "competency gaps"],
    path: "/intelligence/competencies",
    category: "Insights",
    icon: Brain,
    description: "Deep-dive into individual executive competencies — verified, emerging, developing, and gaps — with evidence sources, scores, and AI growth recommendations.",
    purpose: "Understand each competency in detail and identify exactly what to develop next.",
    keyFeatures: ["Competency detail view", "Evidence sources", "Growth recommendations", "Score breakdowns", "Maturity levels"],
    findIt: "Sidebar → Insights → Intelligence Center → Competencies tab.",
  },
  {
    id: "ai_usage",
    name: "AI Usage Dashboard",
    aliases: ["ai usage", "usage", "tokens", "ai operations", "ai analytics", "model usage", "cost analytics"],
    path: "/ai-usage",
    category: "Platform",
    icon: Cpu,
    description: "Comprehensive AI operations dashboard showing token consumption, model analytics, cost tracking, usage forecasts, and provider health across the platform.",
    purpose: "Monitor and optimize how AI resources are consumed across your account or organization.",
    keyFeatures: ["Token analytics", "Model analytics", "Cost tracking", "Usage forecasts", "Provider health", "Budget panel"],
    findIt: "Sidebar → Platform → AI Command Center, or Enterprise → Reports → Usage Analytics.",
  },
  {
    id: "brand_center",
    name: "Executive Brand Center",
    aliases: ["brand center", "brand", "executive brand", "personal brand", "digital business card", "executive timeline", "profile health"],
    path: "/brand-center",
    category: "Account",
    icon: Star,
    description: "Your executive brand hub — digital business card, executive timeline, achievement gallery, reputation index, profile health dashboard, and AI executive advisor.",
    purpose: "Build and showcase your executive brand with shareable, professional assets.",
    keyFeatures: ["Digital business card", "Executive timeline", "Achievement gallery", "Reputation index", "Profile health", "AI advisor", "Public profile"],
    findIt: "Sidebar → Account → Brand Center.",
  },
  {
    id: "admin_console",
    name: "Admin Console",
    aliases: ["admin", "admin console", "user support", "user management admin", "support console"],
    path: "/admin",
    category: "Administration",
    icon: Shield,
    description: "Platform administration console for user support, feature management, deployment gating, consistency reporting, and guardian activity monitoring.",
    purpose: "Administer platform users, features, and system consistency from one place.",
    keyFeatures: ["User support", "Feature management", "Deployment gating", "Consistency reports", "Guardian activity", "Health dashboard"],
    findIt: "Sidebar → System → User Support (Platform workspace).",
  },
  {
    id: "cpq",
    name: "CPQ Wizard",
    aliases: ["cpq", "cpq wizard", "quote", "configure price quote", "sales quote", "proposal builder"],
    path: "/cpq",
    category: "Administration",
    icon: Calculator,
    description: "Configure-Price-Quote wizard for building enterprise sales proposals with module selection, seat tiers, AI packages, discount rules, and contract generation.",
    purpose: "Generate professional enterprise proposals with accurate pricing in minutes.",
    keyFeatures: ["Module selector", "Seat tiers", "AI packages", "Discount rules", "Contract generation", "Quote management"],
    findIt: "Sidebar → Revenue → CPQ (Platform/Developer workspace).",
  },
  {
    id: "cpq_dashboard",
    name: "Sales Pipeline",
    aliases: ["cpq dashboard", "sales pipeline", "quotes dashboard", "pipeline", "sales pipeline dashboard"],
    path: "/cpq-dashboard",
    category: "Administration",
    icon: TrendingUp,
    description: "Sales pipeline dashboard tracking all CPQ quotes through their lifecycle — draft, sent, viewed, accepted, activated — with revenue forecasting.",
    purpose: "Track enterprise sales pipeline and forecast revenue from quotes.",
    keyFeatures: ["Quote pipeline", "Revenue forecast", "Status tracking", "Conversion analytics"],
    findIt: "Sidebar → Revenue → Sales Pipeline (Platform/Developer workspace).",
  },
  {
    id: "company_admin",
    name: "Company Administration",
    aliases: ["company admin", "company management", "company database", "logo management", "industries", "countries"],
    path: "/company-admin",
    category: "Administration",
    icon: Building2,
    description: "Administrative center for managing the company database — logos, industries, countries, company reports, and data quality.",
    purpose: "Maintain accurate, high-quality company intelligence data.",
    keyFeatures: ["Company management", "Logo reliability", "Industry management", "Country management", "Company reports", "Import/export"],
    findIt: "Sidebar → Management → Companies (Platform/Developer workspace).",
  },
  {
    id: "pricing_admin",
    name: "Subscription Management",
    aliases: ["pricing admin", "subscription management", "pricing engine", "plan management", "pricing management"],
    path: "/pricing-admin",
    category: "Administration",
    icon: DollarSign,
    description: "Manage subscription plans, pricing tiers, feature entitlements, and coupon rules from a single pricing engine.",
    purpose: "Configure and maintain the platform's subscription and pricing model.",
    keyFeatures: ["Plan management", "Pricing tiers", "Feature entitlements", "Coupon rules", "Launch mode control"],
    findIt: "Sidebar → Management → Subscription Management (Platform/Developer workspace).",
  },
  {
    id: "feature_management",
    name: "Feature Flag Management",
    aliases: ["feature management", "feature flags", "feature toggle", "rollout control", "feature gates"],
    path: "/feature-management",
    category: "Developer",
    icon: Boxes,
    description: "Control feature rollouts, beta access, and feature gates across the platform with granular plan-tier and environment targeting.",
    purpose: "Manage which features are available to which users at what stage of rollout.",
    keyFeatures: ["Feature flags", "Rollout percentages", "Plan-tier gating", "Beta access", "Environment targeting"],
    findIt: "Sidebar → Workspace → Feature Flags (Developer workspace).",
  },
  {
    id: "billing_admin",
    name: "Revenue Dashboard",
    aliases: ["billing admin", "revenue dashboard", "revenue", "billing management", "finance admin"],
    path: "/billing-admin",
    category: "Administration",
    icon: Receipt,
    description: "Revenue dashboard for monitoring platform-wide billing, subscriptions, invoices, payment provider health, and revenue trends.",
    purpose: "Track platform revenue and billing operations.",
    keyFeatures: ["Revenue tracking", "Subscription monitoring", "Invoice management", "Payment provider health", "Revenue trends"],
    findIt: "Sidebar → Revenue → Revenue Dashboard (Platform/Developer workspace).",
  },
  {
    id: "payment_settings",
    name: "Payment Providers",
    aliases: ["payment settings", "payment providers", "stripe", "payment gateway", "payment configuration"],
    path: "/payment-settings",
    category: "Administration",
    icon: Lock,
    description: "Configure payment provider connections (Stripe), API keys, webhook secrets, supported currencies, tax settings, and trial configuration.",
    purpose: "Set up and maintain the platform's payment infrastructure.",
    keyFeatures: ["Provider connection", "API key management", "Webhook configuration", "Currency support", "Tax settings", "Trial configuration"],
    findIt: "Sidebar → Administration → Payment Providers (Platform/Developer workspace).",
  },
  {
    id: "email_settings",
    name: "Email Center",
    aliases: ["email settings", "email center", "email templates", "email provider", "email configuration", "smtp"],
    path: "/email-settings",
    category: "Administration",
    icon: Mail,
    description: "Configure email providers, templates, test connections, and monitor email queue health and delivery logs.",
    purpose: "Manage the platform's email infrastructure and templates.",
    keyFeatures: ["Provider configuration", "Email templates", "Test connection", "Queue statistics", "Delivery logs", "Diagnostics"],
    findIt: "Sidebar → System → Email Center (Platform/Developer workspace).",
  },
  {
    id: "organization_users",
    name: "Organization Users",
    aliases: ["organization users", "org users", "team members", "manage users", "member management"],
    path: "/organization/users",
    category: "Enterprise",
    icon: Users,
    description: "Manage organization members, roles, departments, and team structure within your enterprise workspace.",
    purpose: "Administer your organization's users and their access.",
    keyFeatures: ["Member management", "Role assignment", "Department structure", "Invite users", "Edit user roles"],
    findIt: "Enterprise Workspace → Organization → Users.",
  },
  {
    id: "sso",
    name: "SSO Identity",
    aliases: ["sso", "single sign-on", "saml", "identity provider", "enterprise login", "federated login"],
    path: "/sso",
    category: "Enterprise",
    icon: KeyRound,
    description: "Configure Single Sign-On (SSO) with SAML-based identity providers for enterprise authentication.",
    purpose: "Enable enterprise users to authenticate through their organization's identity provider.",
    keyFeatures: ["SAML configuration", "Identity provider setup", "Enterprise login", "Federated authentication"],
    findIt: "Enterprise Workspace → Administration → SSO.",
  },
  {
    id: "hr_dashboard",
    name: "HR Dashboard",
    aliases: ["hr dashboard", "hr", "human resources", "departments", "team analytics"],
    path: "/hr-dashboard",
    category: "Enterprise",
    icon: Users,
    description: "HR dashboard for viewing department-level leadership intelligence, team readiness, and development tracking.",
    purpose: "Give HR leaders visibility into department-level leadership capability.",
    keyFeatures: ["Department analytics", "Team readiness", "Development tracking", "Leadership distribution"],
    findIt: "Enterprise Workspace → Organization → Departments.",
  },
  {
    id: "succession_planning",
    name: "Succession Planning",
    aliases: ["succession planning", "succession", "succession plan", "talent pipeline", "replacement planning"],
    path: "/succession-planning",
    category: "Enterprise",
    icon: Users,
    description: "Plan leadership succession with readiness assessments, talent pipelines, and replacement scenarios for key roles.",
    purpose: "Ensure continuity by identifying and developing future leaders for critical positions.",
    keyFeatures: ["Succession plans", "Readiness assessment", "Talent pipeline", "Replacement scenarios", "Role criticality"],
    findIt: "Enterprise Workspace → Organization → Teams.",
  },
  {
    id: "promotion_readiness",
    name: "Promotion Readiness",
    aliases: ["promotion readiness", "promotion", "promotion forecast", "promotion assessment", "promotion probability"],
    path: "/promotion-readiness",
    category: "Enterprise",
    icon: TrendingUp,
    description: "Assess and forecast promotion readiness across the organization with AI-driven probability scores and timelines.",
    purpose: "Identify who is ready for promotion and when, backed by AI forecasting.",
    keyFeatures: ["Promotion assessment", "AI probability forecast", "Timeline estimation", "Readiness gaps", "Confidence scoring"],
    findIt: "Enterprise Workspace → Organization → Promotion Readiness.",
  },
  {
    id: "learning_assignments",
    name: "Learning Assignments",
    aliases: ["learning assignments", "assignments", "assigned learning", "training assignments", "learning paths"],
    path: "/learning-assignments",
    category: "Enterprise",
    icon: ClipboardCheck,
    description: "Assign learning paths, courses, and development modules to team members and track their progress.",
    purpose: "Drive targeted leadership development across your organization through assigned learning.",
    keyFeatures: ["Assignment creation", "Learning path assignment", "Progress tracking", "Completion analytics", "Individual and team views"],
    findIt: "Enterprise Workspace → Organization → Learning Assignments.",
  },
  {
    id: "connected_accounts",
    name: "Connected Accounts",
    aliases: ["connected accounts", "integrations", "oauth", "connect google", "connect calendar", "third party"],
    path: "/connected-accounts",
    category: "Account",
    icon: Network,
    description: "Manage third-party account connections — Google, Microsoft, Slack, and more — for calendar sync, email, and data integration.",
    purpose: "Connect external accounts to enhance your executive intelligence with real-world data.",
    keyFeatures: ["OAuth connections", "Google integration", "Microsoft integration", "Calendar sync", "Connection management"],
    findIt: "Sidebar → Account → Connected Accounts.",
  },
  {
    id: "metrics",
    name: "Executive Metrics",
    aliases: ["metrics", "executive metrics", "kpis", "key metrics", "performance metrics"],
    path: "/metrics",
    category: "Insights",
    icon: BarChart3,
    description: "A focused metrics view showing your key executive performance indicators at a glance.",
    purpose: "Track the KPIs that matter most to your executive development.",
    keyFeatures: ["Key metrics", "Performance indicators", "Trend tracking", "Goal progress"],
    findIt: "Sidebar → Insights → Metrics.",
  },
  {
    id: "exec_admin",
    name: "EXEC™ Console",
    aliases: ["exec admin", "exec console", "exec management", "ai agent management", "exec configuration"],
    path: "/exec-admin",
    category: "Developer",
    icon: Sparkles,
    description: "Administrative console for EXEC™ — configure AI personas, knowledge sources, conversation styles, and agent capabilities.",
    purpose: "Manage and tune the EXEC™ AI assistant's behavior, knowledge, and capabilities.",
    keyFeatures: ["Persona management", "Knowledge source configuration", "Conversation style", "Agent capabilities", "Testing tools"],
    findIt: "Sidebar → Workspace → EXEC™ Console (Developer workspace).",
  },
  {
    id: "executive_platform_status",
    name: "Executive Platform Status™",
    aliases: ["executive platform status", "platform status", "founder mission control", "platform overview", "founder dashboard"],
    path: "/developer/executive-platform-status",
    category: "Developer",
    icon: Gauge,
    description: "Founder Mission Control — a unified executive overview of the entire platform status, aggregating engineering, product, AI, and launch readiness.",
    purpose: "Give the founder or platform lead a single pane of glass for the complete platform health.",
    keyFeatures: ["Platform health scores", "Engineering health", "AI intelligence status", "Launch readiness", "Daily briefing"],
    findIt: "Developer Workspace → Executive Platform Status.",
  },
  {
    id: "experience_audit",
    name: "Platform Autonomic Experience Engine™",
    aliases: ["experience audit", "platform experience audit", "autonomic experience", "ux audit", "platform ux"],
    path: "/developer/experience-audit",
    category: "Developer",
    icon: Wrench,
    description: "Automated platform UX audit engine that discovers, scores, and patches experience issues across the platform.",
    purpose: "Continuously improve the platform's user experience through automated analysis and repair.",
    keyFeatures: ["Automated audit", "Experience scoring", "Repair patches", "Engineering metrics", "Historical trends"],
    findIt: "Developer Workspace → Platform Experience Audit.",
  },
  {
    id: "knowledge_sync",
    name: "EXEC™ Knowledge Synchronization™",
    aliases: ["knowledge sync", "knowledge synchronization", "exec knowledge sync", "sync knowledge", "knowledge pipeline"],
    path: "/developer/knowledge-sync",
    category: "Developer",
    icon: Brain,
    description: "The platform's automatic learning pipeline — discovers, validates, registers, and synchronizes all platform assets into EXEC™'s knowledge base.",
    purpose: "Keep EXEC™ AI aware of every platform change automatically.",
    keyFeatures: ["Asset discovery", "Knowledge registration", "Validation findings", "Sync history", "Self-awareness"],
    findIt: "Developer Workspace → Knowledge Sync.",
  },
  {
    id: "developer_ai_command_center",
    name: "Developer AI Command Center",
    aliases: ["developer ai command center", "developer ai", "ai ops developer", "platform ai operations"],
    path: "/developer/ai-command-center",
    category: "Developer",
    icon: Cpu,
    description: "Developer-focused AI operations dashboard for monitoring platform-wide AI usage, token consumption, and model performance.",
    purpose: "Monitor and optimize AI resource usage from the developer perspective.",
    keyFeatures: ["Platform-wide AI usage", "Token analytics", "Model performance", "Cost tracking"],
    findIt: "Developer Workspace → AI Command Center.",
  },
  {
    id: "audit_logs",
    name: "Audit Logs",
    aliases: ["audit logs", "audit log", "activity log", "system audit", "event log"],
    path: "/developer/audit-logs",
    category: "Developer",
    icon: ClipboardCheck,
    description: "Comprehensive audit trail of all platform events, user actions, and system changes for compliance and debugging.",
    purpose: "Review and investigate platform activity for compliance, debugging, and governance.",
    keyFeatures: ["Event timeline", "User action tracking", "System change log", "Filtering & search"],
    findIt: "Developer Workspace → Audit Logs.",
  },
  {
    id: "system_health",
    name: "System Health",
    aliases: ["system health", "service health", "platform health monitoring", "uptime", "service status"],
    path: "/developer/system-health",
    category: "Developer",
    icon: Gauge,
    description: "Real-time monitoring of all platform services, API health, database performance, and system uptime.",
    purpose: "Monitor the health and performance of all platform infrastructure components.",
    keyFeatures: ["Service status", "API health", "Database performance", "Uptime monitoring"],
    findIt: "Developer Workspace → System Health.",
  },
  {
    id: "api_keys",
    name: "API Keys",
    aliases: ["api keys", "api key", "api management", "developer keys", "access tokens"],
    path: "/developer/api-keys",
    category: "Developer",
    icon: KeyRound,
    description: "Manage platform API keys for developer integrations, webhook secrets, and service-to-service authentication.",
    purpose: "Create and manage API credentials for platform integrations.",
    keyFeatures: ["Key generation", "Key rotation", "Scope management", "Usage tracking"],
    findIt: "Developer Workspace → API Keys.",
  },
  {
    id: "database_tools",
    name: "Database Tools",
    aliases: ["database", "database tools", "db explorer", "data explorer", "database admin"],
    path: "/developer/database",
    category: "Developer",
    icon: Boxes,
    description: "Database exploration and management tools for querying, inspecting, and maintaining platform data.",
    purpose: "Inspect and manage platform database records for debugging and administration.",
    keyFeatures: ["Data explorer", "Query tools", "Record inspection", "Data export"],
    findIt: "Developer Workspace → Database Tools.",
  },
  {
    id: "migration_history",
    name: "Migration History",
    aliases: ["migration history", "migrations", "schema migrations", "database migrations", "data migrations"],
    path: "/developer/migrations",
    category: "Developer",
    icon: ClipboardCheck,
    description: "Track and manage platform data migrations, schema changes, and migration execution history.",
    purpose: "Monitor and control platform data migration operations.",
    keyFeatures: ["Migration timeline", "Schema changes", "Execution history", "Rollback support"],
    findIt: "Developer Workspace → Migration History.",
  },
  {
    id: "deployment_center",
    name: "Deployment Center",
    aliases: ["deployment center", "deployments", "deploy", "deployment pipeline", "publish platform"],
    path: "/developer/deployments",
    category: "Developer",
    icon: Gauge,
    description: "Interactive engineering operations console — run the 7-stage Deployment Pipeline™, inspect every stage with drill-down diagnostics, and generate Platform Validation Reports.",
    purpose: "Deploy and validate the platform with full governance and reporting.",
    keyFeatures: ["7-stage pipeline", "Stage diagnostics", "EXEC™ Copilot", "Platform Validation Report", "Enterprise Report Engine"],
    findIt: "Developer Workspace → Deployment Center.",
  },
  {
    id: "diagnostics",
    name: "Platform Governance Center™",
    aliases: ["diagnostics", "governance", "platform governance", "governance center", "platform diagnostics", "governance pipeline"],
    path: "/developer/diagnostics",
    category: "Developer",
    icon: Wrench,
    description: "The Platform Governance Center™ — runs the 16-stage Governance Pipeline™, certifies platform health, provides self-healing, Mission Control, and Platform State debugging.",
    purpose: "Govern, validate, and certify the platform with automated pipeline execution and AI-assisted remediation.",
    keyFeatures: ["16-stage Governance Pipeline™", "Self-Healing Engine™", "Mission Control", "Platform State Manager™", "Governance Certification"],
    findIt: "Developer Workspace → Platform Governance.",
  },
  {
    id: "academy_course",
    name: "Course Home",
    aliases: ["course", "course home", "academy course", "learning course", "course detail"],
    path: "/academy/:courseSlug",
    category: "Platform",
    icon: GraduationCap,
    description: "Individual course view within the Executive Academy — lessons, progress tracking, AI coach, and certificate upon completion.",
    purpose: "Work through a structured learning course to build executive capabilities.",
    keyFeatures: ["Course syllabus", "Lesson progression", "AI coach", "Quiz & assessment", "Certificate"],
    findIt: "Academy → select any course.",
  },
  {
    id: "academy_lesson",
    name: "Lesson",
    aliases: ["lesson", "academy lesson", "course lesson", "learning lesson"],
    path: "/academy/:courseSlug/:lessonId",
    category: "Platform",
    icon: GraduationCap,
    description: "Individual lesson view within an Academy course — video, content, AI coaching, and quiz.",
    purpose: "Complete individual learning units within a course.",
    keyFeatures: ["Lesson content", "AI coach", "Progress save", "Next lesson navigation"],
    findIt: "Academy → Course → select a lesson.",
  },
  {
    id: "companies_compare",
    name: "Company Compare",
    aliases: ["company compare", "compare companies", "compare company", "side by side companies"],
    path: "/companies/compare",
    category: "Career",
    icon: Building2,
    description: "Side-by-side comparison of multiple companies — culture, leadership, interview difficulty, and executive fit scores.",
    purpose: "Evaluate and compare target companies before making career decisions.",
    keyFeatures: ["Side-by-side comparison", "Culture scores", "Leadership ratings", "Interview difficulty", "Executive fit"],
    findIt: "Companies Intelligence → Compare.",
  },
  {
    id: "company_detail",
    name: "Company Detail",
    aliases: ["company detail", "company profile", "company page", "company overview"],
    path: "/companies/:id",
    category: "Career",
    icon: Building2,
    description: "Detailed company profile — leadership culture, interview prep, executive insights, and career targeting intelligence.",
    purpose: "Deep-dive into a specific company for career targeting and interview preparation.",
    keyFeatures: ["Company overview", "Leadership culture", "Interview preparation", "Executive insights", "Similar companies"],
    findIt: "Companies Intelligence → select a company.",
  },
  {
    id: "cpq_quote_view",
    name: "CPQ Quote View",
    aliases: ["cpq quote view", "quote view", "quote detail", "proposal detail", "view quote"],
    path: "/cpq/quote/:id",
    category: "Administration",
    icon: Receipt,
    description: "Detailed view of a single CPQ quote — line items, pricing breakdown, contract terms, and client actions.",
    purpose: "Review and manage a specific enterprise quote.",
    keyFeatures: ["Quote details", "Pricing breakdown", "Contract terms", "Client actions", "Status tracking"],
    findIt: "My Quotes → select a quote.",
  },
  {
    id: "cpq_quotes",
    name: "My Quotes",
    aliases: ["my quotes", "quotes", "quote history", "enterprise quotes", "quote list"],
    path: "/cpq/quotes",
    category: "Administration",
    icon: Receipt,
    description: "View and manage all CPQ quotes you've created — track status, resend to clients, and download contracts.",
    purpose: "Manage your enterprise proposal pipeline.",
    keyFeatures: ["Quote list", "Status tracking", "Resend", "Download contract"],
    findIt: "Sidebar → Revenue → My Quotes.",
  },
  {
    id: "organization_billing",
    name: "Organization Billing",
    aliases: ["organization billing", "org billing", "enterprise billing", "team billing"],
    path: "/organization/billing",
    category: "Enterprise",
    icon: CreditCard,
    description: "Manage billing, invoices, and subscription details for your organization's enterprise account.",
    purpose: "Administer enterprise subscription billing and invoicing.",
    keyFeatures: ["Subscription management", "Invoice history", "Seat management", "Billing contact"],
    findIt: "Enterprise Workspace → Organization → Billing.",
  },
  {
    id: "membership_admin",
    name: "Membership Admin",
    aliases: ["membership admin", "membership management", "membership programs", "program admin"],
    path: "/membership-admin",
    category: "Administration",
    icon: BadgeCheck,
    description: "Manage membership programs, enroll users, and configure program rules and benefits.",
    purpose: "Administer membership programs across the platform.",
    keyFeatures: ["Program management", "User enrollment", "Program rules", "Benefits configuration"],
    findIt: "Sidebar → Management → Membership Admin.",
  },
  {
    id: "referral_admin",
    name: "Referral Admin",
    aliases: ["referral admin", "referral management", "ambassador admin", "referral settings"],
    path: "/referral-admin",
    category: "Administration",
    icon: Gift,
    description: "Administer the referral and ambassador program — configure rewards, review referral activity, and manage payouts.",
    purpose: "Manage the platform's referral and ambassador program.",
    keyFeatures: ["Referral settings", "Reward configuration", "Activity review", "Payout management"],
    findIt: "Sidebar → Management → Referral Admin.",
  },
  {
    id: "identity_verification_admin",
    name: "Identity Verification Admin",
    aliases: ["identity verification admin", "verification admin", "kyc admin", "verification management"],
    path: "/identity-verification-admin",
    category: "Administration",
    icon: BadgeCheck,
    description: "Review and manage identity verification requests, approve or reject submissions, and track verification status.",
    purpose: "Administer the platform's identity verification process.",
    keyFeatures: ["Verification queue", "Document review", "Approve/reject", "Status tracking"],
    findIt: "Sidebar → Management → Identity Verification Admin.",
  },
  {
    id: "legacy_admin",
    name: "Legacy Library Admin",
    aliases: ["legacy admin", "legacy library admin", "letter moderation", "content moderation", "legacy moderation"],
    path: "/legacy-library/admin",
    category: "Administration",
    icon: BookOpen,
    description: "Moderate and manage the Legacy Library — review submitted letters, manage editorial workflow, and monitor community standards.",
    purpose: "Ensure editorial quality and community standards in the Legacy Library.",
    keyFeatures: ["Letter review queue", "AI moderation", "Editorial workflow", "Code of conduct enforcement"],
    findIt: "Sidebar → Management → Legacy Library Admin.",
  },
  {
    id: "enterprise_organizations",
    name: "Organization Management™",
    aliases: ["organization management", "enterprise organizations", "org management", "manage organizations", "enterprise org", "tenant management"],
    path: "/enterprise/organizations",
    category: "Enterprise",
    icon: Building2,
    description: "Enterprise multi-tenant organization management — create, configure, and manage enterprise client organizations, hierarchy, and provisioning.",
    purpose: "Administer the full lifecycle of enterprise organizations within the platform.",
    keyFeatures: ["Organization creation", "Tenant hierarchy", "Seat management", "Module provisioning", "Organization status"],
    findIt: "Enterprise Workspace → Organizations.",
  },
  {
    id: "enterprise_admin",
    name: "Enterprise Administration™",
    aliases: ["enterprise admin", "enterprise administration", "enterprise management", "enterprise settings", "org admin panel"],
    path: "/enterprise/admin",
    category: "Enterprise",
    icon: Building2,
    description: "Enterprise administration panel — manage users, roles, workspaces, licenses, and enterprise governance across the platform.",
    purpose: "Centralized admin hub for all enterprise-level user and workspace management.",
    keyFeatures: ["User lifecycle", "Role administration", "License management", "Workspace administration", "Delegated administration", "Audit center"],
    findIt: "Enterprise Workspace → Administration.",
  },
  {
    id: "enterprise_identity",
    name: "Enterprise Identity™",
    aliases: ["enterprise identity", "enterprise sso", "identity management", "enterprise idp", "enterprise identity providers", "scim", "saml enterprise"],
    path: "/enterprise/identity",
    category: "Enterprise",
    icon: Fingerprint,
    description: "Enterprise Identity Management — configure SSO, SAML/OIDC identity providers, SCIM provisioning, group sync, and role sync for enterprise tenants.",
    purpose: "Manage enterprise-grade identity federation, automated provisioning, and security policies.",
    keyFeatures: ["Identity Providers", "SSO Configuration", "SCIM Provisioning", "Group Sync", "Role Sync", "License Automation", "Identity Guardian"],
    findIt: "Enterprise Workspace → Identity.",
  },
  {
    id: "enterprise_portal",
    name: "Enterprise Portal",
    aliases: ["enterprise portal", "quote portal", "proposal portal", "client portal", "enterprise proposal"],
    path: "/portal/:quoteId",
    category: "Enterprise",
    icon: Building2,
    description: "Client-facing portal where enterprise prospects review, accept, and activate their CPQ proposals and contracts.",
    purpose: "Provide a professional, self-service experience for enterprise clients to review and sign proposals.",
    keyFeatures: ["Proposal review", "Contract acceptance", "Activation flow", "Payment setup", "Document download"],
    findIt: "Accessed via portal link in enterprise quote emails.",
  },
];

/**
 * Find the best-matching module for a natural-language query.
 * Used to power "Where is X?" questions with one-click navigation.
 */
export function findModule(query) {
  if (!query) return null;
  const q = query.toLowerCase();
  // Direct "where is" / "how do I find" detection
  const whereMatch = q.match(/where(?:'s| is| can i find| do i find)?\s+(.*)/);
  const findMatch = q.match(/how (?:do|can) i (?:find|get to|open|access)\s+(.*)/);
  const target = (whereMatch?.[1] || findMatch?.[1] || q).replace(/[?.!]/g, "").trim();
  if (!target) return null;

  let best = null;
  let bestScore = 0;
  for (const mod of EXEC_KNOWLEDGE_INDEX) {
    let score = 0;
    const name = mod.name.toLowerCase().replace(/[™]/g, "");
    if (q.includes(name)) score += 3;
    for (const alias of mod.aliases) {
      if (target.includes(alias) || alias.includes(target)) score += 2;
    }
    if (score > bestScore) {
      bestScore = score;
      best = mod;
    }
  }
  return bestScore > 0 ? best : null;
}

/**
 * Build a compact summary of the full knowledge index for injection into the LLM prompt.
 */
export function buildFrameworkHierarchySummary() {
  return EXEC_FRAMEWORK_HIERARCHY.map((f, i) => {
    const arrow = i < EXEC_FRAMEWORK_HIERARCHY.length - 1 ? " →" : "";
    return `${f.name} (${f.full} v${f.version})${arrow}`;
  }).join("\n");
}

export function buildKnowledgeIndexSummary() {
  return EXEC_KNOWLEDGE_INDEX.map((m) =>
    `- ${m.name} (${m.path}): ${m.description} | Find it: ${m.findIt}`
  ).join("\n");
}

export const EXEC_KNOWLEDGE_BASE = EXEC_KNOWLEDGE_INDEX.map((m) => m.name);