export const PLAN_CONTENT = {
  free: {
    headline: "Start Your Executive Leadership Journey",
    audience: ["Students", "Graduates", "Career Shifters", "Early Professionals"],
    roi: "Experience EXECLEAD.AI before upgrading.",
    cta: "Start Free",
    accent: "text-slate-400",
    ring: "border-white/10",
    glow: "from-slate-500/5",
  },
  professional: {
    headline: "Accelerate Your Leadership Career",
    audience: ["Team Leads", "Supervisors", "Service Desk Leads", "Operations Managers", "IT Professionals"],
    roi: "Land your next promotion faster.",
    cta: "Start Professional",
    accent: "text-indigo-400",
    ring: "border-indigo-500/30",
    glow: "from-indigo-500/10",
  },
  executive: {
    headline: "Your Personal Executive Leadership Coach",
    audience: ["Senior Managers", "Regional Managers", "Service Delivery Managers", "Directors", "Country Managers", "Executives"],
    roi: "Develop the capabilities expected from senior executive leaders.",
    cta: "Become an Executive Leader",
    accent: "text-purple-400",
    ring: "border-purple-500/30",
    glow: "from-purple-500/10",
  },
  enterprise: {
    headline: "Build Executive Leadership Across Your Organization",
    audience: ["Organizations", "Government", "Consulting", "Technology", "Banking", "Healthcare", "Global Enterprises"],
    roi: "Transform your organization's leadership capability.",
    cta: "Talk to Sales",
    startingUsers: 100,
    accent: "text-emerald-400",
    ring: "border-emerald-500/30",
    glow: "from-emerald-500/10",
  },
};

export const ENTERPRISE_OUTCOMES = [
  { icon: "GraduationCap", title: "Develop Future Leaders", desc: "Structured development programs that build leadership capability at every level." },
  { icon: "Users", title: "Improve Succession Planning", desc: "Identify and develop your next generation of leaders before you need them." },
  { icon: "Layers", title: "Standardize Leadership Development", desc: "One consistent framework for excellence across every department and region." },
  { icon: "TrendingDown", title: "Reduce Coaching Costs", desc: "AI-powered executive coaching at a fraction of traditional fees." },
  { icon: "BookOpen", title: "Preserve Executive Knowledge", desc: "Capture and transfer institutional wisdom from retiring leaders to emerging talent." },
  { icon: "TrendingUp", title: "Increase Internal Promotions", desc: "Build ready-now talent pipelines and reduce external executive hiring costs." },
  { icon: "GitBranch", title: "Strengthen Leadership Pipelines", desc: "Visualize readiness gaps and build development plans for every role." },
  { icon: "Gauge", title: "Measure Leadership Maturity", desc: "Quantify capability with data-driven competency scoring and benchmarks." },
  { icon: "Globe", title: "Support Global Teams", desc: "Multi-region, multi-department support with localized learning and 24/7 access." },
];

export const FEATURE_GROUPS = {
  professional: [
    { category: "Leadership Development", items: ["Daily executive challenges", "Executive journal", "Leadership analytics"] },
    { category: "Career Studio", items: ["Resume builder", "Cover letters", "LinkedIn optimizer", "ATS scoring"] },
    { category: "Resume Intelligence", items: ["AI resume analysis", "Skill gap detection", "Truth Engine verification"] },
    { category: "Executive Academy", items: ["18 learning paths", "Daily lessons", "Certifications"] },
    { category: "AI Executive Coach", items: ["11 AI personas", "24/7 availability", "Unlimited sessions"] },
    { category: "Interview Simulator", items: ["Executive interview practice", "Real-time feedback", "Performance scoring"] },
  ],
  executive: [
    { category: "Leadership DNA™", items: ["Competency radar", "Executive readiness score", "Growth insights"] },
    { category: "Executive Council™", items: ["Multi-persona AI advisory", "Strategic decision support", "Board-level perspectives"] },
    { category: "Board Meeting Simulator", items: ["Board-level presentations", "Q&A simulation", "Stakeholder management"] },
    { category: "Executive Negotiation Coach", items: ["Deal strategy coaching", "Real-time guidance", "Outcome analysis"] },
    { category: "Executive Storytelling", items: ["Narrative frameworks", "Executive presence", "Investor pitches"] },
    { category: "Crisis Management", items: ["Major incident simulation", "Crisis communication", "Decision under pressure"] },
    { category: "Commercial Leadership", items: ["P&L management", "Commercial acumen", "Business case development"] },
    { category: "Strategic Decision Making", items: ["Strategy workshops", "Scenario planning", "Executive reviews"] },
  ],
  enterprise: [
    { category: "Organization Dashboard", items: ["Org-wide visibility", "Leadership heatmap", "Readiness overview"] },
    { category: "HR Dashboard", items: ["Workforce analytics", "Learning outcomes", "ROI tracking"] },
    { category: "Leadership Analytics", items: ["Competency trends", "Department benchmarks", "Growth metrics"] },
    { category: "Succession Planning", items: ["Talent pipeline mapping", "Readiness gaps", "Bench strength"] },
    { category: "Promotion Readiness", items: ["Assessment tracking", "Gap analysis", "Development plans"] },
    { category: "Learning Assignments", items: ["Assign learning paths", "Track completion", "Measure outcomes"] },
    { category: "Department Analytics", items: ["Per-department insights", "Comparison views", "Trend analysis"] },
    { category: "Seat Management", items: ["License allocation", "Role management", "Usage tracking"] },
    { category: "Organization Intelligence", items: ["20+ company profiles", "Competitive intelligence", "Career pathing"] },
    { category: "Custom Branding", items: ["White-label option", "Custom domain", "Brand themes"] },
    { category: "SSO & Identity", items: ["SAML 2.0 / OIDC", "Azure AD", "Google Workspace"] },
    { category: "SCIM Provisioning", items: ["Automated lifecycle", "Deprovisioning", "Group sync"] },
    { category: "API Access", items: ["REST API", "Webhooks", "Custom integrations"] },
    { category: "Audit Logs", items: ["Comprehensive logging", "Compliance trail", "Exportable reports"] },
    { category: "Enterprise Support", items: ["Dedicated CSM", "Priority SLA", "QBR sessions"] },
  ],
};

export const COMPARISON_ROWS = [
  { feature: "AI Executive Coach", free: "limited", pro: true, exec: true, ent: true, note: "5/day on Free" },
  { feature: "Executive Simulator", free: "limited", pro: true, exec: true, ent: true, note: "3/week on Free" },
  { feature: "Resume Intelligence", free: false, pro: true, exec: true, ent: true },
  { feature: "Career Studio", free: false, pro: true, exec: true, ent: true },
  { feature: "Truth Engine", free: false, pro: true, exec: true, ent: true },
  { feature: "Leadership DNA™", free: false, pro: false, exec: true, ent: true },
  { feature: "Executive Council™", free: false, pro: false, exec: true, ent: true },
  { feature: "Company Intelligence", free: "limited", pro: true, exec: true, ent: true, note: "1 company on Free" },
  { feature: "Executive Analytics", free: false, pro: true, exec: true, ent: true },
  { feature: "Marketplace", free: true, pro: true, exec: true, ent: true },
  { feature: "Organization Dashboard", free: false, pro: false, exec: false, ent: true },
  { feature: "SSO", free: false, pro: false, exec: false, ent: true },
  { feature: "SCIM", free: false, pro: false, exec: false, ent: true },
  { feature: "API Access", free: false, pro: false, exec: false, ent: true },
  { feature: "Dedicated Success Manager", free: false, pro: false, exec: false, ent: true },
  { feature: "Priority Support", free: false, pro: false, exec: false, ent: true },
  { feature: "Enterprise Analytics", free: false, pro: false, exec: false, ent: true },
];

export const FAQ_ITEMS = [
  { q: "Can I cancel anytime?", a: "Yes. You can cancel your subscription at any time from your billing settings. You'll retain access until the end of your current billing period. No questions asked, no cancellation fees." },
  { q: "How does Enterprise pricing work?", a: "Enterprise pricing is customized based on your number of active users, selected modules, AI package, support tier, and contract length. Use our Enterprise Calculator to get an instant estimate, or contact our sales team for a tailored proposal. Pricing starts at 100 users with volume discounts at every tier." },
  { q: "Do you support annual billing?", a: "Yes. Annual billing gives you 2 months free compared to monthly billing. You can switch between monthly and annual billing at any time from your account settings." },
  { q: "Do you offer education discounts?", a: "Yes. We offer 25% off for educational institutions and non-profit organizations. Contact our sales team with your credentials to apply the discount to your enterprise proposal." },
  { q: "Can we migrate existing users?", a: "Absolutely. Our implementation team handles user migration, content transfer, and progress tracking from your existing LMS or platform. Data migration is included as a professional service in enterprise contracts." },
  { q: "Do you support SSO?", a: "Yes. Enterprise plans include SAML 2.0 and OIDC single sign-on, with native integrations for Azure AD, Google Workspace, and Okta. SCIM 2.0 automated provisioning is also supported." },
  { q: "How does AI usage work?", a: "Each plan includes AI-powered coaching, simulation, and analysis. Professional and Executive plans have unlimited AI requests. Enterprise plans can choose from four AI packages (Basic, Professional, Executive, Unlimited) based on usage needs. The AI Usage Dashboard lets admins track token consumption and costs in real time." },
];