// Auto-generated by the RBAC Validation Engine audit.
// Reflects the on-disk RLS state of every restricted EXECLEAD.AI entity.
// Re-run the audit in the Platform Governance Center to refresh.
export const RBAC_REGISTRY = [
  {
    "name": "AIOptimizationEvent",
    "ops": {
      "create": "public",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "AIPolicyEvent",
    "ops": {
      "create": "public",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "AIRequestTrace",
    "ops": {
      "create": "public",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "AccountDeletionRequest",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "AnswerAttempt",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ArchitectureProposal",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "AutomationRule",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "BetaApplication",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "BetaCohort",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "BetaCommunication",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "BetaFeedback",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "BetaInvitation",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "BillingEvent",
    "ops": {
      "create": "public",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "BusinessIntelligenceReport",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "CommentAppeal",
    "ops": {
      "create": "other",
      "read": "other",
      "update": "founder",
      "delete": "other"
    }
  },
  {
    "name": "CommercialTask",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "CompanyAuditLog",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "immutable",
      "delete": "immutable"
    }
  },
  {
    "name": "ConsentRecord",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ContinuousImprovementAction",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "CouncilReview",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "DataSubjectRequest",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "DecisionAttempt",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "DecisionProfile",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "DecisionScenario",
    "ops": {
      "create": "founder",
      "read": "public",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "DeletionPolicyConfig",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "Department",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ELIMKnowledgePack",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "EnterpriseReport",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "EvidenceCollection",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "EvidenceItem",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "EvidenceRequest",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ExecVerification",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ExecutiveAction",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ExecutiveAffiliation",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "other",
      "delete": "other"
    }
  },
  {
    "name": "ExecutiveBriefing",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ExecutiveCredential",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "immutable",
      "delete": "immutable"
    }
  },
  {
    "name": "ExecutiveDecision",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ExecutiveIdentityTransfer",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ExecutiveInsight",
    "ops": {
      "create": "founder",
      "read": "public",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ExecutiveOutcome",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ExecutiveSuccessStory",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ExecutiveWallet",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "FeatureFlag",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "FeatureFlagAudit",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "immutable",
      "delete": "founder"
    }
  },
  {
    "name": "FounderStory",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "FoundingMember",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "FoundingMemberAuditLog",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "immutable",
      "delete": "immutable"
    }
  },
  {
    "name": "GovernanceAuditLog",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "immutable",
      "delete": "immutable"
    }
  },
  {
    "name": "GovernanceCertificate",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "immutable"
    }
  },
  {
    "name": "GovernanceConfig",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "immutable",
      "delete": "immutable"
    }
  },
  {
    "name": "GovernanceNotificationLog",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "immutable",
      "delete": "founder"
    }
  },
  {
    "name": "GovernanceRequest",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "immutable",
      "delete": "immutable"
    }
  },
  {
    "name": "IdentityProvider",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "IdentitySyncEvent",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "immutable",
      "delete": "immutable"
    }
  },
  {
    "name": "IdentitySyncStatus",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "immutable",
      "delete": "immutable"
    }
  },
  {
    "name": "IdentityVerification",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "InterviewScenario",
    "ops": {
      "create": "founder",
      "read": "public",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "Invoice",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "immutable"
    }
  },
  {
    "name": "JourneyEvent",
    "ops": {
      "create": "other",
      "read": "other",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "LaunchQuestion",
    "ops": {
      "create": "founder",
      "read": "public",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "LegacyAuditLog",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "immutable",
      "delete": "immutable"
    }
  },
  {
    "name": "LessonProgress",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ModelRoutingEvent",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "NetworkConnection",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "NewsletterSubscription",
    "ops": {
      "create": "public",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "OrgMembership",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "Organization",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "OtpActivityLog",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "immutable",
      "delete": "immutable"
    }
  },
  {
    "name": "PerformanceJob",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "PlatformActivity",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "immutable",
      "delete": "immutable"
    }
  },
  {
    "name": "PlatformStateEvent",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "immutable",
      "delete": "immutable"
    }
  },
  {
    "name": "PortfolioVersion",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "immutable",
      "delete": "immutable"
    }
  },
  {
    "name": "PracticeSession",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ProcurementRequest",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ProductCapabilityMetric",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ProductInsight",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "PromotionForecast",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "Referral",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ReferralTransaction",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ReleaseBlocker",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "RemediationPatch",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ReportEvidence",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ReputationAppeal",
    "ops": {
      "create": "other",
      "read": "other",
      "update": "founder",
      "delete": "other"
    }
  },
  {
    "name": "ReputationAuditLog",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "immutable",
      "delete": "immutable"
    }
  },
  {
    "name": "ResumeImport",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "immutable",
      "delete": "immutable"
    }
  },
  {
    "name": "ResumeVersion",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ScheduledMaintenance",
    "ops": {
      "create": "founder",
      "read": "other",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "ScheduledReport",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "SecurityEvent",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "SecurityIncident",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "immutable"
    }
  },
  {
    "name": "SecuritySession",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "SelfHealingEvent",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "immutable",
      "delete": "immutable"
    }
  },
  {
    "name": "ShareEvent",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "Skill",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "other",
      "delete": "other"
    }
  },
  {
    "name": "Subscription",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "SubscriptionAuditLog",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "immutable",
      "delete": "immutable"
    }
  },
  {
    "name": "SystemIncident",
    "ops": {
      "create": "founder",
      "read": "other",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "Team",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "TelemetryEvent",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "immutable",
      "delete": "immutable"
    }
  },
  {
    "name": "TrustedDevice",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "UsageLog",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "immutable",
      "delete": "immutable"
    }
  },
  {
    "name": "UserProfile",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "Vendor",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "VerificationLog",
    "ops": {
      "create": "public",
      "read": "founder",
      "update": "immutable",
      "delete": "immutable"
    }
  },
  {
    "name": "WalletTransaction",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "WithdrawalRequest",
    "ops": {
      "create": "other",
      "read": "founder",
      "update": "founder",
      "delete": "founder"
    }
  },
  {
    "name": "WorkflowExecutionLog",
    "ops": {
      "create": "founder",
      "read": "founder",
      "update": "immutable",
      "delete": "founder"
    }
  }
];
export const RESTRICTED_COUNT = 107;
export const GENERATED_AT = "2026-07-30T23:45:52.199Z";
