import React from "react";
import { motion } from "framer-motion";
import { Radar, RadarChart, PolarGrid, PolarAngleAxis, ResponsiveContainer } from "recharts";
import { FileText, TrendingUp, Sparkles } from "lucide-react";

const RADAR = [
  { dim: "Strategic Thinking", v: 88 },
  { dim: "Exec. Communication", v: 72 },
  { dim: "Decision Making", v: 85 },
  { dim: "Financial Acumen", v: 68 },
  { dim: "Stakeholder Influence", v: 74 },
  { dim: "Executive Presence", v: 78 },
];

const STRENGTHS = ["Strategic Thinking", "Executive Ownership", "Problem Solving"];
const OPPORTUNITIES = ["Executive Communication", "Financial Acumen", "Stakeholder Influence", "Board Presence"];
const PLAN = [
  { d: 1, t: "Executive Reflection" }, { d: 2, t: "Communication" }, { d: 3, t: "Simulation" },
  { d: 4, t: "Stakeholder Practice" }, { d: 5, t: "Strategic Challenge" }, { d: 6, t: "Decision Exercise" }, { d: 7, t: "Progress Review" },
];

export default function ReadinessReportPreview() {
  return (
    <section className="py-16 md:py-20 px-6 lg:px-8 bg-white/[0.01]">
      <div className="max-w-5xl mx-auto">
        <div className="text-center mb-8">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 bg-indigo-500/10 border border-indigo-500/20 rounded-full text-[11px] text-indigo-400 font-semibold mb-3">
            <FileText size={12} /> What You Receive
          </div>
          <h2 className="text-2xl md:text-3xl font-bold mb-2">Your Executive Readiness Report™</h2>
          <p className="text-white/45 text-sm max-w-xl mx-auto">The signature asset of EXECLEAD.AI — save it, share it, and use it every quarter.</p>
        </div>

        <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.5 }}
          className="rounded-3xl bg-gradient-to-b from-white/[0.04] to-white/[0.01] border border-white/10 overflow-hidden shadow-2xl shadow-black/40">
          {/* Report header */}
          <div className="flex items-center justify-between px-6 py-4 border-b border-white/8 bg-white/[0.02]">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg bg-accent-orange/15 flex items-center justify-center"><FileText size={16} className="text-accent-orange" /></div>
              <div>
                <div className="text-sm font-bold text-white">Executive Readiness Report™</div>
                <div className="text-[10px] text-white/40">Sample Preview · Generated by EXECLEAD.AI</div>
              </div>
            </div>
            <span className="px-2 py-0.5 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-[10px] text-emerald-400 font-medium">Verified</span>
          </div>

          <div className="p-6 grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Left: score + forecast */}
            <div className="space-y-5">
              <div className="rounded-2xl bg-gradient-to-br from-accent-orange/10 to-transparent border border-accent-orange/15 p-5 text-center">
                <div className="text-[10px] uppercase tracking-widest text-accent-orange mb-1">Executive Readiness Score™</div>
                <div className="text-6xl font-bold text-white leading-none">87<span className="text-2xl text-white/40">%</span></div>
                <div className="inline-flex items-center gap-1.5 mt-3 px-2.5 py-0.5 rounded-full bg-accent-orange/15 border border-accent-orange/30 text-xs font-medium text-accent-orange">Promotion Readiness</div>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div className="rounded-xl bg-white/[0.03] border border-white/8 p-3">
                  <div className="text-[9px] uppercase tracking-wider text-white/40">Current Level</div>
                  <div className="text-sm font-semibold text-white mt-0.5">Senior Manager</div>
                </div>
                <div className="rounded-xl bg-white/[0.03] border border-white/8 p-3">
                  <div className="text-[9px] uppercase tracking-wider text-white/40">Target Role</div>
                  <div className="text-sm font-semibold text-white mt-0.5">Director</div>
                </div>
                <div className="rounded-xl bg-white/[0.03] border border-white/8 p-3 col-span-2 flex items-center gap-2">
                  <TrendingUp size={14} className="text-emerald-400" />
                  <div>
                    <div className="text-[9px] uppercase tracking-wider text-white/40">Promotion Forecast™</div>
                    <div className="text-sm font-semibold text-white mt-0.5">9–15 Months</div>
                  </div>
                </div>
              </div>
            </div>

            {/* Right: radar */}
            <div className="rounded-2xl bg-white/[0.03] border border-white/8 p-4">
              <div className="text-[10px] uppercase tracking-wider text-white/40 mb-2">Executive Radar</div>
              <ResponsiveContainer width="100%" height={220}>
                <RadarChart data={RADAR} outerRadius="72%">
                  <PolarGrid stroke="rgba(255,255,255,0.1)" />
                  <PolarAngleAxis dataKey="dim" tick={{ fill: "rgba(255,255,255,0.45)", fontSize: 9 }} />
                  <Radar dataKey="v" stroke="#f59e0b" fill="#f59e0b" fillOpacity={0.3} strokeWidth={1.5} />
                </RadarChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Strengths & opportunities */}
          <div className="px-6 pb-6 grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="rounded-2xl bg-emerald-500/[0.04] border border-emerald-500/15 p-4">
              <div className="text-[10px] uppercase tracking-wider text-emerald-400 mb-2">Leadership Strengths</div>
              <div className="flex flex-wrap gap-1.5">
                {STRENGTHS.map((s) => <span key={s} className="px-2.5 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-[11px] text-emerald-300">{s}</span>)}
              </div>
            </div>
            <div className="rounded-2xl bg-amber-500/[0.04] border border-amber-500/15 p-4">
              <div className="text-[10px] uppercase tracking-wider text-amber-400 mb-2">Highest Growth Opportunities</div>
              <div className="flex flex-wrap gap-1.5">
                {OPPORTUNITIES.map((s) => <span key={s} className="px-2.5 py-1 rounded-full bg-amber-500/10 border border-amber-500/20 text-[11px] text-amber-300">{s}</span>)}
              </div>
            </div>
          </div>

          {/* 7-day plan mini */}
          <div className="px-6 pb-6">
            <div className="rounded-2xl bg-white/[0.03] border border-white/8 p-4">
              <div className="text-[10px] uppercase tracking-wider text-white/40 mb-3">7-Day Executive Coaching Plan™</div>
              <div className="grid grid-cols-7 gap-1.5">
                {PLAN.map((p) => (
                  <div key={p.d} className="rounded-lg bg-white/[0.03] border border-white/8 p-2 text-center">
                    <div className="text-[8px] text-white/30 font-mono">DAY {p.d}</div>
                    <div className="text-[9px] text-white/60 font-medium mt-0.5 leading-tight">{p.t}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* EXEC recommendation */}
          <div className="px-6 pb-6">
            <div className="rounded-2xl bg-gradient-to-r from-indigo-500/10 to-transparent border border-indigo-500/20 p-4 flex items-start gap-3">
              <div className="w-8 h-8 rounded-lg bg-indigo-500/15 flex items-center justify-center shrink-0"><Sparkles size={15} className="text-indigo-400" /></div>
              <div>
                <div className="text-[11px] font-semibold text-indigo-300 mb-1">EXEC™ Recommendation</div>
                <p className="text-sm text-white/70 leading-relaxed italic">
                  "You already demonstrate strong strategic thinking. Your biggest opportunity is communicating business
                  impact with executive confidence. Complete the next 7 days of coaching to increase your Executive Readiness Score."
                </p>
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}