import React, { useState } from "react";
import { FileDown, FileSpreadsheet, Save, Share2, Presentation, Package, Loader2, Check, Briefcase, ClipboardList, BarChart3, Mail } from "lucide-react";
import { base44 } from "@/api/base44Client";

export default function RoiBusinessCase({ inputs, assumptions, roi, insights }) {
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [shared, setShared] = useState(false);
  const [summaryCopied, setSummaryCopied] = useState(false);

  const pdf = (audience) => import("@/lib/enterpriseRoiPdf").then(({ generateBusinessCasePdf: gen }) => gen(inputs, assumptions, roi, insights, audience));

  const downloadCsv = () => {
    const rows = [["Field", "Value"], ["Organization", inputs.organizationName], ["Leadership Population", inputs.leadershipPopulation], ["Annual Gross Value", roi.annualGrossValue], ["Annual Investment", roi.annualPlatformInvestment], ["Net Business Impact", roi.annualNetValue], ["Three-Year ROI %", roi.threeYearROI], ["Payback (months)", roi.paybackPeriod], ...roi.metrics.map((m) => [m.label, m.value])];
    const csv = rows.map((r) => r.map((c) => `"${String(c ?? "").replace(/"/g, '""')}"`).join(",")).join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `EXECLEAD-ROI-${(inputs.organizationName || "org").replace(/\s+/g, "-")}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const save = async () => {
    setSaving(true);
    try {
      const me = await base44.auth.me().catch(() => null);
      await base44.entities.EnterpriseROICalculation.create({
        organization_name: inputs.organizationName || "Organization",
        industry: inputs.industry, country: inputs.country,
        calc_date: new Date().toISOString(),
        inputs_json: JSON.stringify(inputs), assumptions_json: JSON.stringify(assumptions),
        estimated_annual_value: roi.annualGrossValue, estimated_three_year_roi: roi.threeYearROI ?? 0,
        estimated_net_impact: roi.annualNetValue, business_case_generated: true, proposal_generated: false,
        sales_owner: me?.email || me?.full_name || "", opportunity_stage: "Qualification",
        share_token: "roi_" + Math.random().toString(36).slice(2, 10),
      });
      setSaved(true);
    } catch {}
    setSaving(false);
  };

  const share = () => {
    const url = `${window.location.origin}/enterprise/roi?share=${"roi_" + Math.random().toString(36).slice(2, 10)}`;
    navigator.clipboard?.writeText(url).then(() => setShared(true)).catch(() => setShared(true));
    setTimeout(() => setShared(false), 2500);
  };

  const shareableSummary = () => {
    const txt = `Executive Business Case™ — ${inputs.organizationName || "Organization"}\nLeadership Population: ${inputs.leadershipPopulation}\nEstimated Annual Value: $${roi.annualGrossValue.toLocaleString()}\nNet Business Impact: $${roi.annualNetValue.toLocaleString()}\nThree-Year ROI: ${roi.threeYearROI}%\nPayback: ${roi.paybackPeriod ? roi.paybackPeriod + " months" : "—"}\n\nGenerated by EXECLEAD.AI Enterprise Leadership ROI Calculator™. Scenario-based planning estimates — not guarantees.`;
    navigator.clipboard?.writeText(txt).then(() => setSummaryCopied(true)).catch(() => setSummaryCopied(true));
    setTimeout(() => setSummaryCopied(false), 2500);
  };

  const btn = "inline-flex items-center justify-center gap-1.5 rounded-xl px-4 py-2.5 text-sm font-semibold transition-colors";
  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-5">
      <h3 className="text-white text-sm font-semibold mb-1">Executive Business Case™ & Enterprise Sales</h3>
      <p className="text-white/45 text-xs mb-4">Generate audience-specific reports for procurement, finance, HR, and board approval. PowerPoint available at General Availability.</p>
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
        <button onClick={() => pdf("default")} className={`${btn} bg-accent-orange hover:bg-accent-orange/90 text-white`}><FileDown size={14} /> Full PDF</button>
        <button onClick={() => pdf("cfo")} className={`${btn} bg-white/5 hover:bg-white/10 border border-white/10 text-white/70`}><BarChart3 size={14} /> CFO Summary</button>
        <button onClick={() => pdf("chro")} className={`${btn} bg-white/5 hover:bg-white/10 border border-white/10 text-white/70`}><Briefcase size={14} /> CHRO Summary</button>
        <button onClick={() => pdf("board")} className={`${btn} bg-white/5 hover:bg-white/10 border border-white/10 text-white/70`}><Presentation size={14} /> Board Presentation</button>
        <button onClick={() => pdf("procurement")} className={`${btn} bg-white/5 hover:bg-white/10 border border-white/10 text-white/70`}><ClipboardList size={14} /> Procurement</button>
        <button onClick={() => pdf("presentation")} className={`${btn} bg-white/5 hover:bg-white/10 border border-white/10 text-white/70`}><Package size={14} /> Exec Presentation</button>
        <button onClick={downloadCsv} className={`${btn} bg-white/5 hover:bg-white/10 border border-white/10 text-white/70`}><FileSpreadsheet size={14} /> Excel (CSV)</button>
        <button onClick={shareableSummary} className={`${btn} bg-white/5 hover:bg-white/10 border border-white/10 text-white/70`}>{summaryCopied ? <Check size={14} className="text-emerald-400" /> : <Mail size={14} />} {summaryCopied ? "Copied" : "Shareable Summary"}</button>
        <button onClick={save} disabled={saving} className={`${btn} bg-white/5 hover:bg-white/10 border border-white/10 text-white/70`}>{saving ? <Loader2 size={14} className="animate-spin" /> : saved ? <Check size={14} className="text-emerald-400" /> : <Save size={14} />} {saved ? "Saved" : "Save ROI"}</button>
        <button onClick={share} className={`${btn} bg-white/5 hover:bg-white/10 border border-white/10 text-white/70`}>{shared ? <Check size={14} className="text-emerald-400" /> : <Share2 size={14} />} {shared ? "Link Copied" : "Share ROI"}</button>
        <button disabled className={`${btn} bg-white/[0.02] border border-white/8 text-white/30 cursor-not-allowed col-span-2 sm:col-span-1`}><Presentation size={14} /> PowerPoint (GA)</button>
      </div>
      <p className="text-white/35 text-[10px] mt-3">Saved reports store organization, inputs, assumptions, ROI, owner, and opportunity stage in your Enterprise ROI CRM record.</p>
    </div>
  );
}