// Executive Knowledge Center™ — content library & taxonomy (shared backend/frontend)
export const AUDIENCES = [
  'General User', 'Manager', 'Executive', 'Enterprise', 'HR',
  'Recruiter', 'Investor', 'Media', 'Developer', 'Administrator',
];

export const NAV_GROUPS = [
  { label: 'Overview', categories: ['General', 'Mission', 'Vision', 'Founder'] },
  { label: 'Getting Started', categories: ['General', 'Product', 'Beta', 'Support'] },
  { label: 'Platform', categories: ['Platform', 'Architecture', 'Technical', 'API', 'Roadmap'] },
  { label: 'Features', categories: ['Executive Identity™', 'Executive Journey™', 'Leadership DNA™', 'Executive Portfolio™', 'Company Intelligence™'] },
  { label: 'Assessments', categories: ['Executive Readiness™'] },
  { label: 'AI', categories: ['Executive Coach™', 'Executive Simulator™', 'Decision Lab™', 'Launch Defense™', 'Responsible AI'] },
  { label: 'Security', categories: ['Security', 'Privacy'] },
  { label: 'Enterprise', categories: ['Enterprise', 'HR', 'Talent Management'] },
  { label: 'Pricing', categories: ['Pricing', 'Billing', 'Subscriptions'] },
  { label: 'Responsible AI', categories: ['Responsible AI'] },
  { label: 'Founder', categories: ['Founder', 'Founding Members'] },
  { label: 'Investors', categories: ['Investors'] },
  { label: 'Media', categories: ['Media'] },
  { label: 'Developers', categories: ['Technical', 'API', 'Architecture'] },
  { label: 'Release Notes', categories: ['Roadmap', 'Release Notes'] },
];

export const TRUST_CATEGORIES = ['Security', 'Privacy', 'Responsible AI'];

const U = '2026-08-06';

function a(slug, title, category, subgroup, question, shortAnswer, detailedAnswer, scenario, does, doesNot, bestPractice, relatedFeatures, relatedArticles, audience, difficulty, tags) {
  return {
    slug, title, category, subgroup,
    audience: audience || ['General User'],
    difficulty: difficulty || 'beginner',
    question, short_answer: shortAnswer, detailed_answer: detailedAnswer,
    scenario, what_it_does: does, what_it_does_not: doesNot, best_practice: bestPractice,
    related_features: relatedFeatures || [],
    related_articles: relatedArticles || [],
    tags: tags || [],
    status: 'published', published: true, author: 'EXECLEAD.AI', reviewer: 'EXECLEAD.AI',
    review_date: U, version: '1.0', last_updated: U,
  };
}

export const ARTICLES = [
  a('what-is-execlead', 'What is EXECLEAD.AI?', 'General', 'Overview',
    'What is EXECLEAD.AI?',
    'EXECLEAD.AI is the world\'s first evidence-based Executive Leadership Operating System™ — one AI platform that assesses, develops, and proves executive leadership capability.',
    'EXECLEAD.AI helps ambitious professionals become executive-ready leaders through AI coaching, executive simulations, an Executive Readiness Assessment™, and a Leadership Intelligence Engine™. Unlike generic AI assistants or one-off courses, it continuously measures Executive Readiness™ and builds a verified Executive Identity™ over a lifelong leadership journey.',
    'A technology manager takes the Executive Readiness Assessment™, receives a personalized readiness score and gap analysis, then practices executive decisions in simulations while an AI coach personalizes development each week.',
    'Continuously develops executive leaders and measures Executive Readiness™.',
    'Does not replace human mentors, nor guarantee a specific promotion or job offer.',
    'Begin with the Executive Readiness Assessment™ — it personalizes the entire platform to your leadership journey.',
    ['Executive Readiness™', 'Executive Coach™', 'Executive Identity™'],
    ['why-execlead-vs-chatgpt', 'what-is-executive-readiness', 'who-is-execlead-for'],
    ['General User', 'Manager', 'Executive', 'Investor', 'Media'], 'beginner', ['overview', 'platform', 'leadership']),

  a('why-execlead-vs-chatgpt', 'Why should I use EXECLEAD.AI instead of ChatGPT?', 'General', 'Overview',
    'Why should I use EXECLEAD.AI instead of ChatGPT?',
    'ChatGPT is a general-purpose AI assistant. EXECLEAD.AI is a purpose-built Executive Leadership Operating System™ designed specifically for leadership development.',
    'ChatGPT answers general questions but has no concept of your leadership journey, no Executive Readiness score, no verified Executive Identity™, and no leadership simulations. EXECLEAD.AI is engineered around executive leadership: adaptive assessments, an evidence engine, executive simulations, and a continuous Leadership Intelligence Layer™ that grows with you.',
    'Ask ChatGPT "how do I become a CTO?" and you get generic advice. Ask EXECLEAD.AI and you receive a readiness assessment, a personalized roadmap, and simulations of the exact decisions a CTO faces.',
    'Provides executive-specific, evidence-based, personalized leadership development.',
    'Does not attempt to be a general-purpose chatbot for any topic.',
    'Use EXECLEAD.AI for leadership development; use general AI for unrelated tasks.',
    ['Executive Readiness™', 'Executive Coach™', 'Decision Lab™'],
    ['what-is-execlead', 'what-is-executive-readiness', 'how-does-decision-lab-work'],
    ['General User', 'Manager', 'Executive'], 'beginner', ['comparison', 'chatgpt', 'ai']),

  a('who-is-execlead-for', 'Who is EXECLEAD.AI for?', 'General', 'Overview',
    'Who is EXECLEAD.AI for?',
    'EXECLEAD.AI is for ambitious professionals at every stage of the leadership journey — from early-career explorers to senior executives, founders, HR leaders, and enterprise organizations.',
    'The platform adapts to your level and goals. Today it is optimized for Technology Leadership and Digital Transformation professionals, while expanding toward executive leadership across every industry and function.',
    'An IT manager preparing for a Director role, a VP aiming for CIO, and an HR leader building a succession pipeline can all use the same platform, each with a personalized journey.',
    'Personalizes the journey for individuals, teams, and enterprises.',
    'Does not assume a single starting point — journeys are individual.',
    'Set your target executive role so every recommendation adapts to you.',
    ['Executive Readiness™', 'Executive Journey™'],
    ['what-is-execlead', 'what-is-executive-readiness'],
    ['General User', 'Manager', 'Executive', 'Enterprise', 'HR'], 'beginner', ['audience', 'use-case']),

  a('execlead-mission', 'What is the mission of EXECLEAD.AI?', 'Mission', 'Overview',
    'What is the mission of EXECLEAD.AI?',
    'Leadership is a lifelong journey — not a single promotion. EXECLEAD.AI provides one intelligent AI platform that grows with professionals from their earliest career aspirations to executive leadership and beyond.',
    'The mission is to help ambitious professionals become executive-ready leaders through continuous, evidence-based leadership development — measuring, developing, and demonstrating executive readiness over time.',
    'A member joins as a team lead and, over years, progresses to Director, VP, and C-level — their Executive Identity™ and evidence growing continuously on one platform.',
    'Supports the entire lifelong leadership journey on one platform.',
    'Does not treat leadership as a one-time training event.',
    'Commit to the journey — consistency compounds.',
    ['Executive Journey™', 'Executive Readiness™'],
    ['what-is-execlead', 'execlead-vision'],
    ['General User', 'Investor', 'Media'], 'beginner', ['mission', 'philosophy']),

  a('execlead-vision', 'What is the vision of EXECLEAD.AI?', 'Vision', 'Overview',
    'What is the vision of EXECLEAD.AI?',
    'To establish the AI Executive Leadership Operating System category and become one of the world\'s most trusted platforms for executive leadership development.',
    'EXECLEAD.AI aims to redefine executive leadership development — moving from periodic training to continuous, measurable, evidence-based readiness across every industry.',
    'A future where every organization uses Executive Readiness™ to develop and promote leaders with confidence, and every professional carries a verified Executive Identity™.',
    'Defines a new category: the Executive Leadership Operating System™.',
    'Does not aim to be just another course or coaching marketplace.',
    'Measure what matters — readiness, evidence, and outcomes.',
    ['Executive Readiness™', 'Executive Identity™'],
    ['execlead-mission', 'what-is-execlead'],
    ['General User', 'Investor', 'Media'], 'beginner', ['vision', 'category']),

  a('what-is-executive-readiness', 'What is Executive Readiness™?', 'Executive Readiness™', 'Assessments',
    'What is Executive Readiness™?',
    'Executive Readiness™ is an evidence-based measure of how prepared you are for executive leadership — scored 0–100 across 12 leadership dimensions.',
    'The Executive Readiness Assessment™ combines 16 universal leadership questions with 4 adaptive, role-specific questions. It produces an overall score, a classification (emerging leader → executive ready), a gap analysis, a promotion forecast, and a personalized 90-day roadmap.',
    'A manager scores 68, learns their strongest dimension is Strategic Thinking and their gap is Executive Communication, and receives a roadmap prioritizing stakeholder influence.',
    'Measures readiness continuously with evidence, not a one-time personality test.',
    'Does not predict a guaranteed promotion date or replace human judgment.',
    'Re-take the assessment periodically to track measurable growth.',
    ['Executive Readiness Assessment™', 'Leadership Gap Analysis™'],
    ['how-readiness-calculated', 'how-often-score-updated', 'what-evidence-improves-readiness'],
    ['General User', 'Manager', 'Executive', 'HR'], 'intermediate', ['readiness', 'score', 'assessment']),

  a('how-readiness-calculated', 'How is Executive Readiness™ calculated?', 'Executive Readiness™', 'Assessments',
    'How is Executive Readiness™ calculated?',
    'Executive Readiness™ is a weighted score across 12 leadership dimensions, combining a Universal Leadership Score™ (80%) with Role-Specific Readiness™ (20%).',
    'Each question is scored 0–4 against an evidence-based rubric. Category scores are normalized to 0–100, then combined into the overall Executive Readiness Score™. The result includes a confidence rating based on evidence coverage.',
    'A leader answers scenario questions about delegation, prioritization, and stakeholder influence; each answer is scored and aggregated into dimension and overall readiness.',
    'Uses an evidence-based, transparent scoring rubric.',
    'Does not use opaque personality profiling or astrology-style labels.',
    'Answer honestly — the score is for your growth, not a grade.',
    ['Executive Readiness Assessment™', 'Leadership Gap Analysis™'],
    ['what-is-executive-readiness', 'how-often-score-updated', 'can-enterprises-customize-readiness'],
    ['General User', 'Developer', 'HR'], 'advanced', ['scoring', 'rubric', 'methodology']),

  a('how-often-score-updated', 'How often is my readiness score updated?', 'Executive Readiness™', 'Assessments',
    'How often is my readiness score updated?',
    'Your score updates each time you complete the Executive Readiness Assessment™, and your underlying readiness evidence evolves continuously through coaching, simulations, and outcomes.',
    'The assessment snapshot is point-in-time, but your Executive Identity™ and evidence base grow between assessments — so your true readiness trajectory is visible over time.',
    'A member takes the assessment in March (72) and again in September (79); the trend line shows measurable growth in Executive Communication.',
    'Tracks readiness as a trend, not a single number.',
    'Does not auto-inflate your score without new evidence.',
    'Re-assess every 3–6 months to see real progress.',
    ['Executive Readiness Assessment™', 'Executive Identity™'],
    ['what-is-executive-readiness', 'what-evidence-improves-readiness'],
    ['General User', 'Manager', 'Executive'], 'intermediate', ['trend', 'update', 'evidence']),

  a('what-evidence-improves-readiness', 'What evidence improves my readiness?', 'Executive Readiness™', 'Assessments',
    'What evidence improves my readiness?',
    'Verified leadership evidence — assessment results, simulation outcomes, coaching reflections, achievements, and reported executive outcomes — strengthens your Executive Readiness™ over time.',
    'EXECLEAD.AI\'s Evidence Engine™ links activities to competencies, so completed simulations, journaling, and real-world outcomes all contribute to your readiness trajectory and Executive Identity™.',
    'Completing a crisis simulation and reflecting on the decision adds evidence to your Decision Quality and Stakeholder Management dimensions.',
    'Connects real activities to measurable leadership evidence.',
    'Does not accept unverifiable self-claims as evidence by default.',
    'Log achievements and outcomes regularly — evidence compounds.',
    ['Evidence Engine™', 'Executive Identity™'],
    ['how-readiness-calculated', 'how-often-score-updated', 'what-is-executive-identity'],
    ['General User', 'Manager', 'Executive'], 'intermediate', ['evidence', 'growth']),

  a('can-enterprises-customize-readiness', 'Can enterprises customize assessments?', 'Enterprise', 'Enterprise',
    'Can enterprises customize assessments?',
    'Yes. Enterprises can configure assessment tracks, target roles, and campaigns through enterprise configuration, and assign assessments via SSO, SCIM, department, or HR campaign.',
    'Organizations enable or disable assessment types (Leadership DNA™, Promotion Readiness™, Succession Planning™, etc.) and route employees into the right workflow automatically — employees never select assessments manually.',
    'A CHRO launches a "Q3 Leadership Review" campaign; 200 managers are auto-assigned the Promotion Readiness™ assessment via SCIM groups.',
    'Supports enterprise assignment, configuration, and talent intelligence sync.',
    'Does not expose one employee\'s assessment data to peers or managers without governance.',
    'Align assessment campaigns with your talent review calendar.',
    ['Enterprise Executive Assessment Center™', 'HR Dashboard'],
    ['how-readiness-calculated', 'enterprise-talent-intelligence', 'succession-planning-works'],
    ['Enterprise', 'HR', 'Talent Management', 'Administrator'], 'advanced', ['enterprise', 'configuration', 'assignment']),

  a('what-is-executive-coach', 'What is the Executive Coach™?', 'Executive Coach™', 'AI',
    'What is the Executive Coach™?',
    'The Executive Coach™ (EXEC™) is a personalized, context-aware AI coaching experience with 11 distinct personas modeled on former CIOs, COOs, and CFOs.',
    'EXEC™ uses your Executive Context — readiness scores, leadership track, target role, and evidence — to deliver coaching that adapts to your level, goals, and recent activity across the platform.',
    'After scoring low on Executive Communication, EXEC™ proactively suggests a stakeholder-influence exercise tailored to your target role.',
    'Provides continuous, personalized, context-aware executive coaching.',
    'Does not replace licensed therapeutic or clinical coaching.',
    'Be specific in your asks — context improves coaching quality.',
    ['EXEC™ AI Executive Coach™', 'Executive Readiness™'],
    ['can-ai-replace-coaching', 'how-does-decision-lab-work', 'what-is-executive-readiness'],
    ['General User', 'Manager', 'Executive'], 'beginner', ['coach', 'ai', 'persona']),

  a('can-ai-replace-coaching', 'Can AI replace executive coaching?', 'Executive Coach™', 'AI',
    'Can AI replace executive coaching?',
    'No — AI augments coaching, it does not replace human executive coaches. EXECLEAD.AI provides continuous, on-demand coaching that complements human mentorship.',
    'Human coaches bring relational wisdom, accountability, and context AI cannot replicate. EXEC™ provides always-on practice, simulations, and personalized guidance between human sessions — and can prepare you to get more from a human coach.',
    'A member uses EXEC™ weekly for practice and meets a human coach monthly for deeper strategic conversations.',
    'Augments and scales executive coaching continuously.',
    'Does not claim to fully replace experienced human coaches.',
    'Combine AI practice with human mentorship for the best results.',
    ['Executive Coach™', 'Executive Simulations™'],
    ['what-is-executive-coach', 'why-execlead-vs-chatgpt'],
    ['General User', 'Manager', 'Executive', 'HR'], 'intermediate', ['ai', 'coaching', 'philosophy']),

  a('how-does-decision-lab-work', 'How does the Decision Lab™ work?', 'Decision Lab™', 'AI',
    'How does the Decision Lab™ work?',
    'The Decision Lab™ presents realistic executive decision scenarios, evaluates your chosen strategy across leadership dimensions, and reveals your Decision DNA™ — your recurring decision patterns.',
    'You read a scenario, choose a strategy, and explain your rationale. AI scores dimensions like Strategic Thinking, Decision Quality, and Stakeholder Management, then compares your choice to expert strategy and surfaces blind spots.',
    'A ransomware scenario: you balance CEO urgency, legal caution, and financial impact — and learn your default bias toward speed over stakeholder alignment.',
    'Builds measurable, repeatable decision intelligence.',
    'Does not score opinions as right/wrong — it evaluates executive quality.',
    'Review your blind spots after each scenario — patterns reveal growth areas.',
    ['Decision Lab™', 'Decision DNA™', 'Executive Simulations™'],
    ['what-is-leadership-dna', 'what-is-executive-simulator', 'how-readiness-calculated'],
    ['General User', 'Manager', 'Executive'], 'intermediate', ['decision', 'simulation', 'dna']),

  a('what-is-executive-simulator', 'What is the Executive Simulator™?', 'Executive Simulator™', 'AI',
    'What is the Executive Simulator™?',
    'The Executive Simulator™ lets you practice high-stakes executive decisions — interviews, quarterly business reviews, crises, and negotiations — with realistic AI-driven scenarios.',
    'With 15+ scenarios across leadership categories, the simulator evaluates strategic thinking, communication, stakeholder management, and decision quality, then gives feedback and alternative strategies.',
    'Practice a board-level budget defense before the real meeting and receive feedback on your framing and ROI narrative.',
    'Provides safe, repeatable practice of real executive situations.',
    'Does not simulate your specific real-world stakeholders by name.',
    'Rehearse the scenarios that intimidate you most.',
    ['Executive Simulations™', 'Decision Lab™', 'Launch Defense™'],
    ['how-does-decision-lab-work', 'what-is-launch-defense'],
    ['General User', 'Manager', 'Executive'], 'beginner', ['simulation', 'practice']),

  a('what-is-launch-defense', 'What is the Launch Defense Center™?', 'Launch Defense™', 'AI',
    'What is the Launch Defense Center™?',
    'The Launch Defense Center™ prepares founders and executives to answer the hardest questions from investors, enterprise buyers, journalists, and analysts.',
    'It combines a curated question bank, interviewer personas, an AI interview simulator, answer library, and performance analytics so you can rehearse and refine your narrative before going public.',
    'A founder practices a seed-funding interview against an AI investor persona and improves their differentiation answer.',
    'Builds confidence and clarity for high-stakes external conversations.',
    'Does not script false claims — it strengthens truthful narratives.',
    'Practice the questions you hope nobody asks.',
    ['Launch Defense Center™', 'Executive Simulations™'],
    ['what-is-executive-simulator', 'how-does-decision-lab-work'],
    ['Founder', 'Executive', 'Media', 'Investor'], 'intermediate', ['launch', 'investor', 'media']),

  a('what-is-executive-identity', 'What is Executive Identity™?', 'Executive Identity™', 'Features',
    'What is Executive Identity™?',
    'Executive Identity™ is your verified, evidence-backed executive profile — a living record of your leadership narrative, competencies, and proof.',
    'It synthesizes your assessment results, simulation outcomes, achievements, and outcomes into a professional headline, executive summary, leadership narrative, and verified competencies — with a verification status and confidence score.',
    'A member\'s Executive Identity™ shows "Strategic Technology Leader" with verified competencies in Digital Transformation and Executive Communication.',
    'Builds a portable, verified executive identity that grows with you.',
    'Does not fabricate credentials or claim external verification it cannot prove.',
    'Keep your evidence current — identity strength depends on it.',
    ['Executive Identity™', 'Executive Portfolio™', 'Evidence Engine™'],
    ['what-evidence-improves-readiness', 'what-is-executive-portfolio'],
    ['General User', 'Manager', 'Executive', 'Recruiter'], 'intermediate', ['identity', 'profile']),

  a('what-is-executive-portfolio', 'What is the Executive Portfolio™?', 'Executive Portfolio™', 'Features',
    'What is the Executive Portfolio™?',
    'The Executive Portfolio™ is a shareable, evidence-backed showcase of your executive journey, achievements, readiness, and identity.',
    'It assembles your readiness scores, leadership DNA, simulation history, credentials, and executive story into a public or private portfolio you can share with recruiters, boards, or networks.',
    'A member shares their portfolio link with a recruiter, who sees verified readiness and leadership evidence.',
    'Turns leadership growth into a credible, shareable asset.',
    'Does not expose private data you have not chosen to share.',
    'Choose visibility deliberately — private, anonymous, or named.',
    ['Executive Portfolio™', 'Executive Identity™', 'Executive Success Stories™'],
    ['what-is-executive-identity', 'what-is-leadership-dna'],
    ['General User', 'Executive', 'Recruiter'], 'beginner', ['portfolio', 'share']),

  a('what-is-leadership-dna', 'What is Leadership DNA™?', 'Leadership DNA™', 'Features',
    'What is Leadership DNA™?',
    'Leadership DNA™ reveals your recurring decision-making archetypes and patterns based on your simulation and decision-lab history.',
    'As you complete decisions, EXECLEAD.AI identifies your dominant archetypes, favorite strategies, recurring strengths and blind spots, and decision diversity — turning behavior into insight.',
    'Your DNA shows a "Pragmatic Operator" archetype with a strength in fast execution and a blind spot in stakeholder alignment.',
    'Translates repeated behavior into self-awareness.',
    'Does not pigeonhole you — DNA evolves as you grow.',
    'Use DNA insights to deliberately stretch beyond your defaults.',
    ['Leadership DNA™', 'Decision Lab™', 'Decision DNA™'],
    ['how-does-decision-lab-work', 'what-is-executive-identity'],
    ['General User', 'Manager', 'Executive'], 'intermediate', ['dna', 'archetype', 'patterns']),

  a('what-is-executive-journey', 'What is the Executive Journey™?', 'Executive Journey™', 'Features',
    'What is the Executive Journey™?',
    'The Executive Journey™ is the continuous timeline of your leadership growth — assessments, simulations, coaching, achievements, and milestones in one view.',
    'It visualizes your readiness trend, XP and badges, milestones, and weekly digest so you can see how far you\'ve come and what\'s next.',
    'A member\'s journey shows readiness rising from 62 to 78 over nine months, with badges for consistent practice.',
    'Makes lifelong leadership growth visible and motivating.',
    'Does not reduce your journey to a single score.',
    'Review your journey weekly to stay accountable.',
    ['Executive Journey™', 'Executive Readiness™'],
    ['what-is-executive-readiness', 'how-often-score-updated'],
    ['General User', 'Manager', 'Executive'], 'beginner', ['journey', 'timeline']),

  a('what-is-company-intelligence', 'What is Company Intelligence™?', 'Company Intelligence™', 'Features',
    'What is Company Intelligence™?',
    'Company Intelligence™ provides curated executive intelligence on 126+ global organizations — leadership expectations, interview style, strategy, and culture.',
    'It helps you understand how executives lead and succeed at target companies, with leadership principles, interview questions, and transformation initiatives.',
    'Before interviewing at a target company, a member studies its leadership principles and rehearses matching scenarios.',
    'Connects your development to real organizations and roles.',
    'Does not provide confidential or non-public company data.',
    'Study target companies before interviews and networking.',
    ['Company Intelligence™', 'Executive Simulations™'],
    ['who-is-execlead-for', 'what-is-executive-portfolio'],
    ['General User', 'Executive', 'Recruiter'], 'beginner', ['companies', 'intelligence']),

  a('enterprise-talent-intelligence', 'What is Enterprise Talent Intelligence™?', 'Enterprise', 'Enterprise',
    'What is Enterprise Talent Intelligence™?',
    'Enterprise Talent Intelligence™ automatically aggregates assessment results into real-time organizational insight — no manual HR tracking required.',
    'The HR Dashboard surfaces completion rate, average executive readiness, leadership DNA distribution, promotion-ready counts, high-potential employees, critical gaps, department comparisons, and trend analysis.',
    'A CHRO opens the dashboard and sees 64% campaign completion and a critical gap in Executive Communication across Sales Managers.',
    'Turns assessment data into live talent intelligence.',
    'Does not expose individual data to peers without governance.',
    'Review talent intelligence before each talent review cycle.',
    ['HR Dashboard', 'Enterprise Executive Assessment Center™'],
    ['can-enterprises-customize-readiness', 'succession-planning-works'],
    ['Enterprise', 'HR', 'Talent Management', 'Administrator'], 'advanced', ['enterprise', 'hr', 'intelligence']),

  a('succession-planning-works', 'How does succession planning work?', 'Talent Management', 'Enterprise',
    'How does succession planning work?',
    'Assessment results automatically feed talent reviews, 9-box grids, the leadership pipeline, succession bench strength, and promotion recommendations.',
    'EXECLEAD.AI maps readiness, high-potential identification, and development plans into succession views so HR can identify ready-now and ready-in-12/24-month talent.',
    'A VP retires; succession shows two Director-ready successors and one ready in 12 months.',
    'Provides evidence-based succession depth, not gut calls.',
    'Does not replace human promotion decisions — it informs them.',
    'Pair succession data with development plans for bench strength.',
    ['Succession Planning™', 'HR Dashboard'],
    ['enterprise-talent-intelligence', 'can-enterprises-customize-readiness'],
    ['Enterprise', 'HR', 'Talent Management'], 'advanced', ['succession', 'pipeline']),

  a('how-secure-is-my-data', 'How secure is my data?', 'Security', 'Security',
    'How secure is my data?',
    'EXECLEAD.AI is built with enterprise-grade security: encrypted data, strict access controls, row-level security, and a public Trust Center™ documenting our commitments.',
    'We apply least-privilege access, session security, admin governance gates, audit logging, and a responsible AI policy. Security posture is published in the Trust Center™ for transparency.',
    'An enterprise CISO reviews the Trust Center™ and confirms SOC-aligned controls before procurement.',
    'Treats security as a first-class, transparent commitment.',
    'Does not store sensitive secrets in client code or expose them to the runtime.',
    'Review the Trust Center™ and enable available security features.',
    ['Trust Center™', 'Security Center'],
    ['what-is-trust-center', 'how-is-privacy-handled', 'what-is-responsible-ai'],
    ['General User', 'Enterprise', 'Administrator', 'Investor'], 'intermediate', ['security', 'data', 'trust']),

  a('how-is-privacy-handled', 'How is my privacy handled?', 'Privacy', 'Security',
    'How is my privacy handled?',
    'You control your data. Portfolio and success-story visibility is yours to set (private, anonymous, or named), and you can export or delete your data at any time.',
    'EXECLEAD.AI provides privacy controls, data export, account deletion, and consent records. Enterprise members\' individual results are governed by organizational policy.',
    'A member sets their success story to "anonymous" so it inspires others without exposing identity.',
    'Gives members genuine control over their information.',
    'Does not sell member data to third parties.',
    'Review your privacy settings and visibility preferences regularly.',
    ['Privacy Compliance Center', 'Trust Center™'],
    ['how-secure-is-my-data', 'what-is-responsible-ai'],
    ['General User', 'Enterprise', 'Administrator'], 'intermediate', ['privacy', 'consent', 'data']),

  a('what-is-responsible-ai', 'What is Responsible AI at EXECLEAD.AI?', 'Responsible AI', 'Responsible AI',
    'What is Responsible AI at EXECLEAD.AI?',
    'Responsible AI means transparent, evidence-based, human-accountable AI — never fabrication. EXECLEAD.AI documents its AI policy, model usage, and guardrails publicly.',
    'We track AI request traces, model routing, policy events, and optimization, and we prohibit invention of facts. Ask EXEC™ answers only from approved knowledge and declines when evidence is insufficient.',
    'Ask EXEC™ is asked an unsupported question and responds with related articles instead of inventing an answer.',
    'Builds AI that is explainable, governed, and honest.',
    'Does not allow AI to fabricate credentials, scores, or facts.',
    'Treat AI outputs as input to judgment, not as ground truth.',
    ['Responsible AI Dashboard', 'AI Governance Center', 'Trust Center™'],
    ['how-secure-is-my-data', 'why-execlead-vs-chatgpt', 'can-ai-replace-coaching'],
    ['General User', 'Enterprise', 'Administrator', 'Investor', 'Media'], 'intermediate', ['responsible-ai', 'governance', 'ethics']),

  a('what-is-trust-center', 'What is the Trust Center™?', 'Security', 'Security',
    'What is the Trust Center™?',
    'The Trust Center™ is EXECLEAD.AI\'s public transparency hub for security, privacy, responsible AI, compliance, and operational status.',
    'It documents security commitments, certifications, incident history, responsible AI disclosures, and live platform status so customers can verify trust before buying.',
    'A procurement team downloads the Trust Center™ evidence pack as part of vendor due diligence.',
    'Makes trust verifiable, not claimed.',
    'Does not disclose sensitive internal architecture details.',
    'Link prospects to the Trust Center™ early in enterprise sales.',
    ['Trust Center™', 'Security Center', 'Responsible AI Dashboard'],
    ['how-secure-is-my-data', 'what-is-responsible-ai'],
    ['Enterprise', 'Investor', 'Media', 'Administrator'], 'beginner', ['trust', 'transparency']),

  a('how-pricing-works', 'How does pricing work?', 'Pricing', 'Pricing',
    'How does pricing work?',
    'EXECLEAD.AI offers Free, Professional, Executive, and Enterprise plans. Current access is invitation-only through the Founding Private Beta™; future General Availability pricing is published on the Pricing page.',
    'Each plan communicates an outcome — who it\'s for, the primary outcome, and the upgrade trigger. Founding Members receive protected lifetime benefits.',
    'A professional picks the Executive plan because they\'re preparing for a Director promotion.',
    'Prices plans around transformation, not feature checklists.',
    'Does not lock you in — you can start Free and upgrade anytime.',
    'Choose the plan that matches your next leadership milestone.',
    ['Pricing', 'Founding Members'],
    ['can-i-change-plans', 'what-are-founding-members', 'how-billing-works'],
    ['General User', 'Manager', 'Executive', 'Enterprise'], 'beginner', ['pricing', 'plans']),

  a('can-i-change-plans', 'Can I change or cancel my plan?', 'Billing', 'Pricing',
    'Can I change or cancel my plan?',
    'Yes. You can begin with Free and upgrade at any time. Your Executive Journey remains intact — nothing is lost when you change plans.',
    'Executive Readiness™, the Evidence Engine™, and Executive Identity™ continue with you across every plan. You can cancel anytime from billing settings.',
    'A Free member upgrades to Executive and keeps all prior evidence and progress.',
    'Removes risk from starting — your journey is portable.',
    'Does not delete your evidence when you downgrade.',
    'Start Free, upgrade when your journey demands more.',
    ['Billing', 'Pricing'],
    ['how-pricing-works', 'how-billing-works'],
    ['General User', 'Manager', 'Executive'], 'beginner', ['billing', 'cancel']),

  a('how-billing-works', 'How does billing work?', 'Billing', 'Pricing',
    'How does billing work?',
    'Billing is monthly or annual (annual saves 20%). Enterprise plans are quoted via CPQ. Founding Members receive protected pricing for life.',
    'Manage billing, invoices, and payment settings in-app. Enterprise procurement can use quotes, approvals, and contracts through the platform.',
    'An enterprise buyer requests a CPQ quote for 500 seats and routes it through procurement.',
    'Supports individual self-service and enterprise procurement.',
    'Does not auto-charge without your authorization.',
    'Choose annual if you\'re committed to a multi-month journey.',
    ['Billing', 'CPQ', 'Pricing'],
    ['how-pricing-works', 'can-i-change-plans'],
    ['General User', 'Enterprise', 'Administrator'], 'beginner', ['billing', 'invoices']),

  a('what-are-founding-members', 'What are Founding Members?', 'Founding Members', 'Founder',
    'What are Founding Members?',
    'Founding Members are the first executive leaders to join EXECLEAD.AI — invitation-only, limited, and granted lifetime Founding benefits.',
    'They shape the product, receive protected pricing, early access, community access, roadmap voting, and a permanent Founder Identity Seal™. The program rolls out in waves: Founder Circle™, Founding Beta™, Founding Private Beta™.',
    'A founding member joins in Batch #1 and retains a 25% lifetime discount forever.',
    'Rewards early trust with permanent, protected benefits.',
    'Does not sell founding status — it is earned by invitation.',
    'Apply only if you\'re committed to shaping the platform.',
    ['Founding Members', 'Pricing'],
    ['how-pricing-works', 'execlead-mission'],
    ['General User', 'Founder', 'Investor'], 'beginner', ['founding', 'beta']),

  a('founder-why-built', 'Why did you build EXECLEAD.AI?', 'Founder', 'Founder',
    'Why did you build EXECLEAD.AI?',
    'Because leadership is a lifelong journey — not a single promotion — and no platform measured, developed, and proved executive readiness continuously.',
    'EXECLEAD.AI began by helping technology professionals become executive-ready, then evolved into an Executive Leadership Operating System™ for every industry.',
    'A founder, frustrated by generic leadership content, builds an evidence-based system that actually measures growth.',
    'Solves a real, underserved problem with a new category.',
    'Does not claim to have invented leadership development.',
    'Read the founder story to understand the "why."',
    ['Founder Story', 'Executive Journey™'],
    ['execlead-mission', 'execlead-vision', 'media-what-problem'],
    ['General User', 'Investor', 'Media'], 'beginner', ['founder', 'story']),

  a('investor-why-now', 'Why now for EXECLEAD.AI?', 'Investors', 'Investors',
    'Why now?',
    'AI has matured enough to deliver continuous, personalized leadership development at scale, while the market for executive development remains fragmented and unevidenced.',
    'EXECLEAD.AI defines a new category — the Executive Leadership Operating System™ — at the intersection of AI, leadership development, and talent intelligence.',
    'AI coaching, simulations, and evidence engines are now production-viable; enterprises demand measurable talent intelligence.',
    'Combines a category-defining vision with timing and technology.',
    'Does not chase a crowded generic coaching market.',
    'Review the positioning architecture for the long-term thesis.',
    ['Executive Readiness™', 'Enterprise Talent Intelligence™'],
    ['execlead-vision', 'investor-business-model', 'founder-why-built'],
    ['Investor'], 'intermediate', ['investor', 'market', 'why-now']),

  a('investor-business-model', 'What is the business model?', 'Investors', 'Investors',
    'What is the business model?',
    'EXECLEAD.AI monetizes through individual subscriptions (Free/Professional/Executive) and enterprise contracts (Talent Intelligence, succession, HR) with CPQ-driven procurement.',
    'Individual plans convert as members progress toward executive roles; enterprise expands through seat-based talent intelligence and assessment campaigns.',
    'A professional upgrades to Executive, then their employer adopts Enterprise Talent Intelligence™ org-wide.',
    'Land-and-expand: individual value drives enterprise adoption.',
    'Does not rely on advertising or data sales.',
    'See the pricing page for plan outcomes and upgrade triggers.',
    ['Pricing', 'Enterprise Talent Intelligence™'],
    ['investor-why-now', 'how-pricing-works', 'enterprise-talent-intelligence'],
    ['Investor'], 'intermediate', ['investor', 'business-model', 'revenue']),

  a('media-what-problem', 'What problem are you solving?', 'Media', 'Media',
    'What problem are you solving?',
    'Executive leadership development is periodic, unevidenced, and inaccessible. Most professionals have no measurable way to know if they\'re executive-ready.',
    'EXECLEAD.AI turns leadership development into a continuous, evidence-based journey — measuring readiness, practicing decisions, and building a verified executive identity.',
    'A capable manager is repeatedly passed over for promotion because no one can evidence their executive readiness — until now.',
    'Solves the evidence gap in executive development.',
    'Does not claim leadership can be reduced to a single score.',
    'Reference the mission and vision for the narrative.',
    ['Executive Readiness™', 'Executive Identity™'],
    ['founder-why-built', 'what-is-execlead', 'execlead-mission'],
    ['Media', 'Investor'], 'beginner', ['media', 'problem']),

  a('what-architecture', 'What is the platform architecture?', 'Architecture', 'Developers',
    'What is the platform architecture?',
    'EXECLEAD.AI is a BaaS-backed platform with a React + Tailwind frontend, serverless backend functions, an entity data model, AI integrations, and a governance layer.',
    'It uses Platform Services™, a manifest-driven architecture, row-level security, an authorized dependency allowlist, and Architecture Decision Records™ for accountable evolution.',
    'A developer reviews ADRs to understand why a governance pattern was chosen before extending it.',
    'Governed, observable, and continuously hardened.',
    'Does not expose internal secrets or bypass governance.',
    'Read the architecture decision records before major changes.',
    ['Platform Knowledge Center', 'Platform Governance Center'],
    ['what-is-responsible-ai', 'how-secure-is-my-data'],
    ['Developer', 'Administrator'], 'advanced', ['architecture', 'governance']),

  a('is-there-an-api', 'Is there an API?', 'API', 'Developers',
    'Is there an API?',
    'EXECLEAD.AI exposes backend functions, an SDK, and an MCP server for integrating published app data and functions with AI clients.',
    'Enterprise integrations include SSO/SCIM, Airtable CRM sync, Gmail, and webhook automations. The app MCP server lets AI clients query approved data and functions.',
    'An enterprise integrates EXECLEAD.AI assessment data into its HRIS via a backend function.',
    'Supports enterprise and AI-client integration.',
    'Does not expose raw database access or unauthenticated endpoints.',
    'Use the SDK and approved functions — never bypass governance.',
    ['API Keys', 'Connected Accounts', 'App MCP'],
    ['what-architecture', 'can-enterprises-customize-readiness'],
    ['Developer', 'Administrator', 'Enterprise'], 'advanced', ['api', 'integration', 'mcp']),

  a('what-is-the-beta', 'What is the Founding Private Beta™?', 'Beta', 'Getting Started',
    'What is the Founding Private Beta™?',
    'The Founding Private Beta™ is EXECLEAD.AI\'s invitation-only early-access phase where founding members shape the product before General Availability.',
    'Beta members get early access to modules, community, roadmap voting, feedback sessions, and Founding benefits for life.',
    'A founding member votes on the roadmap and joins a feedback session that shapes a new feature.',
    'Co-creates the platform with its first members.',
    'Does not guarantee feature parity with future GA.',
    'Give feedback early — it directly shapes the roadmap.',
    ['Founding Members', 'Beta Feedback Center'],
    ['what-are-founding-members', 'how-to-get-support'],
    ['General User', 'Founder'], 'beginner', ['beta', 'early-access']),

  a('how-to-get-support', 'How do I get support?', 'Support', 'Getting Started',
    'How do I get support?',
    'Search this Executive Knowledge Center™ first, then use the in-app feedback widget or contact EXECLEAD.AI support for account, billing, or enterprise issues.',
    'The Knowledge Center is the single source of truth; Ask EXEC™ can answer most product questions instantly from approved articles.',
    'A member asks EXEC™ "how is readiness calculated?" and gets a grounded answer with sources.',
    'Self-serve first, human support second.',
    'Does not promise instant human responses to all queries.',
    'Check the Knowledge Center before opening a support request.',
    ['Executive Knowledge Center™', 'Feedback Widget'],
    ['what-is-the-beta', 'how-secure-is-my-data'],
    ['General User', 'Enterprise', 'Administrator'], 'beginner', ['support', 'help']),

  a('platform-roadmap', 'What is on the roadmap?', 'Roadmap', 'Release Notes',
    'What is on the roadmap?',
    'EXECLEAD.AI is expanding from Technology Leadership across every executive function, deepening Enterprise Talent Intelligence™, AI simulations, and verified Executive Identity™.',
    'Founding Members vote on roadmap priorities; the platform evolves through governed, evidence-based releases tracked in the Product Command Center.',
    'A founding member votes to prioritize voice interview simulations next quarter.',
    'Evolves with member evidence, not guesswork.',
    'Does not promise specific dates for unreleased features.',
    'Participate in roadmap voting if you\'re a founding member.',
    ['Product Command Center', 'Founding Members'],
    ['execlead-vision', 'what-is-the-beta'],
    ['General User', 'Founder', 'Investor'], 'intermediate', ['roadmap', 'roadmap-voting']),
];

export const ENTERPRISE_FAQ_SLUGS = ['can-enterprises-customize-readiness', 'enterprise-talent-intelligence', 'succession-planning-works', 'how-secure-is-my-data', 'how-is-privacy-handled', 'is-there-an-api'];
export const INVESTOR_FAQ_SLUGS = ['investor-why-now', 'investor-business-model', 'execlead-vision', 'founder-why-built', 'what-is-execlead', 'what-are-founding-members'];
export const MEDIA_FAQ_SLUGS = ['media-what-problem', 'founder-why-built', 'what-is-execlead', 'execlead-mission', 'execlead-vision'];