// Entity catalog — curated from base44/entities/. Purpose inferred from names/schemas.
export const ENTITIES = [
  { name: 'UserProfile', purpose: 'Extended executive profile, target role/company, AI personality', layer: 'Database', usedBy: ['Coach', 'Profile', 'Readiness Engine'], security: 'owner', retention: 'persistent' },
  { name: 'ExecutiveCompetency', purpose: 'Competency scores per executive', layer: 'Database', usedBy: ['Intelligence Center', 'Readiness Engine'], security: 'owner', retention: 'persistent' },
  { name: 'ChallengeResult', purpose: 'Daily executive challenge results and scores', layer: 'Database', usedBy: ['Challenge', 'Analytics', 'Dashboard'], security: 'owner', retention: 'persistent' },
  { name: 'SimulationSession', purpose: 'Executive simulator session records', layer: 'Database', usedBy: ['Simulator', 'Portfolio'], security: 'owner', retention: 'persistent' },
  { name: 'JournalEntry', purpose: 'Reflective leadership journal entries', layer: 'Database', usedBy: ['Journal', 'Portfolio', 'Dashboard'], security: 'owner', retention: 'persistent' },
  { name: 'LessonProgress', purpose: 'Academy lesson completion tracking', layer: 'Database', usedBy: ['Academy', 'Portfolio'], security: 'owner', retention: 'persistent' },
  { name: 'Certificate', purpose: 'Earned executive certificates', layer: 'Database', usedBy: ['Academy', 'Credentials', 'Portfolio'], security: 'owner', retention: 'persistent' },
  { name: 'Achievement', purpose: 'Executive achievements and milestones', layer: 'Database', usedBy: ['Portfolio', 'Dashboard'], security: 'owner', retention: 'persistent' },
  { name: 'JourneyEvent', purpose: 'Career journey timeline events', layer: 'Database', usedBy: ['Journey', 'Journey Orchestrator', 'Portfolio'], security: 'owner', retention: 'persistent' },
  { name: 'ExecutiveOutcome', purpose: 'Observed/predicted executive outcomes with attribution', layer: 'Evidence', usedBy: ['Outcome Intelligence', 'Recommendation Intelligence'], security: 'owner+admin', retention: 'persistent' },
  { name: 'EvidenceItem', purpose: 'Individual evidence items with provenance', layer: 'Evidence', usedBy: ['Evidence Vault', 'Readiness Engine', 'Portfolio'], security: 'owner', retention: 'persistent' },
  { name: 'EvidenceCollection', purpose: 'Grouped evidence collections', layer: 'Evidence', usedBy: ['Evidence Vault'], security: 'owner', retention: 'persistent' },
  { name: 'EvidenceRequest', purpose: 'Requests for evidence from users', layer: 'Evidence', usedBy: ['Evidence Vault', 'Verification'], security: 'owner+admin', retention: 'persistent' },
  { name: 'PortfolioVersion', purpose: 'Versioned executive portfolio snapshots', layer: 'Database', usedBy: ['Portfolio'], security: 'owner', retention: 'persistent' },
  { name: 'ResumeVersion', purpose: 'Versioned resume with extracted data', layer: 'Database', usedBy: ['Resume Intelligence', 'Resume Import', 'Coach'], security: 'owner', retention: 'persistent' },
  { name: 'ResumeImport', purpose: 'Resume upload import records', layer: 'Database', usedBy: ['Resume Import'], security: 'owner', retention: '90 days' },
  { name: 'CareerResume', purpose: 'Career studio resume records', layer: 'Database', usedBy: ['Career Studio'], security: 'owner', retention: 'persistent' },
  { name: 'CareerDocument', purpose: 'Cover letters and career documents', layer: 'Database', usedBy: ['Career Studio'], security: 'owner', retention: 'persistent' },
  { name: 'ExecutiveCredential', purpose: 'Verified leadership credentials', layer: 'Database', usedBy: ['Credentials', 'Passport'], security: 'owner', retention: 'persistent' },
  { name: 'LeadershipDNA', purpose: 'Leadership archetype assessment results', layer: 'Database', usedBy: ['Leadership DNA', 'Portfolio'], security: 'owner', retention: 'persistent' },
  { name: 'ExecutiveLegacy', purpose: 'Leadership philosophy, mission, vision', layer: 'Database', usedBy: ['Executive Legacy'], security: 'owner', retention: 'persistent' },
  { name: 'LegacyCaseStudy', purpose: 'Professional leadership case studies', layer: 'Database', usedBy: ['Legacy Library'], security: 'owner', retention: 'persistent' },
  { name: 'LeadershipLetter', purpose: 'Leadership letters for community review', layer: 'Database', usedBy: ['Legacy Library'], security: 'owner+moderator', retention: 'persistent' },
  { name: 'LaunchQuestion', purpose: 'Launch defense question bank', layer: 'Launch Defense', usedBy: ['Launch Defense Center'], security: 'platform-admin', retention: 'persistent' },
  { name: 'InterviewScenario', purpose: 'Interview scenarios linking questions', layer: 'Launch Defense', usedBy: ['Launch Defense Center'], security: 'platform-admin', retention: 'persistent' },
  { name: 'PracticeSession', purpose: 'Interview practice session records', layer: 'Launch Defense', usedBy: ['Launch Defense Center'], security: 'owner', retention: 'persistent' },
  { name: 'AnswerAttempt', purpose: 'Individual answer attempts with AI scores', layer: 'Launch Defense', usedBy: ['Launch Defense Center'], security: 'owner', retention: 'persistent' },
  { name: 'FounderStory', purpose: 'Founder mission, vision, origin story', layer: 'Launch Defense', usedBy: ['Launch Defense Center'], security: 'owner', retention: 'persistent' },
  { name: 'DecisionScenario', purpose: 'Strategic decision scenarios with options', layer: 'Decision Lab', usedBy: ['Decision Lab'], security: 'platform-admin', retention: 'persistent' },
  { name: 'DecisionAttempt', purpose: 'Decision attempts with AI evaluation', layer: 'Decision Lab', usedBy: ['Decision Lab', 'Decision DNA'], security: 'owner', retention: 'persistent' },
  { name: 'DecisionProfile', purpose: 'Decision DNA archetype profile', layer: 'Decision Lab', usedBy: ['Decision Lab', 'Decision DNA'], security: 'owner', retention: 'persistent' },
  { name: 'ExecutiveDecision', purpose: 'Executive decision records', layer: 'Decision Lab', usedBy: ['Decision Intelligence'], security: 'owner', retention: 'persistent' },
  { name: 'AIPolicyEvent', purpose: 'AI governance policy events', layer: 'Governance', usedBy: ['AI Governance Center'], security: 'admin', retention: 'persistent' },
  { name: 'AIRequestTrace', purpose: 'AI request traces for transparency', layer: 'Governance', usedBy: ['AI Governance', 'AI Observability'], security: 'admin', retention: '180 days' },
  { name: 'ModelRoutingEvent', purpose: 'AI model routing decisions', layer: 'AI Layer', usedBy: ['Model Router Dashboard'], security: 'admin', retention: '90 days' },
  { name: 'AIOptimizationEvent', purpose: 'AI optimization events', layer: 'AI Layer', usedBy: ['AI Optimization'], security: 'admin', retention: '90 days' },
  { name: 'GovernanceRequest', purpose: 'Protected operation governance requests', layer: 'Governance', usedBy: ['Governance Command Center'], security: 'requester+admin', retention: 'persistent' },
  { name: 'GovernanceAuditLog', purpose: 'Immutable governance audit trail', layer: 'Governance', usedBy: ['Governance Command Center', 'Audit Logs'], security: 'immutable', retention: 'permanent' },
  { name: 'GovernanceNotificationLog', purpose: 'Governance notification delivery logs', layer: 'Governance', usedBy: ['Governance Notifications'], security: 'recipient+admin', retention: '180 days' },
  { name: 'GovernanceConfig', purpose: 'Governance policy configuration', layer: 'Governance', usedBy: ['Governance'], security: 'admin', retention: 'persistent' },
  { name: 'GovernanceCertificate', purpose: 'Governance certification records', layer: 'Governance', usedBy: ['Trust Center'], security: 'admin', retention: 'persistent' },
  { name: 'CouncilReview', purpose: 'Council review investigations and decisions', layer: 'Governance', usedBy: ['Executive Council', 'Reputation'], security: 'admin', retention: 'persistent' },
  { name: 'CouncilSession', purpose: 'Council deliberation sessions', layer: 'Governance', usedBy: ['Executive Council'], security: 'owner', retention: 'persistent' },
  { name: 'ReleaseBlocker', purpose: 'Release blocking validation issues', layer: 'Security', usedBy: ['Guardian', 'Remediation Center'], security: 'admin', retention: 'persistent' },
  { name: 'RemediationPatch', purpose: 'Generated remediation patches', layer: 'Security', usedBy: ['Remediation Center'], security: 'admin', retention: 'persistent' },
  { name: 'SelfHealingEvent', purpose: 'Self-healing engine events', layer: 'Security', usedBy: ['Guardian'], security: 'admin', retention: '180 days' },
  { name: 'SecurityIncident', purpose: 'Security incident records', layer: 'Security', usedBy: ['Security Operations'], security: 'admin', retention: 'permanent' },
  { name: 'SecurityEvent', purpose: 'Security telemetry events', layer: 'Security', usedBy: ['Security Center', 'Threat Detection'], security: 'admin', retention: '90 days' },
  { name: 'SecuritySession', purpose: 'Active security sessions', layer: 'Security', usedBy: ['Security Center'], security: 'owner', retention: '30 days' },
  { name: 'TrustedDevice', purpose: 'Trusted device records', layer: 'Security', usedBy: ['Security Center'], security: 'owner', retention: 'persistent' },
  { name: 'PlatformActivity', purpose: 'Platform activity audit log', layer: 'Analytics', usedBy: ['Platform Activity Center', 'Audit Logs'], security: 'immutable', retention: 'permanent' },
  { name: 'UsageLog', purpose: 'AI usage and credit consumption logs', layer: 'Analytics', usedBy: ['AI Usage', 'AI Operations'], security: 'owner+admin', retention: '180 days' },
  { name: 'TelemetryEvent', purpose: 'Product telemetry events', layer: 'Analytics', usedBy: ['Experience Intelligence'], security: 'admin', retention: '90 days' },
  { name: 'ProductCapabilityMetric', purpose: 'Product capability metrics over time', layer: 'Analytics', usedBy: ['Product Command Center'], security: 'admin', retention: 'persistent' },
  { name: 'ProductInsight', purpose: 'AI-generated product insights', layer: 'Analytics', usedBy: ['Product Intelligence'], security: 'admin', retention: 'persistent' },
  { name: 'ProductRelease', purpose: 'Product release records', layer: 'Analytics', usedBy: ['Deployment Center', 'Release Readiness'], security: 'admin', retention: 'persistent' },
  { name: 'FeatureFlag', purpose: 'Feature flags for rollout control', layer: 'Platform', usedBy: ['Feature Flag Center'], security: 'admin', retention: 'persistent' },
  { name: 'FeatureFlagAudit', purpose: 'Feature flag change audit', layer: 'Platform', usedBy: ['Feature Flag Center'], security: 'immutable', retention: 'permanent' },
  { name: 'Feature', purpose: 'Feature catalog and gating config', layer: 'Platform', usedBy: ['Feature Management', 'FeatureGate'], security: 'admin', retention: 'persistent' },
  { name: 'PricingPlan', purpose: 'Subscription plan definitions', layer: 'Commercial', usedBy: ['Pricing', 'Billing', 'Entitlements'], security: 'admin', retention: 'persistent' },
  { name: 'Subscription', purpose: 'User subscription records', layer: 'Commercial', usedBy: ['Billing', 'Entitlements'], security: 'owner', retention: 'persistent' },
  { name: 'SubscriptionAuditLog', purpose: 'Subscription change audit', layer: 'Commercial', usedBy: ['Billing'], security: 'immutable', retention: 'permanent' },
  { name: 'BillingEvent', purpose: 'Billing events', layer: 'Commercial', usedBy: ['Billing', 'Billing Admin'], security: 'owner+admin', retention: 'persistent' },
  { name: 'Invoice', purpose: 'Generated invoices', layer: 'Commercial', usedBy: ['Billing', 'CPQ'], security: 'owner+admin', retention: '7 years' },
  { name: 'PaymentSettings', purpose: 'Payment provider configuration', layer: 'Commercial', usedBy: ['Payment Settings'], security: 'admin', retention: 'persistent' },
  { name: 'CPQQuote', purpose: 'Configure-price-quote records', layer: 'Commercial', usedBy: ['CPQ Wizard', 'CPQ Dashboard'], security: 'owner+admin', retention: 'persistent' },
  { name: 'CPQModule', purpose: 'CPQ module catalog', layer: 'Commercial', usedBy: ['CPQ Wizard'], security: 'admin', retention: 'persistent' },
  { name: 'MarketplaceItem', purpose: 'Marketplace listings', layer: 'Commercial', usedBy: ['Marketplace'], security: 'owner+admin', retention: 'persistent' },
  { name: 'Purchase', purpose: 'Marketplace purchase records', layer: 'Commercial', usedBy: ['Marketplace', 'Wallet'], security: 'owner', retention: 'persistent' },
  { name: 'Organization', purpose: 'Enterprise organizations', layer: 'Enterprise', usedBy: ['Enterprise', 'Enterprise Admin'], security: 'admin', retention: 'persistent' },
  { name: 'OrgMembership', purpose: 'User organization memberships', layer: 'Enterprise', usedBy: ['Enterprise', 'SSO'], security: 'owner+admin', retention: 'persistent' },
  { name: 'Department', purpose: 'Enterprise departments', layer: 'Enterprise', usedBy: ['Enterprise'], security: 'admin', retention: 'persistent' },
  { name: 'Team', purpose: 'Enterprise teams', layer: 'Enterprise', usedBy: ['Enterprise', 'HR'], security: 'admin', retention: 'persistent' },
  { name: 'SuccessionPlan', purpose: 'Succession planning records', layer: 'Enterprise', usedBy: ['Succession Planning', 'HR'], security: 'admin', retention: 'persistent' },
  { name: 'LearningAssignment', purpose: 'Assigned learning to enterprise users', layer: 'Enterprise', usedBy: ['Learning Assignments', 'HR'], security: 'owner+admin', retention: 'persistent' },
  { name: 'SSOConfig', purpose: 'SSO identity provider configuration', layer: 'Enterprise', usedBy: ['SSO Identity'], security: 'admin', retention: 'persistent' },
  { name: 'Company', purpose: 'Company intelligence records', layer: 'Database', usedBy: ['Company Intelligence', 'Company Detail'], security: 'public-read', retention: 'persistent' },
  { name: 'CompanyVersion', purpose: 'Versioned company data', layer: 'Database', usedBy: ['Company Intelligence'], security: 'admin', retention: 'persistent' },
  { name: 'CompanyReport', purpose: 'Company analysis reports', layer: 'Database', usedBy: ['Company Reports Admin'], security: 'admin', retention: 'persistent' },
  { name: 'SavedJob', purpose: 'Saved job opportunities', layer: 'Database', usedBy: ['Career', 'Network Careers'], security: 'owner', retention: 'persistent' },
  { name: 'JobApplication', purpose: 'Job application records', layer: 'Database', usedBy: ['Career', 'Network Careers'], security: 'owner', retention: 'persistent' },
  { name: 'CareerOpportunity', purpose: 'Career opportunity listings', layer: 'Database', usedBy: ['Network Careers'], security: 'public-read', retention: 'persistent' },
  { name: 'NetworkConnection', purpose: 'Executive network connections', layer: 'Community', usedBy: ['Network', 'Portfolio'], security: 'owner', retention: 'persistent' },
  { name: 'NetworkPost', purpose: 'Network feed posts', layer: 'Community', usedBy: ['Network Feed'], security: 'owner', retention: 'persistent' },
  { name: 'NetworkDiscussion', purpose: 'Network discussions', layer: 'Community', usedBy: ['Network Discussions'], security: 'owner', retention: 'persistent' },
  { name: 'NetworkCircle', purpose: 'Network circles/groups', layer: 'Community', usedBy: ['Network Circles'], security: 'owner', retention: 'persistent' },
  { name: 'NetworkBadge', purpose: 'Community badges', layer: 'Community', usedBy: ['Network', 'Reputation'], security: 'admin', retention: 'persistent' },
  { name: 'NetworkEvent', purpose: 'Network events', layer: 'Community', usedBy: ['Network Events'], security: 'owner', retention: 'persistent' },
  { name: 'EventRegistration', purpose: 'Event registrations', layer: 'Community', usedBy: ['Network Events'], security: 'owner', retention: 'persistent' },
  { name: 'CommunityMembership', purpose: 'Community memberships', layer: 'Community', usedBy: ['Community Workspace'], security: 'owner', retention: 'persistent' },
  { name: 'MembershipProgram', purpose: 'Membership program definitions', layer: 'Commercial', usedBy: ['Membership Admin'], security: 'admin', retention: 'persistent' },
  { name: 'UserMembership', purpose: 'User membership records', layer: 'Commercial', usedBy: ['Membership'], security: 'owner', retention: 'persistent' },
  { name: 'MentorProfile', purpose: 'Mentor profiles', layer: 'Community', usedBy: ['Network Mentorship'], security: 'owner', retention: 'persistent' },
  { name: 'PartnershipListing', purpose: 'Partnership marketplace listings', layer: 'Commercial', usedBy: ['Network Partnerships', 'Partner Portal'], security: 'owner', retention: 'persistent' },
  { name: 'ExecutiveReputation', purpose: 'Executive reputation scores', layer: 'Community', usedBy: ['Reputation'], security: 'owner', retention: 'persistent' },
  { name: 'ReputationAuditLog', purpose: 'Reputation change audit', layer: 'Community', usedBy: ['Reputation'], security: 'immutable', retention: 'permanent' },
  { name: 'ReputationAppeal', purpose: 'Reputation score appeals', layer: 'Community', usedBy: ['Reputation'], security: 'owner+admin', retention: 'persistent' },
  { name: 'FoundingMember', purpose: 'Founding member records', layer: 'Commercial', usedBy: ['Founder Portal', 'Founding Member Admin'], security: 'owner+admin', retention: 'permanent' },
  { name: 'FoundingMemberAuditLog', purpose: 'Founding member audit', layer: 'Commercial', usedBy: ['Founding Member Admin'], security: 'immutable', retention: 'permanent' },
  { name: 'FoundingWaitlist', purpose: 'Founding member waitlist', layer: 'Commercial', usedBy: ['Beta Program'], security: 'admin', retention: 'persistent' },
  { name: 'BetaApplication', purpose: 'Beta program applications', layer: 'Commercial', usedBy: ['Beta Apply', 'Admissions'], security: 'applicant+admin', retention: 'persistent' },
  { name: 'BetaCohort', purpose: 'Beta cohort definitions', layer: 'Commercial', usedBy: ['Admissions', 'Beta Program'], security: 'admin', retention: 'persistent' },
  { name: 'BetaInvitation', purpose: 'Beta invitations', layer: 'Commercial', usedBy: ['Admissions'], security: 'admin', retention: 'persistent' },
  { name: 'BetaFeedback', purpose: 'Beta user feedback', layer: 'Commercial', usedBy: ['Beta Operations', 'Feedback'], security: 'owner+admin', retention: 'persistent' },
  { name: 'BetaCommunication', purpose: 'Beta applicant communications', layer: 'Commercial', usedBy: ['Admissions', 'Beta Ops'], security: 'admin', retention: 'persistent' },
  { name: 'ExecutiveWallet', purpose: 'Executive wallet balances', layer: 'Commercial', usedBy: ['Wallet'], security: 'owner', retention: 'persistent' },
  { name: 'WalletTransaction', purpose: 'Wallet transactions', layer: 'Commercial', usedBy: ['Wallet'], security: 'owner', retention: 'permanent' },
  { name: 'WithdrawalRequest', purpose: 'Wallet withdrawal requests', layer: 'Commercial', usedBy: ['Wallet'], security: 'owner+admin', retention: 'persistent' },
  { name: 'Referral', purpose: 'Referral records', layer: 'Commercial', usedBy: ['Referrals'], security: 'owner', retention: 'persistent' },
  { name: 'ReferralTransaction', purpose: 'Referral reward transactions', layer: 'Commercial', usedBy: ['Referrals', 'Wallet'], security: 'owner', retention: 'permanent' },
  { name: 'ReferralReward', purpose: 'Referral reward definitions', layer: 'Commercial', usedBy: ['Referrals'], security: 'admin', retention: 'persistent' },
  { name: 'ReferralSettings', purpose: 'Referral program settings', layer: 'Commercial', usedBy: ['Referrals'], security: 'admin', retention: 'persistent' },
  { name: 'Notification', purpose: 'In-app notifications', layer: 'Platform', usedBy: ['Notifications', 'Concierge'], security: 'owner', retention: '90 days' },
  { name: 'ExecutiveBriefing', purpose: 'Daily executive briefing records', layer: 'Database', usedBy: ['Executive Briefing'], security: 'owner', retention: '90 days' },
  { name: 'PromotionForecast', purpose: 'Promotion readiness forecasts', layer: 'Database', usedBy: ['Promotion Forecast'], security: 'owner', retention: 'persistent' },
  { name: 'ExecutiveAction', purpose: 'Executive action items', layer: 'Database', usedBy: ['Action Center'], security: 'owner', retention: '90 days' },
  { name: 'ExecutiveMemory', purpose: 'AI executive memory state', layer: 'AI Layer', usedBy: ['Concierge', 'Digital Twin'], security: 'owner', retention: 'persistent' },
  { name: 'AIAgentState', purpose: 'AI agent persistent state', layer: 'AI Layer', usedBy: ['Concierge', 'AI Workforce'], security: 'owner', retention: 'persistent' },
  { name: 'ExecutiveInterest', purpose: 'Executive interests/preferences', layer: 'Database', usedBy: ['Profile', 'Concierge'], security: 'owner', retention: 'persistent' },
  { name: 'ExecutiveAffiliation', purpose: 'Executive org affiliations', layer: 'Enterprise', usedBy: ['Enterprise', 'Profile'], security: 'owner', retention: 'persistent' },
  { name: 'IdentityVerification', purpose: 'Identity verification records', layer: 'Security', usedBy: ['Identity Verification', 'Verification'], security: 'owner+admin', retention: 'persistent' },
  { name: 'VerificationLog', purpose: 'Verification audit logs', layer: 'Security', usedBy: ['Verification'], security: 'immutable', retention: 'permanent' },
  { name: 'ExecVerification', purpose: 'EXEC Verified status records', layer: 'Security', usedBy: ['Verification Center'], security: 'owner+admin', retention: 'persistent' },
  { name: 'ExecutiveIdentityTransfer', purpose: 'Identity transfer records', layer: 'Security', usedBy: ['Identity Transfer'], security: 'owner+admin', retention: 'permanent' },
  { name: 'IdentityVersion', purpose: 'Versioned identity snapshots', layer: 'Security', usedBy: ['Identity Graph', 'Identity Transfer'], security: 'owner+admin', retention: 'permanent' },
  { name: 'IdentityProvider', purpose: 'Identity provider configs', layer: 'Security', usedBy: ['SSO', 'Login'], security: 'admin', retention: 'persistent' },
  { name: 'IdentitySyncEvent', purpose: 'Identity sync events', layer: 'Security', usedBy: ['Identity Sync'], security: 'admin', retention: '90 days' },
  { name: 'IdentitySyncStatus', purpose: 'Identity sync status', layer: 'Security', usedBy: ['Identity Sync'], security: 'admin', retention: 'persistent' },
  { name: 'OtpActivityLog', purpose: 'OTP activity logs', layer: 'Security', usedBy: ['Auth', 'Security Center'], security: 'admin', retention: '180 days' },
  { name: 'ExecutiveDigitalTwin', purpose: 'Digital twin config (concept)', layer: 'AI Layer', usedBy: ['Digital Twin'], security: 'owner', retention: 'persistent' },
  { name: 'ConsentRecord', purpose: 'User consent records', layer: 'Security', usedBy: ['Privacy'], security: 'owner', retention: 'permanent' },
  { name: 'DataSubjectRequest', purpose: 'GDPR data subject requests', layer: 'Security', usedBy: ['Privacy'], security: 'owner+admin', retention: 'permanent' },
  { name: 'AccountDeletionRequest', purpose: 'Account deletion requests', layer: 'Security', usedBy: ['Settings', 'Privacy'], security: 'owner+admin', retention: 'permanent' },
  { name: 'DeletionPolicyConfig', purpose: 'Deletion policy configuration', layer: 'Security', usedBy: ['Privacy'], security: 'admin', retention: 'persistent' },
  { name: 'BusinessIntelligenceReport', purpose: 'BI report records', layer: 'Commercial', usedBy: ['Business Intelligence Center'], security: 'admin', retention: 'persistent' },
  { name: 'ScheduledReport', purpose: 'Scheduled report definitions', layer: 'Commercial', usedBy: ['Report Registry'], security: 'admin', retention: 'persistent' },
  { name: 'ReportEvidence', purpose: 'Report supporting evidence', layer: 'Commercial', usedBy: ['Report Registry'], security: 'admin', retention: 'persistent' },
  { name: 'EnterpriseReport', purpose: 'Enterprise report records', layer: 'Enterprise', usedBy: ['Enterprise Reporting'], security: 'admin', retention: 'persistent' },
  { name: 'CommercialTask', purpose: 'Commercial automation tasks', layer: 'Commercial', usedBy: ['Commercial Automation'], security: 'admin', retention: '90 days' },
  { name: 'AutomationRule', purpose: 'Commercial automation rules', layer: 'Commercial', usedBy: ['Commercial Automation'], security: 'admin', retention: 'persistent' },
  { name: 'WorkflowExecutionLog', purpose: 'Workflow execution logs', layer: 'Commercial', usedBy: ['Commercial Automation'], security: 'admin', retention: '180 days' },
  { name: 'ContinuousImprovementAction', purpose: 'Improvement actions', layer: 'Platform', usedBy: ['Platform Improvement Center'], security: 'admin', retention: 'persistent' },
  { name: 'Vendor', purpose: 'Vendor records', layer: 'Enterprise', usedBy: ['Vendor Management', 'Procurement'], security: 'admin', retention: 'persistent' },
  { name: 'ProcurementRequest', purpose: 'Procurement requests', layer: 'Enterprise', usedBy: ['Procurement Command Center'], security: 'admin', retention: 'persistent' },
  { name: 'ArchitectureProposal', purpose: 'Architecture governance proposals', layer: 'Platform', usedBy: ['Architecture Governance'], security: 'admin', retention: 'persistent' },
  { name: 'PerformanceJob', purpose: 'Background performance jobs', layer: 'Platform', usedBy: ['Performance Execution'], security: 'admin', retention: '90 days' },
  { name: 'PlatformStateEvent', purpose: 'Platform state change events', layer: 'Platform', usedBy: ['Platform State', 'Guardian'], security: 'admin', retention: '180 days' },
  { name: 'NewsletterSubscription', purpose: 'Newsletter subscriptions', layer: 'Commercial', usedBy: ['Marketing', 'Landing'], security: 'public', retention: 'persistent' },
  { name: 'EmailEvent', purpose: 'Email delivery events', layer: 'Platform', usedBy: ['Email Settings', 'Admissions'], security: 'admin', retention: '180 days' },
  { name: 'EmailSettings', purpose: 'Email provider settings', layer: 'Platform', usedBy: ['Email Settings'], security: 'admin', retention: 'persistent' },
  { name: 'ProfileView', purpose: 'Public profile view analytics', layer: 'Analytics', usedBy: ['Portfolio', 'Brand Center'], security: 'owner', retention: '180 days' },
  { name: 'ShareEvent', purpose: 'Content share events', layer: 'Analytics', usedBy: ['Brand Center', 'Social'], security: 'owner', retention: '180 days' },
  { name: 'CompanyRequest', purpose: 'Company intelligence requests', layer: 'Database', usedBy: ['Company Admin'], security: 'admin', retention: 'persistent' },
  { name: 'JobSource', purpose: 'Job source configurations', layer: 'Database', usedBy: ['Career', 'Job Application Tools'], security: 'admin', retention: 'persistent' },
  { name: 'Coupon', purpose: 'Discount coupons', layer: 'Commercial', usedBy: ['Billing', 'Pricing'], security: 'admin', retention: 'persistent' },
  { name: 'CPQSeatTier', purpose: 'CPQ seat tier pricing', layer: 'Commercial', usedBy: ['CPQ'], security: 'admin', retention: 'persistent' },
  { name: 'CPQApprovalWorkflow', purpose: 'CPQ approval workflows', layer: 'Commercial', usedBy: ['CPQ'], security: 'admin', retention: 'persistent' },
  { name: 'CPQDiscountRule', purpose: 'CPQ discount rules', layer: 'Commercial', usedBy: ['CPQ'], security: 'admin', retention: 'persistent' },
  { name: 'CPQCurrency', purpose: 'CPQ currency config', layer: 'Commercial', usedBy: ['CPQ'], security: 'admin', retention: 'persistent' },
  { name: 'CPQTaxRule', purpose: 'CPQ tax rules', layer: 'Commercial', usedBy: ['CPQ'], security: 'admin', retention: 'persistent' },
  { name: 'CPQSupportPackage', purpose: 'CPQ support packages', layer: 'Commercial', usedBy: ['CPQ'], security: 'admin', retention: 'persistent' },
  { name: 'CPQAIPackage', purpose: 'CPQ AI add-on packages', layer: 'Commercial', usedBy: ['CPQ'], security: 'admin', retention: 'persistent' },
  { name: 'DemoRequest', purpose: 'Enterprise demo requests', layer: 'Commercial', usedBy: ['Pricing', 'Marketing'], security: 'admin', retention: 'persistent' },
  { name: 'LegacyAuditLog', purpose: 'Legacy audit log (migration)', layer: 'Security', usedBy: ['Audit Logs'], security: 'immutable', retention: 'permanent' },
  { name: 'ScheduledMaintenance', purpose: 'Scheduled maintenance windows', layer: 'Platform', usedBy: ['System Status'], security: 'admin', retention: 'persistent' },
  { name: 'SystemIncident', purpose: 'System incident records', layer: 'Platform', usedBy: ['System Status'], security: 'admin', retention: 'permanent' },
  { name: 'ExecutiveInsight', purpose: 'Thought leadership articles', layer: 'Database', usedBy: ['Articles'], security: 'public-read', retention: 'persistent' },
  { name: 'AITask', purpose: 'AI workforce tasks', layer: 'AI Layer', usedBy: ['AI Workforce'], security: 'owner', retention: '90 days' },
  { name: 'Skill', purpose: 'Skills catalog', layer: 'Database', usedBy: ['Skills', 'Resume'], security: 'owner+admin', retention: 'persistent' },
  { name: 'ELIMKnowledgePack', purpose: 'ELIM framework knowledge packs', layer: 'Platform', usedBy: ['ELIM Management Center'], security: 'platform-admin', retention: 'persistent' },
  { name: 'ExecutiveLegacy', purpose: 'Executive legacy records', layer: 'Database', usedBy: ['Executive Legacy'], security: 'owner', retention: 'persistent' },
  { name: 'FounderTimeCapsule', purpose: 'Founder time capsule entries', layer: 'Commercial', usedBy: ['Founder Portal'], security: 'owner', retention: 'permanent' },
  { name: 'CodeOfConductAcceptance', purpose: 'Code of conduct acceptances', layer: 'Community', usedBy: ['Legacy Library'], security: 'owner', retention: 'permanent' },
  { name: 'LetterComment', purpose: 'Leadership letter comments', layer: 'Community', usedBy: ['Legacy Library'], security: 'owner+moderator', retention: 'persistent' },
  { name: 'LetterInteraction', purpose: 'Leadership letter interactions', layer: 'Community', usedBy: ['Legacy Library'], security: 'owner', retention: '180 days' },
  { name: 'LetterReport', purpose: 'Leadership letter reports', layer: 'Community', usedBy: ['Legacy Library', 'Moderation'], security: 'moderator', retention: 'persistent' },
  { name: 'CommentReaction', purpose: 'Comment reactions', layer: 'Community', usedBy: ['Legacy Library'], security: 'owner', retention: 'persistent' },
  { name: 'CommentAppeal', purpose: 'Comment moderation appeals', layer: 'Community', usedBy: ['Legacy Library'], security: 'owner+moderator', retention: 'persistent' },
  { name: 'JournalEntry', purpose: 'Journal entries (duplicate ref)', layer: 'Database', usedBy: ['Journal'], security: 'owner', retention: 'persistent' },
];