import React from "react";
import { DollarSign, TrendingUp } from "lucide-react";
import { safeParse, formatMetric, getScoreColor } from "@/lib/businessIntelligenceEngine";

export default function ROIWorkflowPanel({ report }) {
  if (!report) return null;

  const workflows = safeParse(report.roi_by_workflow_json, []);
  const attribution = safeParse(report.revenue_attribution_json, []);
  const totalRevenue = report.revenue_generated || 0;

  if (workflows.length === 0) {
    return null;
  }

  const maxRevenue = Math.max(...workflows.map(w => w.revenue_generated), 1);

  return (
    <div>
      <div className="flex items-center gap-2 mb-4">
        <DollarSign size={14} className="text-emerald-400" />
        <h3 className="text-sm font-semibold text-white/80 uppercase tracking-widest">ROI by Commercial Workflow</h3>
        <div className="flex-1 h-px bg-white/5" />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Revenue bars */}
        <div className="bg-white/[0.02] border border-white/5 rounded-lg p-4">
          <div className="text-white/40 text-xs uppercase tracking-widest mb-3">Revenue Generated by Workflow</div>
          <div className="space-y-2.5">
            {workflows.slice(0, 8).map((w) => (
              <div key={w.workflow}>
                <div className="flex items-center justify-between text-xs mb-1">
                  <span className="text-white/60 capitalize">{w.workflow.replace(/_/g, " ")}</span>
                  <span className="text-emerald-400/80 font-medium">{formatMetric(w.revenue_generated, "currency")}</span>
                </div>
                <div className="h-1.5 bg-white/5 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-gradient-to-r from-emerald-500/40 to-emerald-400 rounded-full transition-all"
                    style={{ width: `${(w.revenue_generated / maxRevenue) * 100}%` }}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* ROI metrics table */}
        <div className="bg-white/[0.02] border border-white/5 rounded-lg p-4">
          <div className="text-white/40 text-xs uppercase tracking-widest mb-3">Workflow Performance</div>
          <table className="w-full text-xs">
            <thead>
              <tr className="text-white/30 border-b border-white/5">
                <th className="text-left py-1.5">Workflow</th>
                <th className="text-center py-1.5">Tasks</th>
                <th className="text-center py-1.5">Done</th>
                <th className="text-right py-1.5">ROI</th>
              </tr>
            </thead>
            <tbody>
              {workflows.slice(0, 8).map((w) => (
                <tr key={w.workflow} className="border-b border-white/5">
                  <td className="py-2 text-white/60 capitalize">{w.workflow.replace(/_/g, " ")}</td>
                  <td className="py-2 text-center text-white/40">{w.tasks_created}</td>
                  <td className="py-2 text-center text-white/40">{w.tasks_completed}</td>
                  <td className={`py-2 text-right font-medium ${getScoreColor(w.roi)}`}>{w.roi}%</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Revenue attribution summary */}
      {attribution.length > 0 && (
        <div className="mt-4 flex items-center gap-6 bg-white/[0.02] border border-white/5 rounded-lg p-3">
          <div className="flex items-center gap-2">
            <TrendingUp size={14} className="text-emerald-400" />
            <span className="text-white/40 text-xs">Total Revenue</span>
            <span className="text-emerald-400 text-sm font-bold">{formatMetric(totalRevenue, "currency")}</span>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-white/40 text-xs">Top Workflow</span>
            <span className="text-white/70 text-sm font-medium capitalize">
              {workflows[0]?.workflow.replace(/_/g, " ") || "—"}
            </span>
            <span className="text-emerald-400/60 text-xs">
              ({attribution[0]?.percentage || 0}%)
            </span>
          </div>
        </div>
      )}
    </div>
  );
}