import { useState } from 'react';
import { Loader2, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { PLATFORMS, PILLARS, CONTENT_TYPES, SOURCE_TYPES, PLATFORM_LABELS } from '@/lib/socialContentConfig';
const initial={platform:'linkedin',pillar:PILLARS[0],contentType:'Quick Post',sourceType:'leadership_topic',topic:'',instruction:'',voice:'company',mediaFile:null};
export default function CreatePostForm({ onGenerate, busy }) {
  const [form,setForm]=useState(initial); const set=(key,value)=>setForm(current=>({...current,[key]:value}));
  const Select=({label,value,onChange,children})=><label className="space-y-1.5 text-xs font-medium text-foreground"><span>{label}</span><select value={value} onChange={onChange} className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm">{children}</select></label>;
  return <form onSubmit={e=>{e.preventDefault();onGenerate(form);}} className="grid gap-5 rounded-2xl border border-border bg-card p-5"><div className="grid gap-4 md:grid-cols-3"><Select label="1. Platform" value={form.platform} onChange={e=>set('platform',e.target.value)}>{PLATFORMS.map(v=><option key={v} value={v}>{PLATFORM_LABELS[v]}</option>)}</Select><Select label="2. Content Pillar" value={form.pillar} onChange={e=>set('pillar',e.target.value)}>{PILLARS.map(v=><option key={v}>{v}</option>)}</Select><Select label="3. Content Type" value={form.contentType} onChange={e=>set('contentType',e.target.value)}>{CONTENT_TYPES.map(v=><option key={v}>{v}</option>)}</Select></div><div className="grid gap-4 md:grid-cols-2"><Select label="4. Source Material" value={form.sourceType} onChange={e=>set('sourceType',e.target.value)}>{SOURCE_TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select><Select label="Voice" value={form.voice} onChange={e=>set('voice',e.target.value)}><option value="company">Company Voice</option><option value="founder">Founder Voice</option></Select></div><label className="space-y-1.5 text-xs font-medium"><span>Topic</span><Input required value={form.topic} onChange={e=>set('topic',e.target.value)} placeholder="Why executive readiness is more than management experience"/></label><label className="space-y-1.5 text-xs font-medium"><span>5. Ask EXEC™ (optional instruction)</span><Textarea value={form.instruction} onChange={e=>set('instruction',e.target.value)} placeholder="Create today's LinkedIn post, turn this milestone into an announcement, or add a specific angle."/></label><label className="space-y-1.5 text-xs font-medium"><span>Media asset (optional)</span><Input type="file" accept="image/*,video/*" onChange={e=>set('mediaFile',e.target.files?.[0]||null)}/></label><Button disabled={busy} className="w-full md:w-fit">{busy?<Loader2 className="animate-spin"/>:<Sparkles/>}Generate Governed Draft</Button></form>;
}