import React from "react";
import { useSubscription } from "@/lib/SubscriptionContext";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { Swords, Brain, MessageSquare, GraduationCap, Scale, PenLine, FileText, Zap, Compass, TrendingUp } from "lucide-react";
import DashboardModeBanner from "@/components/dashboard/DashboardModeBanner";
import ExecutiveHealth from "@/components/dashboard/ExecutiveHealth";
import ExecutiveMomentum from "@/components/dashboard/ExecutiveMomentum";
import { useWorkspace } from "@/lib/WorkspaceContext";
import ExecutiveStatusBar from "@/components/shared/ExecutiveStatusBar";
import SummaryCard from "@/components/shared/SummaryCard";
import NextBestActionCard from "@/components/shared/NextBestActionCard";

const QUICK_ACTIONS = [
  { path: "/challenge", label: "Challenge", desc: "Test readiness", icon: Swords, color: "from-indigo-600 to-violet-600" },
  { path: "/simulator", label: "Simulator", desc: "Run a scenario", icon: Brain, color: "from-cyan-600 to-blue-600" },
  { path: "/debate", label: "Debate", desc: "Defend a position", icon: Scale, color: "from-red-600 to-orange-600" },
  { path: "/coach", label: "AI Coach", desc: "Get coached 24/7", icon: MessageSquare, color: "from-emerald-600 to-teal-600" },
  { path: "/academy", label: "Academy", desc: "Daily lessons", icon: GraduationCap, color: "from-amber-600 to-orange-600" },
  { path: "/journal", label: "Journal", desc: "Reflect & track", icon: PenLine, color: "from-pink-600 to-rose-600" },
];

export default function Dashboard() {
  const { profile, loading: loadingProfile } = useSubscription();
  const { activeWorkspace } = useWorkspace();

  if (loadingProfile || !profile) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="w-6 h-6 border-2 border-indigo-400/30 border-t-indigo-400 rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Executive Status Bar™ — consistent across all executive pages */}
      <ExecutiveStatusBar />

      <DashboardModeBanner profile={profile} activeWorkspace={activeWorkspace} />

      {/* Executive Snapshot — "How am I doing?" */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <ExecutiveHealth profile={profile} />
        <ExecutiveMomentum profile={profile} />
      </div>

      {/* One Next Best Action™ — generated by Journey Orchestrator™ */}
      <NextBestActionCard />

      {/* Summary Cards — deep links, not duplicated content */}
      <div>
        <h2 className="text-sm font-medium text-white/40 uppercase tracking-wider mb-4">Executive Intelligence</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <SummaryCard title="Executive Briefing™" message="What changed this week" path="/executive-briefing" icon={FileText} accent="indigo" />
          <SummaryCard title="Action Center™" message="What should I do today" path="/action-center" icon={Zap} accent="amber" />
          <SummaryCard title="Promotion Forecast™" message="Am I ready for promotion" path="/promotion-forecast" icon={TrendingUp} accent="emerald" />
          <SummaryCard title="Journey Orchestrator™" message="My long-term leadership journey" path="/journey-orchestrator" icon={Compass} accent="violet" />
        </div>
      </div>

      {/* Quick Actions */}
      <div>
        <h2 className="text-sm font-medium text-white/40 uppercase tracking-wider mb-4">Quick Actions</h2>
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">
          {QUICK_ACTIONS.map((action, i) => (
            <motion.div key={action.path} initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.04 }}>
              <Link to={action.path} className="block group bg-white/[0.02] hover:bg-white/[0.05] border border-white/5 hover:border-white/10 rounded-xl p-4 transition-all duration-300">
                <div className={`w-9 h-9 rounded-lg bg-gradient-to-br ${action.color} flex items-center justify-center mb-3`}>
                  <action.icon size={16} className="text-white" />
                </div>
                <h3 className="text-white font-semibold text-sm mb-0.5 group-hover:text-indigo-400 transition-colors">{action.label}</h3>
                <p className="text-white/30 text-xs">{action.desc}</p>
              </Link>
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  );
}