/**
 * Company Registry™ — Master Registry v1.0
 * ============================================================
 * Centralized company database powering Company Intelligence™,
 * Executive Coach™, Resume Intelligence™, and Career Studio™.
 *
 * Future: API-backed, 10,000+ companies, bulk import/export.
 */
export const COMPANY_REGISTRY_VERSION = "1.0.0";

export const COMPANIES = [
  {
    id: "microsoft",
    name: "Microsoft",
    logo: "🔷",
    industry: "Technology",
    country: "United States",
    headquarters: "Redmond, Washington, USA",
    employee_size: "220,000+",
    fortune_ranking: 13,
    technology: ["Azure", "Microsoft 365", "Dynamics 365", "GitHub", "LinkedIn"],
    leadership_style: "Growth Mindset • Collaborative • Data-driven",
    interview_style: "Behavioral • System Design • Leadership Principles",
    executive_competencies: ["Cloud Strategy", "Enterprise Sales", "Partner Ecosystem", "Digital Transformation"],
    promotion_expectations: "Demonstrated impact across org boundaries, growth mindset, customer obsession",
    company_intelligence_available: true,
    recommended_certifications: ["Azure Solutions Architect", "Microsoft Certified: Executive", "PMP"],
    recommended_learning_paths: ["Cloud Leadership", "Enterprise Architecture", "Digital Transformation"],
  },
  {
    id: "amazon",
    name: "Amazon",
    logo: "📦",
    industry: "Technology",
    country: "United States",
    headquarters: "Seattle, Washington, USA",
    employee_size: "1,500,000+",
    fortune_ranking: 2,
    technology: ["AWS", "Amazon Retail", "Alexa", "Prime", "Logistics"],
    leadership_style: "Customer Obsession • Bias for Action • Ownership",
    interview_style: "Leadership Principles • STAR • Bar Raiser",
    executive_competencies: ["Customer Obsession", "Operational Excellence", "Scale Leadership", "Invent & Simplify"],
    promotion_expectations: "Deep dive, deliver results, think big, earn trust across teams",
    company_intelligence_available: true,
    recommended_certifications: ["AWS Solutions Architect Professional", "AWS Cloud Practitioner", "PMP"],
    recommended_learning_paths: ["Cloud Architecture", "Operations Leadership", "Product Management"],
  },
  {
    id: "google",
    name: "Google",
    logo: "🔍",
    industry: "Technology",
    country: "United States",
    headquarters: "Mountain View, California, USA",
    employee_size: "180,000+",
    fortune_ranking: 8,
    technology: ["Google Cloud", "Search", "Android", "Workspace", "AI/ML"],
    leadership_style: "Innovation-first • Data-driven • Collaborative",
    interview_style: "Algorithmic • System Design • Googliness",
    executive_competencies: ["Technical Vision", "Innovation Leadership", "Scale Management", "AI Strategy"],
    promotion_expectations: "Impact, leadership, complexity handling, cross-functional influence",
    company_intelligence_available: true,
    recommended_certifications: ["Google Cloud Professional Architect", "PMP", "Google Project Management"],
    recommended_learning_paths: ["AI/ML Leadership", "Cloud Architecture", "Product Strategy"],
  },
  {
    id: "apple",
    name: "Apple",
    logo: "🍎",
    industry: "Technology",
    country: "United States",
    headquarters: "Cupertino, California, USA",
    employee_size: "160,000+",
    fortune_ranking: 7,
    technology: ["iOS", "macOS", "iCloud", "Apple Silicon", "Services"],
    leadership_style: "Perfectionism • Design-first • Secrecy • Excellence",
    interview_style: "Behavioral • Technical Depth • Design Thinking",
    executive_competencies: ["Design Leadership", "Product Excellence", "Supply Chain", "Privacy Strategy"],
    promotion_expectations: "Excellence in execution, cross-functional collaboration, innovation",
    company_intelligence_available: true,
    recommended_certifications: ["Apple Certified IT Professional", "PMP", "ITIL"],
    recommended_learning_paths: ["Product Design Leadership", "Hardware Engineering", "Services Strategy"],
  },
  {
    id: "meta",
    name: "Meta",
    logo: "🌐",
    industry: "Technology",
    country: "United States",
    headquarters: "Menlo Park, California, USA",
    employee_size: "67,000+",
    fortune_ranking: 22,
    technology: ["Meta Platforms", "AI Research", "Reality Labs", "Instagram", "WhatsApp"],
    leadership_style: "Move Fast • Build Social Value • Long-term Vision",
    interview_style: "Behavioral • System Design • Leadership",
    executive_competencies: ["Social Impact", "AI/ML Strategy", "Metaverse Vision", "Scale Leadership"],
    promotion_expectations: "Impact, people leadership, technical depth, cross-team collaboration",
    company_intelligence_available: true,
    recommended_certifications: ["Meta Blueprint", "AWS Solutions Architect", "PMP"],
    recommended_learning_paths: ["AI Research Leadership", "Social Platform Strategy", "AR/VR Product"],
  },
  {
    id: "openai",
    name: "OpenAI",
    logo: "🤖",
    industry: "Technology",
    country: "United States",
    headquarters: "San Francisco, California, USA",
    employee_size: "2,000+",
    fortune_ranking: null,
    technology: ["GPT", "DALL-E", "ChatGPT", "API Platform", "Sora"],
    leadership_style: "Mission-driven • Research Excellence • Safety-first",
    interview_style: "Research Depth • Engineering Excellence • Alignment",
    executive_competencies: ["AI Strategy", "Research Leadership", "Safety & Alignment", "Product AI"],
    promotion_expectations: "Research impact, safety contributions, product innovation, mission alignment",
    company_intelligence_available: true,
    recommended_certifications: ["AI/ML Specialization", "Cloud AI", "PMP"],
    recommended_learning_paths: ["AI Research", "AI Product Management", "AI Safety"],
  },
  {
    id: "servicenow",
    name: "ServiceNow",
    logo: "⚡",
    industry: "Technology",
    country: "United States",
    headquarters: "Santa Clara, California, USA",
    employee_size: "22,000+",
    fortune_ranking: 90,
    technology: ["Now Platform", "ITSM", "ITOM", "CSM", "HRSD"],
    leadership_style: "Customer-centric • Platform-first • Innovation",
    interview_style: "Behavioral • Platform Knowledge • Leadership",
    executive_competencies: ["Platform Strategy", "Workflow Automation", "Enterprise Sales", "Customer Success"],
    promotion_expectations: "Platform expertise, customer impact, team leadership, innovation",
    company_intelligence_available: true,
    recommended_certifications: ["ServiceNow Certified System Administrator", "ServiceNow Implementation", "ITIL"],
    recommended_learning_paths: ["Platform Architecture", "IT Service Management", "Workflow Automation"],
  },
  {
    id: "oracle",
    name: "Oracle",
    logo: "🔴",
    industry: "Technology",
    country: "United States",
    headquarters: "Austin, Texas, USA",
    employee_size: "164,000+",
    fortune_ranking: 104,
    technology: ["Oracle Cloud", "Database", "ERP", "NetSuite", "Java"],
    leadership_style: "Sales-driven • Competitive • Enterprise-focused",
    interview_style: "Technical • Behavioral • Sales Acumen",
    executive_competencies: ["Database Strategy", "Cloud Migration", "Enterprise Sales", "ERP Leadership"],
    promotion_expectations: "Sales performance, technical depth, customer relationships, leadership",
    company_intelligence_available: true,
    recommended_certifications: ["Oracle Cloud Infrastructure", "Oracle Database", "PMP"],
    recommended_learning_paths: ["Cloud Architecture", "Database Administration", "ERP Implementation"],
  },
  {
    id: "salesforce",
    name: "Salesforce",
    logo: "☁️",
    industry: "Technology",
    country: "United States",
    headquarters: "San Francisco, California, USA",
    employee_size: "73,000+",
    fortune_ranking: 98,
    technology: ["Sales Cloud", "Service Cloud", "Marketing Cloud", "MuleSoft", "Tableau"],
    leadership_style: "Ohana Culture • Stakeholder Success • Trailblazer",
    interview_style: "Behavioral • Platform Knowledge • Trailhead",
    executive_competencies: ["CRM Strategy", "Cloud Sales", "Customer Success", "Stakeholder Management"],
    promotion_expectations: "Platform expertise, customer success, team leadership, Ohana values",
    company_intelligence_available: true,
    recommended_certifications: ["Salesforce Administrator", "Salesforce Platform App Builder", "PMP"],
    recommended_learning_paths: ["CRM Architecture", "Cloud Sales Leadership", "Customer Success"],
  },
  {
    id: "ibm",
    name: "IBM",
    logo: "🔷",
    industry: "Technology",
    country: "United States",
    headquarters: "Armonk, New York, USA",
    employee_size: "282,000+",
    fortune_ranking: 168,
    technology: ["IBM Cloud", "Watson", "Red Hat", "Consulting", "Quantum"],
    leadership_style: "Consultative • Research-driven • Enterprise",
    interview_style: "Behavioral • Technical Depth • Consulting Case",
    executive_competencies: ["Hybrid Cloud", "AI/Watson", "Consulting Leadership", "Quantum Strategy"],
    promotion_expectations: "Consulting excellence, technical leadership, client relationships, innovation",
    company_intelligence_available: true,
    recommended_certifications: ["IBM Cloud Architect", "Red Hat Certified Engineer", "PMP"],
    recommended_learning_paths: ["Hybrid Cloud Architecture", "AI/Watson", "Consulting Excellence"],
  },
  {
    id: "accenture",
    name: "Accenture",
    logo: "▶️",
    industry: "Consulting",
    country: "Ireland",
    headquarters: "Dublin, Ireland",
    employee_size: "733,000+",
    fortune_ranking: 175,
    technology: ["Accenture Cloud", "Synops", "MyNav", "AI", "Blockchain"],
    leadership_style: "Consultative • Client-first • Innovation",
    interview_style: "Case Study • Behavioral • Leadership",
    executive_competencies: ["Consulting Leadership", "Digital Transformation", "Client Management", "Delivery Excellence"],
    promotion_expectations: "Client impact, team building, practice growth, innovation",
    company_intelligence_available: true,
    recommended_certifications: ["PMP", "ITIL", "TOGAF", "Accenture Certification"],
    recommended_learning_paths: ["Consulting Excellence", "Digital Transformation", "Cloud Strategy"],
  },
  {
    id: "deloitte",
    name: "Deloitte",
    logo: "💚",
    industry: "Consulting",
    country: "United Kingdom",
    headquarters: "London, United Kingdom",
    employee_size: "457,000+",
    fortune_ranking: 19,
    technology: ["Deloitte Digital", "Cloud", "AI", "Analytics", "Risk"],
    leadership_style: "Professional • Collaborative • Excellence",
    interview_style: "Case Study • Behavioral • Technical",
    executive_competencies: ["Advisory Leadership", "Risk Management", "Digital Strategy", "Audit Excellence"],
    promotion_expectations: "Client excellence, team leadership, practice growth, thought leadership",
    company_intelligence_available: true,
    recommended_certifications: ["CPA", "PMP", "CISA", "CISSP"],
    recommended_learning_paths: ["Advisory Excellence", "Risk & Compliance", "Digital Transformation"],
  },
  {
    id: "ey",
    name: "EY",
    logo: "💛",
    industry: "Consulting",
    country: "United Kingdom",
    headquarters: "London, United Kingdom",
    employee_size: "395,000+",
    fortune_ranking: 185,
    technology: ["EY Cloud", "AI", "Blockchain", "Analytics", "Risk"],
    leadership_style: "Building a Better Working World • Collaborative",
    interview_style: "Case Study • Behavioral • Technical",
    executive_competencies: ["Advisory Leadership", "Audit Excellence", "Tax Strategy", "Consulting"],
    promotion_expectations: "Client excellence, team building, practice growth, innovation",
    company_intelligence_available: true,
    recommended_certifications: ["CPA", "PMP", "CISA", "CISSP"],
    recommended_learning_paths: ["Advisory Excellence", "Tax Strategy", "Digital Transformation"],
  },
  {
    id: "pwc",
    name: "PwC",
    logo: "🟠",
    industry: "Consulting",
    country: "United Kingdom",
    headquarters: "London, United Kingdom",
    employee_size: "364,000+",
    fortune_ranking: 158,
    technology: ["PwC Cloud", "AI", "Blockchain", "Analytics", "Risk"],
    leadership_style: "Purpose-led • Collaborative • Excellence",
    interview_style: "Case Study • Behavioral • Technical",
    executive_competencies: ["Advisory Leadership", "Audit Excellence", "Tax Strategy", "Consulting"],
    promotion_expectations: "Client impact, team leadership, practice growth, purpose-driven",
    company_intelligence_available: true,
    recommended_certifications: ["CPA", "PMP", "CISA", "CISSP"],
    recommended_learning_paths: ["Advisory Excellence", "Tax Strategy", "Digital Transformation"],
  },
  {
    id: "kpmg",
    name: "KPMG",
    logo: "🔵",
    industry: "Consulting",
    country: "Netherlands",
    headquarters: "Amstelveen, Netherlands",
    employee_size: "273,000+",
    fortune_ranking: 187,
    technology: ["KPMG Cloud", "AI", "Blockchain", "Analytics", "Risk"],
    leadership_style: "Collaborative • Integrity • Excellence",
    interview_style: "Case Study • Behavioral • Technical",
    executive_competencies: ["Advisory Leadership", "Audit Excellence", "Tax Strategy", "Consulting"],
    promotion_expectations: "Client excellence, team building, practice growth, integrity",
    company_intelligence_available: true,
    recommended_certifications: ["CPA", "PMP", "CISA", "CISSP"],
    recommended_learning_paths: ["Advisory Excellence", "Tax Strategy", "Digital Transformation"],
  },
  {
    id: "capgemini",
    name: "Capgemini",
    logo: "💎",
    industry: "Consulting",
    country: "France",
    headquarters: "Paris, France",
    employee_size: "340,000+",
    fortune_ranking: 285,
    technology: ["Capgemini Cloud", "AI", "Engineering", "Digital", "R&D"],
    leadership_style: "Collaborative • Innovation • Client-centric",
    interview_style: "Case Study • Behavioral • Technical",
    executive_competencies: ["Engineering Leadership", "Digital Transformation", "Cloud Strategy", "Consulting"],
    promotion_expectations: "Client impact, team leadership, innovation, delivery excellence",
    company_intelligence_available: true,
    recommended_certifications: ["PMP", "TOGAF", "ITIL", "Cloud Certified"],
    recommended_learning_paths: ["Engineering Excellence", "Digital Transformation", "Cloud Strategy"],
  },
  {
    id: "fujitsu",
    name: "Fujitsu",
    logo: "🔴",
    industry: "Technology",
    country: "Japan",
    headquarters: "Tokyo, Japan",
    employee_size: "124,000+",
    fortune_ranking: 244,
    technology: ["Fujitsu Cloud", "Computing", "AI", "5G", "Quantum"],
    leadership_style: "Japanese Management • Consensus • Long-term",
    interview_style: "Behavioral • Technical • Cultural Fit",
    executive_competencies: ["Hardware Strategy", "Cloud Migration", "AI Leadership", "Global Operations"],
    promotion_expectations: "Technical excellence, consensus building, long-term thinking, client dedication",
    company_intelligence_available: true,
    recommended_certifications: ["Fujitsu Certified", "PMP", "ITIL", "Cloud Certified"],
    recommended_learning_paths: ["Cloud Architecture", "AI/ML", "Global Operations"],
  },
  {
    id: "ntt_data",
    name: "NTT DATA",
    logo: "🔵",
    industry: "Technology",
    country: "Japan",
    headquarters: "Tokyo, Japan",
    employee_size: "190,000+",
    fortune_ranking: 312,
    technology: ["NTT Cloud", "AI", "Blockchain", "IoT", "Consulting"],
    leadership_style: "Japanese Management • Client-first • Innovation",
    interview_style: "Behavioral • Technical • Cultural Fit",
    executive_competencies: ["IT Services Leadership", "Cloud Strategy", "Digital Transformation", "Consulting"],
    promotion_expectations: "Client excellence, technical leadership, team building, innovation",
    company_intelligence_available: true,
    recommended_certifications: ["PMP", "ITIL", "TOGAF", "Cloud Certified"],
    recommended_learning_paths: ["IT Services Excellence", "Cloud Strategy", "Digital Transformation"],
  },
  {
    id: "dxc technology",
    name: "DXC Technology",
    logo: "🟣",
    industry: "Technology",
    country: "United States",
    headquarters: "Ashburn, Virginia, USA",
    employee_size: "130,000+",
    fortune_ranking: 185,
    technology: ["DXC Cloud", "IT Services", "Analytics", "Security", "Consulting"],
    leadership_style: "Client-centric • Delivery Excellence • Innovation",
    interview_style: "Behavioral • Technical • Leadership",
    executive_competencies: ["IT Services Leadership", "Cloud Migration", "Security Strategy", "Consulting"],
    promotion_expectations: "Client impact, delivery excellence, team leadership, innovation",
    company_intelligence_available: true,
    recommended_certifications: ["PMP", "ITIL", "TOGAF", "CISSP"],
    recommended_learning_paths: ["IT Services Excellence", "Cloud Strategy", "Security Leadership"],
  },
  {
    id: "government of alberta",
    name: "Government of Alberta",
    logo: "🏛️",
    industry: "Government",
    country: "Canada",
    headquarters: "Edmonton, Alberta, Canada",
    employee_size: "27,000+",
    fortune_ranking: null,
    technology: ["Azure", "Oracle", "SAP", "ServiceNow", "Custom"],
    leadership_style: "Public Service • Accountability • Transparency",
    interview_style: "Behavioral • Competency-based • Security Clearance",
    executive_competencies: ["Public Sector Leadership", "Digital Government", "Policy Implementation", "Fiscal Management"],
    promotion_expectations: "Public service excellence, policy leadership, fiscal responsibility, transparency",
    company_intelligence_available: true,
    recommended_certifications: ["PMP", "ITIL", "Security Clearance", "Public Sector Certification"],
    recommended_learning_paths: ["Public Sector Leadership", "Digital Government", "Policy Implementation"],
  },
];

/** Search companies by name, industry, country, or technology. */
export function searchCompanies(query, limit = 10) {
  if (!query || !query.trim()) return COMPANIES.slice(0, limit);
  const q = query.toLowerCase().trim();
  return COMPANIES.filter(c =>
    c.name.toLowerCase().includes(q) ||
    c.industry.toLowerCase().includes(q) ||
    c.country.toLowerCase().includes(q) ||
    c.technology.some(t => t.toLowerCase().includes(q))
  ).slice(0, limit);
}

export function getCompanyById(id) {
  return COMPANIES.find(c => c.id === id);
}

export function getCompanyByName(name) {
  if (!name) return null;
  return COMPANIES.find(c => c.name.toLowerCase() === name.toLowerCase());
}