/**
 * Role Registry™ — Master Registry v1.0
 * ============================================================
 * Centralized executive role database powering Executive Coach™,
 * Leadership DNA™, Executive Journey™, and Resume Intelligence™.
 */
export const ROLE_REGISTRY_VERSION = "1.0.0";

export const ROLES = [
  {
    id: "ceo",
    title: "Chief Executive Officer",
    executive_level: "C-Suite",
    leadership_level: 5,
    job_family: "Executive Leadership",
    career_track: "Executive",
    competencies: ["Strategic Vision", "Board Relations", "P&L Management", "Stakeholder Management", "Crisis Leadership"],
    leadership_behaviors: ["Sets Vision", "Builds Culture", "Drives Results", "Develops Leaders"],
    executive_skills: ["Strategic Planning", "Financial Acumen", "Public Speaking", "Negotiation"],
    recommended_certifications: ["Executive MBA", "Board Governance", "Harvard Executive Program"],
    recommended_courses: ["CEO Excellence", "Board Leadership", "Strategic Management"],
    recommended_books: ["The CEO Next Door", "What Got You Here Won't Get You There", "Good to Great"],
    promotion_path: "COO → President → CEO → Board Chair",
    salary_benchmark_ref: "ceo",
    ai_persona_mapping: "strategic_visionary",
  },
  {
    id: "cto",
    title: "Chief Technology Officer",
    executive_level: "C-Suite",
    leadership_level: 5,
    job_family: "Technology",
    career_track: "Executive",
    competencies: ["Technology Strategy", "Innovation Leadership", "Engineering Excellence", "Cloud Architecture", "Team Building"],
    leadership_behaviors: ["Technology Vision", "Engineering Culture", "Innovation Driver", "Talent Magnet"],
    executive_skills: ["Architecture", "Technical Strategy", "Vendor Management", "Team Scaling"],
    recommended_certifications: ["AWS Solutions Architect Professional", "TOGAF", "CISSP"],
    recommended_courses: ["Technology Leadership", "Cloud Architecture", "Engineering Management"],
    recommended_books: ["The Lean Startup", "Accelerate", "Staff Engineer"],
    promotion_path: "VP Engineering → SVP Engineering → CTO",
    salary_benchmark_ref: "cto",
    ai_persona_mapping: "technology_visionary",
  },
  {
    id: "cio",
    title: "Chief Information Officer",
    executive_level: "C-Suite",
    leadership_level: 5,
    job_family: "Information Technology",
    career_track: "Executive",
    competencies: ["IT Strategy", "Digital Transformation", "Vendor Management", "Cybersecurity", "Change Management"],
    leadership_behaviors: ["Digital Vision", "Operational Excellence", "Risk Management", "Business Alignment"],
    executive_skills: ["IT Operations", "Budget Management", "Stakeholder Engagement", "Program Management"],
    recommended_certifications: ["ITIL Expert", "CISM", "CGEIT", "PMP"],
    recommended_courses: ["Digital Transformation", "IT Leadership", "Cybersecurity Strategy"],
    recommended_books: ["The CIO Paradox", "Leading Digital", "The Phoenix Project"],
    promotion_path: "IT Director → VP IT → CIO",
    salary_benchmark_ref: "cio",
    ai_persona_mapping: "digital_transformation_leader",
  },
  {
    id: "cdo",
    title: "Chief Digital Officer",
    executive_level: "C-Suite",
    leadership_level: 5,
    job_family: "Digital Transformation",
    career_track: "Executive",
    competencies: ["Digital Strategy", "Innovation", "Data Analytics", "Customer Experience", "Agile Leadership"],
    leadership_behaviors: ["Digital Vision", "Innovation Driver", "Customer Champion", "Change Agent"],
    executive_skills: ["Digital Product", "Data Strategy", "Agile/DevOps", "Design Thinking"],
    recommended_certifications: ["Digital Transformation", "PMP", "Agile/Scrum"],
    recommended_courses: ["Digital Strategy", "Design Thinking", "Data Analytics"],
    recommended_books: ["Leading Digital", "The Digital Matrix", "Digital Transformation"],
    promotion_path: "Digital Director → VP Digital → CDO",
    salary_benchmark_ref: "cdo",
    ai_persona_mapping: "digital_innovator",
  },
  {
    id: "coo",
    title: "Chief Operations Officer",
    executive_level: "C-Suite",
    leadership_level: 5,
    job_family: "Operations",
    career_track: "Executive",
    competencies: ["Operational Excellence", "Process Optimization", "Supply Chain", "Quality Management", "Team Leadership"],
    leadership_behaviors: ["Operational Discipline", "Efficiency Driver", "Cross-functional Leader", "Results Oriented"],
    executive_skills: ["Operations Management", "Lean/Six Sigma", "Budget Management", "Program Management"],
    recommended_certifications: ["Six Sigma Black Belt", "PMP", "APICS CSCP"],
    recommended_courses: ["Operations Excellence", "Lean Management", "Supply Chain Strategy"],
    recommended_books: ["The Goal", "Lean Thinking", "Good to Great"],
    promotion_path: "Operations Director → VP Operations → COO → CEO",
    salary_benchmark_ref: "coo",
    ai_persona_mapping: "operational_excellence",
  },
  {
    id: "vp",
    title: "Vice President",
    executive_level: "VP",
    leadership_level: 4,
    job_family: "Executive Leadership",
    career_track: "Executive",
    competencies: ["Strategic Planning", "Team Leadership", "P&L Management", "Cross-functional Collaboration", "Executive Communication"],
    leadership_behaviors: ["Strategic Thinker", "Team Builder", "Stakeholder Manager", "Results Driver"],
    executive_skills: ["Strategy", "Budget Management", "Presentation", "Negotiation"],
    recommended_certifications: ["MBA", "PMP", "Executive Education"],
    recommended_courses: ["Leadership Excellence", "Strategic Management", "Executive Communication"],
    recommended_books: ["The 7 Habits of Highly Effective People", "Good to Great", "Multipliers"],
    promotion_path: "Director → Senior Director → VP → SVP → EVP",
    salary_benchmark_ref: "vp",
    ai_persona_mapping: "strategic_leader",
  },
  {
    id: "director",
    title: "Director",
    executive_level: "Director",
    leadership_level: 3,
    job_family: "Management",
    career_track: "Management",
    competencies: ["Department Leadership", "Strategic Execution", "Team Development", "Budget Management", "Stakeholder Management"],
    leadership_behaviors: ["Execution Focused", "Team Developer", "Collaborative Leader", "Accountable"],
    executive_skills: ["Project Management", "Financial Planning", "Communication", "Problem Solving"],
    recommended_certifications: ["PMP", "ITIL", "Six Sigma Green Belt"],
    recommended_courses: ["Management Excellence", "Leadership Foundations", "Strategic Execution"],
    recommended_books: ["The Five Dysfunctions of a Team", "Radical Candor", "Dare to Lead"],
    promotion_path: "Manager → Senior Manager → Director → Senior Director → VP",
    salary_benchmark_ref: "director",
    ai_persona_mapping: "execution_leader",
  },
  {
    id: "senior_director",
    title: "Senior Director",
    executive_level: "Senior Director",
    leadership_level: 3,
    job_family: "Management",
    career_track: "Management",
    competencies: ["Multi-team Leadership", "Strategic Planning", "Organizational Design", "Executive Influence", "Change Leadership"],
    leadership_behaviors: ["Strategic Executor", "Organization Builder", "Influencer", "Mentor"],
    executive_skills: ["Strategy", "Organizational Design", "Executive Presence", "Financial Acumen"],
    recommended_certifications: ["PMP", "MBA", "Executive Education"],
    recommended_courses: ["Senior Leadership", "Organizational Design", "Executive Presence"],
    recommended_books: ["The Leadership Challenge", "Good to Great", "The First 90 Days"],
    promotion_path: "Director → Senior Director → VP → SVP",
    salary_benchmark_ref: "senior_director",
    ai_persona_mapping: "senior_execution_leader",
  },
  {
    id: "senior_manager",
    title: "Senior Manager",
    executive_level: "Manager",
    leadership_level: 2,
    job_family: "Management",
    career_track: "Management",
    competencies: ["Team Management", "Project Delivery", "Process Improvement", "Mentoring", "Stakeholder Communication"],
    leadership_behaviors: ["Team Leader", "Process Improver", "Mentor", "Communicator"],
    executive_skills: ["Project Management", "Team Development", "Process Design", "Reporting"],
    recommended_certifications: ["PMP", "ITIL Foundation", "Agile/Scrum"],
    recommended_courses: ["Management Foundations", "Team Leadership", "Process Improvement"],
    recommended_books: ["The Making of a Manager", "Radical Candor", "Crucial Conversations"],
    promotion_path: "Manager → Senior Manager → Director → Senior Director",
    salary_benchmark_ref: "senior_manager",
    ai_persona_mapping: "team_leader",
  },
  {
    id: "service_delivery_director",
    title: "Service Delivery Director",
    executive_level: "Director",
    leadership_level: 3,
    job_family: "IT Service Management",
    career_track: "Management",
    competencies: ["SLA Management", "Service Operations", "Client Relationship", "Team Leadership", "Process Excellence"],
    leadership_behaviors: ["Service Excellence", "Client Champion", "Operational Leader", "Quality Focused"],
    executive_skills: ["ITIL", "SLA Management", "Incident Management", "Vendor Management"],
    recommended_certifications: ["ITIL Expert", "ISO 20000", "PMP", "SIAM"],
    recommended_courses: ["Service Management Excellence", "ITIL Strategy", "Client Relationship Management"],
    recommended_books: ["The Phoenix Project", "ITIL Foundation", "Service Operation"],
    promotion_path: "Service Manager → Service Delivery Manager → Service Delivery Director → Head of Service",
    salary_benchmark_ref: "service_delivery_director",
    ai_persona_mapping: "service_excellence_leader",
  },
  {
    id: "head_of_it",
    title: "Head of IT",
    executive_level: "Head",
    leadership_level: 4,
    job_family: "Information Technology",
    career_track: "Executive",
    competencies: ["IT Strategy", "Team Leadership", "Budget Management", "Vendor Management", "Digital Transformation"],
    leadership_behaviors: ["IT Visionary", "Team Builder", "Business Partner", "Innovation Driver"],
    executive_skills: ["IT Operations", "Strategy", "Financial Planning", "Stakeholder Management"],
    recommended_certifications: ["ITIL Expert", "CISM", "PMP", "MBA"],
    recommended_courses: ["IT Leadership", "Digital Transformation", "Business Strategy"],
    recommended_books: ["The CIO Paradox", "Leading Digital", "The Phoenix Project"],
    promotion_path: "IT Manager → IT Director → Head of IT → CIO",
    salary_benchmark_ref: "head_of_it",
    ai_persona_mapping: "it_leader",
  },
  {
    id: "head_of_engineering",
    title: "Head of Engineering",
    executive_level: "Head",
    leadership_level: 4,
    job_family: "Engineering",
    career_track: "Executive",
    competencies: ["Engineering Strategy", "Team Scaling", "Architecture", "Product Engineering", "Technical Leadership"],
    leadership_behaviors: ["Technical Visionary", "Engineering Culture", "Talent Builder", "Innovation Driver"],
    executive_skills: ["Architecture", "Engineering Management", "Hiring", "Technical Strategy"],
    recommended_certifications: ["AWS Solutions Architect", "TOGAF", "Engineering Management"],
    recommended_courses: ["Engineering Leadership", "System Design", "Team Scaling"],
    recommended_books: ["Accelerate", "Staff Engineer", "The Manager's Path"],
    promotion_path: "Engineering Manager → Director of Engineering → Head of Engineering → VP Engineering → CTO",
    salary_benchmark_ref: "head_of_engineering",
    ai_persona_mapping: "engineering_leader",
  },
  {
    id: "platform_engineering_manager",
    title: "Platform Engineering Manager",
    executive_level: "Manager",
    leadership_level: 2,
    job_family: "Engineering",
    career_track: "Management",
    competencies: ["Platform Strategy", "DevOps", "Cloud Infrastructure", "Team Leadership", "Developer Experience"],
    leadership_behaviors: ["Platform Builder", "Automation Champion", "Developer Advocate", "Efficiency Driver"],
    executive_skills: ["Kubernetes", "Cloud Architecture", "CI/CD", "Team Management"],
    recommended_certifications: ["CKA", "AWS DevOps", "Terraform Associate"],
    recommended_courses: ["Platform Engineering", "Cloud Native", "DevOps Excellence"],
    recommended_books: ["Team Topologies", "Accelerate", "The DevOps Handbook"],
    promotion_path: "Senior Engineer → Engineering Manager → Platform Engineering Manager → Director of Platform",
    salary_benchmark_ref: "platform_engineering_manager",
    ai_persona_mapping: "platform_leader",
  },
  {
    id: "cloud_director",
    title: "Cloud Director",
    executive_level: "Director",
    leadership_level: 3,
    job_family: "Cloud",
    career_track: "Management",
    competencies: ["Cloud Strategy", "Migration Leadership", "Cost Optimization", "Security", "Team Leadership"],
    leadership_behaviors: ["Cloud Visionary", "Cost Optimizer", "Security Champion", "Innovation Driver"],
    executive_skills: ["Multi-cloud", "Architecture", "FinOps", "Security"],
    recommended_certifications: ["AWS Solutions Architect Professional", "Azure Architect Expert", "CCSP"],
    recommended_courses: ["Cloud Strategy", "FinOps", "Cloud Security"],
    recommended_books: ["Cloud Strategy", "The Cloud Adoption Playbook", "AWS Well-Architected"],
    promotion_path: "Cloud Architect → Cloud Manager → Cloud Director → VP Cloud → CTO",
    salary_benchmark_ref: "cloud_director",
    ai_persona_mapping: "cloud_strategy_leader",
  },
  {
    id: "infrastructure_director",
    title: "Infrastructure Director",
    executive_level: "Director",
    leadership_level: 3,
    job_family: "Infrastructure",
    career_track: "Management",
    competencies: ["Infrastructure Strategy", "Data Center", "Network", "Security", "Team Leadership"],
    leadership_behaviors: ["Infrastructure Builder", "Reliability Champion", "Security Focused", "Cost Conscious"],
    executive_skills: ["Network Architecture", "Systems", "Disaster Recovery", "Vendor Management"],
    recommended_certifications: ["CCNP", "CISSP", "ITIL Expert", "VMware"],
    recommended_courses: ["Infrastructure Excellence", "Network Security", "Data Center Management"],
    recommended_books: ["Designing Data-Intensive Applications", "The Phoenix Project", "Site Reliability Engineering"],
    promotion_path: "Infrastructure Manager → Infrastructure Director → VP Infrastructure → CIO",
    salary_benchmark_ref: "infrastructure_director",
    ai_persona_mapping: "infrastructure_leader",
  },
  {
    id: "enterprise_architect",
    title: "Enterprise Architect",
    executive_level: "Architect",
    leadership_level: 3,
    job_family: "Architecture",
    career_track: "Technical",
    competencies: ["Enterprise Architecture", "Strategy", "Governance", "Stakeholder Management", "Technology Roadmaps"],
    leadership_behaviors: ["Strategic Thinker", "Standard Setter", "Business-IT Bridge", "Innovation Catalyst"],
    executive_skills: ["TOGAF", "Strategy", "Modeling", "Communication"],
    recommended_certifications: ["TOGAF", "Zachman", "AWS/Azure Architect", "CISSP"],
    recommended_courses: ["Enterprise Architecture", "Strategy & Governance", "Digital Transformation"],
    recommended_books: ["Enterprise Architecture as Strategy", "TOGAF Standard", "Good Strategy Bad Strategy"],
    promotion_path: "Solution Architect → Senior Architect → Enterprise Architect → Chief Architect",
    salary_benchmark_ref: "enterprise_architect",
    ai_persona_mapping: "architecture_strategist",
  },
  {
    id: "program_director",
    title: "Program Director",
    executive_level: "Director",
    leadership_level: 3,
    job_family: "Program Management",
    career_track: "Management",
    competencies: ["Program Strategy", "Portfolio Management", "Stakeholder Management", "Risk Management", "Team Leadership"],
    leadership_behaviors: ["Program Visionary", "Risk Manager", "Stakeholder Champion", "Delivery Excellence"],
    executive_skills: ["PMP", "Portfolio Management", "Risk", "Communication"],
    recommended_certifications: ["PgMP", "PMP", "PRINCE2", "MSP"],
    recommended_courses: ["Program Management Excellence", "Portfolio Management", "Executive Communication"],
    recommended_books: ["The Standard for Program Management", "PMBOK Guide", "Managing Successful Programmes"],
    promotion_path: "Project Manager → Program Manager → Program Director → VP PMO",
    salary_benchmark_ref: "program_director",
    ai_persona_mapping: "program_leader",
  },
];

/** Search roles by title, job family, or career track. */
export function searchRoles(query, limit = 10) {
  if (!query || !query.trim()) return ROLES.slice(0, limit);
  const q = query.toLowerCase().trim();
  return ROLES.filter(r =>
    r.title.toLowerCase().includes(q) ||
    r.job_family.toLowerCase().includes(q) ||
    r.career_track.toLowerCase().includes(q) ||
    r.executive_level.toLowerCase().includes(q) ||
    r.competencies.some(c => c.toLowerCase().includes(q))
  ).slice(0, limit);
}

export function getRoleById(id) {
  return ROLES.find(r => r.id === id);
}

export function getRoleByTitle(title) {
  if (!title) return null;
  return ROLES.find(r => r.title.toLowerCase() === title.toLowerCase());
}