export const DECISION_LIFECYCLE_STAGES = Object.freeze({
  DRAFT: 'DRAFT',
  EXPLORE: 'EXPLORE',
  MODEL: 'MODEL',
  CHALLENGE: 'CHALLENGE',
  SIMULATE: 'SIMULATE',
  READY_TO_DECIDE: 'READY_TO_DECIDE',
  DECIDED: 'DECIDED',
  MEASURING: 'MEASURING',
  OUTCOME_RECORDED: 'OUTCOME_RECORDED',
  LEARNED: 'LEARNED',
  CLOSED: 'CLOSED',
});

export const DECISION_LIFECYCLE_ORDER = Object.freeze(Object.values(DECISION_LIFECYCLE_STAGES));

export const DECISION_LIFECYCLE_NEXT = Object.freeze({
  DRAFT: 'EXPLORE',
  EXPLORE: 'MODEL',
  MODEL: 'CHALLENGE',
  CHALLENGE: 'SIMULATE',
  SIMULATE: 'READY_TO_DECIDE',
  READY_TO_DECIDE: 'DECIDED',
  DECIDED: 'MEASURING',
  MEASURING: 'OUTCOME_RECORDED',
  OUTCOME_RECORDED: 'LEARNED',
  LEARNED: 'CLOSED',
  CLOSED: null,
});

export const DECISION_LIFECYCLE_PATHS = Object.freeze({ FULL: 'full', ABBREVIATED: 'abbreviated' });