/**
 * EXECLEAD.AI — Capability Registry™ v1.0
 * =================================================
 * Centralized registry of every premium-capable feature.
 * Each capability stores metadata for commercialization
 * analysis, entitlement checks, and AI economics.
 *
 * This registry is the single source of truth for what
 * features exist, what plan they require, and whether
 * they are candidates for future Intelligence Suites™.
 */

// ============================================================
// Capability Statuses
// ============================================================

export const CAPABILITY_STATUS = {
  CORE: 'core',
  PREMIUM_CANDIDATE: 'premium_candidate',
  ENTERPRISE: 'enterprise',
  EXPERIMENTAL: 'experimental',
  INTERNAL: 'internal',
  VALIDATED: 'validated',
  COMMERCIALIZED: 'commercialized',
  RETIRED: 'retired',
  FUTURE: 'future',
};

export const STATUS_META = {
  core:               { label: 'Core',               color: '#10b981', description: 'Available to all plans' },
  premium_candidate:  { label: 'Premium Candidate',  color: '#a855f7', description: 'Candidate for future premium suite' },
  enterprise:         { label: 'Enterprise',          color: '#3b82f6', description: 'Enterprise-only capability' },
  experimental:       { label: 'Experimental',        color: '#f59e0b', description: 'In development / beta' },
  internal:           { label: 'Internal',            color: '#06b6d4', description: 'Internal-only capability' },
  validated:          { label: 'Validated',           color: '#3b82f6', description: 'Proven demand — ready for commercialization' },
  commercialized:     { label: 'Commercialized',      color: '#10b981', description: 'Actively sold as part of a paid plan' },
  retired:            { label: 'Retired',             color: '#64748b', description: 'Decommissioned' },
  future:             { label: 'Future',              color: '#06b6d4', description: 'Planned but not built' },
};

// ============================================================
// Capability Flag Types
// ============================================================

export const CAPABILITY_FLAGS = {
  ENABLED: 'enabled',
  DISABLED: 'disabled',
  PREMIUM_CANDIDATE: 'premium_candidate',
  ENTERPRISE_ONLY: 'enterprise_only',
  HIDDEN: 'hidden',
  BETA: 'beta',
  INTERNAL: 'internal',
  INTERNAL_ONLY: 'internal_only',
  DEVELOPER: 'developer',
  DEVELOPER_ONLY: 'developer_only',
  EXPERIMENTAL: 'experimental',
};

export const FLAG_META = {
  enabled:            { label: 'Enabled',            color: '#10b981', visible: true,  usable: true },
  disabled:           { label: 'Disabled',           color: '#ef4444', visible: true,  usable: false },
  premium_candidate:  { label: 'Premium Candidate',  color: '#a855f7', visible: true,  usable: true },
  enterprise_only:    { label: 'Enterprise Only',    color: '#3b82f6', visible: false, usable: false },
  hidden:             { label: 'Hidden',             color: '#64748b', visible: false, usable: false },
  beta:               { label: 'Beta',               color: '#f59e0b', visible: true,  usable: true },
  internal:           { label: 'Internal',           color: '#06b6d4', visible: false, usable: false },
  internal_only:      { label: 'Internal Only',      color: '#06b6d4', visible: false, usable: false },
  developer:          { label: 'Developer',          color: '#8b5cf6', visible: false, usable: false },
  developer_only:     { label: 'Developer Only',     color: '#8b5cf6', visible: false, usable: false },
  experimental:       { label: 'Experimental',       color: '#f59e0b', visible: false, usable: false },
};

// ============================================================
// Impact Levels
// ============================================================

const IMPACT = {
  NONE: 0, LOW: 1, MEDIUM: 2, HIGH: 3, CRITICAL: 4,
};

const IMPACT_LABEL = { 0: 'None', 1: 'Low', 2: 'Medium', 3: 'High', 4: 'Critical' };

// ============================================================
// Capability Registry
// ============================================================

export const CAPABILITIES = [
  // ── Executive AI Intelligence ──
  {
    id: 'executive_digital_twin',
    name: 'Executive Digital Twin™',
    description: 'AI-powered digital twin modeling executive capability, growth, and readiness',
    workspace: 'executive',
    category: 'AI Intelligence',
    owner: 'platform',
    currentPlan: 'executive',
    premiumCandidate: true,
    aiComputeRequired: true,
    estimatedComputeCost: 0.15,
    avgTokensPerCall: 3500,
    avgResponseTimeMs: 4200,
    featureFlag: 'executive_digital_twin',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.CRITICAL,
    conversionImpact: IMPACT.CRITICAL,
    customerValue: 95,
    strategicAlignment: 95,
    engineeringComplexity: 85,
    recommendedPlan: 'executive',
    recommendedSuite: 'executive_intelligence_suite',
  },
  {
    id: 'decision_intelligence',
    name: 'Decision Intelligence™',
    description: 'AI-powered executive decision evaluation with predictive outcomes',
    workspace: 'executive',
    category: 'AI Intelligence',
    owner: 'platform',
    currentPlan: 'executive',
    premiumCandidate: true,
    aiComputeRequired: true,
    estimatedComputeCost: 0.12,
    avgTokensPerCall: 2800,
    avgResponseTimeMs: 3500,
    featureFlag: 'decision_intelligence',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.HIGH,
    conversionImpact: IMPACT.HIGH,
    customerValue: 88,
    strategicAlignment: 90,
    engineeringComplexity: 80,
    recommendedPlan: 'executive',
    recommendedSuite: 'executive_intelligence_suite',
  },
  {
    id: 'executive_future',
    name: 'Executive Future™',
    description: 'Predictive career trajectory and future state modeling',
    workspace: 'executive',
    category: 'AI Intelligence',
    owner: 'platform',
    currentPlan: 'executive',
    premiumCandidate: true,
    aiComputeRequired: true,
    estimatedComputeCost: 0.10,
    avgTokensPerCall: 2200,
    avgResponseTimeMs: 3000,
    featureFlag: 'executive_future',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.FUTURE,
    retentionImpact: IMPACT.HIGH,
    conversionImpact: IMPACT.MEDIUM,
    customerValue: 82,
    strategicAlignment: 88,
    engineeringComplexity: 75,
    recommendedPlan: 'executive',
    recommendedSuite: 'executive_intelligence_suite',
  },
  {
    id: 'leadership_dna',
    name: 'Leadership DNA™',
    description: 'Multi-dimensional leadership assessment and competency profiling',
    workspace: 'executive',
    category: 'Assessment',
    owner: 'platform',
    currentPlan: 'executive',
    premiumCandidate: true,
    aiComputeRequired: true,
    estimatedComputeCost: 0.03,
    avgTokensPerCall: 1200,
    avgResponseTimeMs: 1800,
    featureFlag: 'leadership_dna',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.HIGH,
    conversionImpact: IMPACT.HIGH,
    customerValue: 85,
    strategicAlignment: 92,
    engineeringComplexity: 60,
    recommendedPlan: 'executive',
    recommendedSuite: 'executive_growth_suite',
  },
  {
    id: 'intelligence_center',
    name: 'Executive Intelligence Center™',
    description: 'Unified intelligence dashboard aggregating all executive metrics',
    workspace: 'executive',
    category: 'AI Intelligence',
    owner: 'platform',
    currentPlan: 'executive',
    premiumCandidate: true,
    aiComputeRequired: false,
    estimatedComputeCost: 0.00,
    avgTokensPerCall: 0,
    avgResponseTimeMs: 0,
    featureFlag: 'intelligence_center',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.HIGH,
    conversionImpact: IMPACT.MEDIUM,
    customerValue: 80,
    strategicAlignment: 85,
    engineeringComplexity: 55,
    recommendedPlan: 'executive',
    recommendedSuite: 'executive_intelligence_suite',
  },

  // ── Executive Identity & Trust ──
  {
    id: 'executive_portfolio',
    name: 'Executive Portfolio™',
    description: 'Comprehensive executive portfolio with versioned snapshots',
    workspace: 'executive',
    category: 'Identity',
    owner: 'platform',
    currentPlan: 'free',
    premiumCandidate: false,
    aiComputeRequired: false,
    estimatedComputeCost: 0.00,
    avgTokensPerCall: 0,
    avgResponseTimeMs: 0,
    featureFlag: 'executive_portfolio',
    flag: CAPABILITY_FLAGS.ENABLED,
    status: CAPABILITY_STATUS.CORE,
    retentionImpact: IMPACT.HIGH,
    conversionImpact: IMPACT.MEDIUM,
    customerValue: 75,
    strategicAlignment: 80,
    engineeringComplexity: 50,
    recommendedPlan: 'free',
    recommendedSuite: null,
  },
  {
    id: 'executive_credentials',
    name: 'Executive Credentials™',
    description: 'Verifiable executive credential issuance and wallet',
    workspace: 'executive',
    category: 'Identity',
    owner: 'platform',
    currentPlan: 'executive',
    premiumCandidate: true,
    aiComputeRequired: false,
    estimatedComputeCost: 0.00,
    avgTokensPerCall: 0,
    avgResponseTimeMs: 0,
    featureFlag: 'executive_credentials',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.HIGH,
    conversionImpact: IMPACT.HIGH,
    customerValue: 82,
    strategicAlignment: 85,
    engineeringComplexity: 65,
    recommendedPlan: 'executive',
    recommendedSuite: 'executive_trust_suite',
  },
  {
    id: 'verification_center',
    name: 'Verification Center™',
    description: 'Multi-category identity verification workflow',
    workspace: 'executive',
    category: 'Trust',
    owner: 'platform',
    currentPlan: 'free',
    premiumCandidate: false,
    aiComputeRequired: false,
    estimatedComputeCost: 0.00,
    avgTokensPerCall: 0,
    avgResponseTimeMs: 0,
    featureFlag: 'verification_center',
    flag: CAPABILITY_FLAGS.ENABLED,
    status: CAPABILITY_STATUS.CORE,
    retentionImpact: IMPACT.CRITICAL,
    conversionImpact: IMPACT.LOW,
    customerValue: 70,
    strategicAlignment: 90,
    engineeringComplexity: 70,
    recommendedPlan: 'free',
    recommendedSuite: null,
  },
  {
    id: 'evidence_vault',
    name: 'Evidence Vault™',
    description: 'Secure evidence storage with AI quality scoring and intelligence',
    workspace: 'executive',
    category: 'Trust',
    owner: 'platform',
    currentPlan: 'professional',
    premiumCandidate: true,
    aiComputeRequired: true,
    estimatedComputeCost: 0.04,
    avgTokensPerCall: 1500,
    avgResponseTimeMs: 2200,
    featureFlag: 'evidence_vault',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.HIGH,
    conversionImpact: IMPACT.MEDIUM,
    customerValue: 78,
    strategicAlignment: 82,
    engineeringComplexity: 68,
    recommendedPlan: 'professional',
    recommendedSuite: 'executive_trust_suite',
  },
  {
    id: 'identity_graph',
    name: 'Identity Graph™',
    description: 'Visual graph of executive identity relationships and evidence',
    workspace: 'executive',
    category: 'Trust',
    owner: 'platform',
    currentPlan: 'enterprise',
    premiumCandidate: false,
    aiComputeRequired: false,
    estimatedComputeCost: 0.00,
    avgTokensPerCall: 0,
    avgResponseTimeMs: 0,
    featureFlag: 'identity_graph',
    flag: CAPABILITY_FLAGS.ENTERPRISE_ONLY,
    status: CAPABILITY_STATUS.ENTERPRISE,
    retentionImpact: IMPACT.MEDIUM,
    conversionImpact: IMPACT.LOW,
    customerValue: 65,
    strategicAlignment: 75,
    engineeringComplexity: 72,
    recommendedPlan: 'enterprise',
    recommendedSuite: null,
  },
  {
    id: 'executive_readiness',
    name: 'Executive Readiness™',
    description: 'Composite readiness score for promotion and C-suite preparation',
    workspace: 'executive',
    category: 'Assessment',
    owner: 'platform',
    currentPlan: 'executive',
    premiumCandidate: true,
    aiComputeRequired: false,
    estimatedComputeCost: 0.00,
    avgTokensPerCall: 0,
    avgResponseTimeMs: 0,
    featureFlag: 'executive_readiness',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.HIGH,
    conversionImpact: IMPACT.HIGH,
    customerValue: 84,
    strategicAlignment: 88,
    engineeringComplexity: 55,
    recommendedPlan: 'executive',
    recommendedSuite: 'executive_growth_suite',
  },
  {
    id: 'executive_legacy',
    name: 'Executive Legacy™',
    description: 'Leadership legacy letters, case studies, and time capsules',
    workspace: 'executive',
    category: 'Identity',
    owner: 'platform',
    currentPlan: 'executive',
    premiumCandidate: true,
    aiComputeRequired: false,
    estimatedComputeCost: 0.00,
    avgTokensPerCall: 0,
    avgResponseTimeMs: 0,
    featureFlag: 'executive_legacy',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.MEDIUM,
    conversionImpact: IMPACT.MEDIUM,
    customerValue: 72,
    strategicAlignment: 78,
    engineeringComplexity: 60,
    recommendedPlan: 'executive',
    recommendedSuite: null,
  },
  {
    id: 'reputation',
    name: 'Executive Reputation™',
    description: 'Reputation scoring, badges, and community trust system',
    workspace: 'executive',
    category: 'Trust',
    owner: 'platform',
    currentPlan: 'professional',
    premiumCandidate: true,
    aiComputeRequired: false,
    estimatedComputeCost: 0.00,
    avgTokensPerCall: 0,
    avgResponseTimeMs: 0,
    featureFlag: 'reputation',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.HIGH,
    conversionImpact: IMPACT.MEDIUM,
    customerValue: 76,
    strategicAlignment: 80,
    engineeringComplexity: 65,
    recommendedPlan: 'professional',
    recommendedSuite: 'executive_trust_suite',
  },

  // ── Development & Coaching ──
  {
    id: 'ai_coach',
    name: 'AI Coach™',
    description: 'Personalized AI executive coaching with contextual guidance',
    workspace: 'executive',
    category: 'Coaching',
    owner: 'platform',
    currentPlan: 'executive',
    premiumCandidate: true,
    aiComputeRequired: true,
    estimatedComputeCost: 0.05,
    avgTokensPerCall: 1800,
    avgResponseTimeMs: 2500,
    featureFlag: 'ai_coach',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.CRITICAL,
    conversionImpact: IMPACT.HIGH,
    customerValue: 90,
    strategicAlignment: 88,
    engineeringComplexity: 55,
    recommendedPlan: 'executive',
    recommendedSuite: 'executive_growth_suite',
  },
  {
    id: 'simulator',
    name: 'Executive Simulator™',
    description: 'AI-driven executive scenario simulations with scoring',
    workspace: 'executive',
    category: 'Coaching',
    owner: 'platform',
    currentPlan: 'executive',
    premiumCandidate: true,
    aiComputeRequired: true,
    estimatedComputeCost: 0.08,
    avgTokensPerCall: 2400,
    avgResponseTimeMs: 3200,
    featureFlag: 'executive_simulator',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.HIGH,
    conversionImpact: IMPACT.HIGH,
    customerValue: 86,
    strategicAlignment: 85,
    engineeringComplexity: 62,
    recommendedPlan: 'executive',
    recommendedSuite: 'executive_growth_suite',
  },
  {
    id: 'debate',
    name: 'Executive Debate™',
    description: 'AI-powered executive debate practice with multi-perspective analysis',
    workspace: 'executive',
    category: 'Coaching',
    owner: 'platform',
    currentPlan: 'executive',
    premiumCandidate: true,
    aiComputeRequired: true,
    estimatedComputeCost: 0.10,
    avgTokensPerCall: 2600,
    avgResponseTimeMs: 3400,
    featureFlag: 'executive_debate',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.MEDIUM,
    conversionImpact: IMPACT.MEDIUM,
    customerValue: 78,
    strategicAlignment: 82,
    engineeringComplexity: 58,
    recommendedPlan: 'executive',
    recommendedSuite: 'executive_growth_suite',
  },
  {
    id: 'council',
    name: 'Executive Council™',
    description: 'AI council of executive personas for collaborative decision-making',
    workspace: 'executive',
    category: 'Coaching',
    owner: 'platform',
    currentPlan: 'executive',
    premiumCandidate: true,
    aiComputeRequired: true,
    estimatedComputeCost: 0.15,
    avgTokensPerCall: 4000,
    avgResponseTimeMs: 5000,
    featureFlag: 'executive_council',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.HIGH,
    conversionImpact: IMPACT.HIGH,
    customerValue: 88,
    strategicAlignment: 85,
    engineeringComplexity: 70,
    recommendedPlan: 'executive',
    recommendedSuite: 'executive_intelligence_suite',
  },
  {
    id: 'daily_challenge',
    name: 'Daily Executive Challenge™',
    description: 'Daily leadership challenges with AI evaluation',
    workspace: 'executive',
    category: 'Coaching',
    owner: 'platform',
    currentPlan: 'free',
    premiumCandidate: false,
    aiComputeRequired: true,
    estimatedComputeCost: 0.02,
    avgTokensPerCall: 800,
    avgResponseTimeMs: 1200,
    featureFlag: 'daily_executive_challenge',
    flag: CAPABILITY_FLAGS.ENABLED,
    status: CAPABILITY_STATUS.CORE,
    retentionImpact: IMPACT.HIGH,
    conversionImpact: IMPACT.MEDIUM,
    customerValue: 68,
    strategicAlignment: 75,
    engineeringComplexity: 45,
    recommendedPlan: 'free',
    recommendedSuite: null,
  },

  // ── Learning & Career ──
  {
    id: 'academy',
    name: 'Executive Academy™',
    description: 'Structured executive learning courses with AI tutoring',
    workspace: 'executive',
    category: 'Learning',
    owner: 'platform',
    currentPlan: 'professional',
    premiumCandidate: true,
    aiComputeRequired: true,
    estimatedComputeCost: 0.03,
    avgTokensPerCall: 1000,
    avgResponseTimeMs: 1500,
    featureFlag: 'executive_academy',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.HIGH,
    conversionImpact: IMPACT.MEDIUM,
    customerValue: 75,
    strategicAlignment: 80,
    engineeringComplexity: 50,
    recommendedPlan: 'professional',
    recommendedSuite: 'executive_growth_suite',
  },
  {
    id: 'resume_intelligence',
    name: 'Resume Intelligence™',
    description: 'AI-powered resume analysis, scoring, and intelligence report',
    workspace: 'executive',
    category: 'Career',
    owner: 'platform',
    currentPlan: 'professional',
    premiumCandidate: true,
    aiComputeRequired: true,
    estimatedComputeCost: 0.06,
    avgTokensPerCall: 2000,
    avgResponseTimeMs: 2800,
    featureFlag: 'resume_intelligence',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.MEDIUM,
    conversionImpact: IMPACT.HIGH,
    customerValue: 80,
    strategicAlignment: 78,
    engineeringComplexity: 55,
    recommendedPlan: 'professional',
    recommendedSuite: null,
  },
  {
    id: 'career_studio',
    name: 'Career Studio™',
    description: 'AI-powered resume builder, bio writer, and job match optimizer',
    workspace: 'executive',
    category: 'Career',
    owner: 'platform',
    currentPlan: 'executive',
    premiumCandidate: true,
    aiComputeRequired: true,
    estimatedComputeCost: 0.04,
    avgTokensPerCall: 1600,
    avgResponseTimeMs: 2200,
    featureFlag: 'career_studio',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.MEDIUM,
    conversionImpact: IMPACT.HIGH,
    customerValue: 82,
    strategicAlignment: 76,
    engineeringComplexity: 52,
    recommendedPlan: 'executive',
    recommendedSuite: null,
  },
  {
    id: 'career_advisor',
    name: 'Career Advisor™',
    description: 'AI career guidance with job matching and application tools',
    workspace: 'executive',
    category: 'Career',
    owner: 'platform',
    currentPlan: 'professional',
    premiumCandidate: true,
    aiComputeRequired: true,
    estimatedComputeCost: 0.05,
    avgTokensPerCall: 1800,
    avgResponseTimeMs: 2400,
    featureFlag: 'career_advisor',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.MEDIUM,
    conversionImpact: IMPACT.HIGH,
    customerValue: 79,
    strategicAlignment: 74,
    engineeringComplexity: 48,
    recommendedPlan: 'professional',
    recommendedSuite: null,
  },

  // ── Analytics & Insights ──
  {
    id: 'analytics',
    name: 'Leadership Analytics™',
    description: 'Executive performance analytics and trend visualization',
    workspace: 'executive',
    category: 'Analytics',
    owner: 'platform',
    currentPlan: 'professional',
    premiumCandidate: true,
    aiComputeRequired: false,
    estimatedComputeCost: 0.00,
    avgTokensPerCall: 0,
    avgResponseTimeMs: 0,
    featureFlag: 'leadership_analytics',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.MEDIUM,
    conversionImpact: IMPACT.MEDIUM,
    customerValue: 72,
    strategicAlignment: 82,
    engineeringComplexity: 45,
    recommendedPlan: 'professional',
    recommendedSuite: null,
  },
  {
    id: 'company_intelligence',
    name: 'Company Intelligence™',
    description: 'Company database with enrichment, comparison, and transparency',
    workspace: 'executive',
    category: 'Intelligence',
    owner: 'platform',
    currentPlan: 'professional',
    premiumCandidate: true,
    aiComputeRequired: false,
    estimatedComputeCost: 0.00,
    avgTokensPerCall: 0,
    avgResponseTimeMs: 0,
    featureFlag: 'company_intelligence',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.MEDIUM,
    conversionImpact: IMPACT.MEDIUM,
    customerValue: 74,
    strategicAlignment: 72,
    engineeringComplexity: 40,
    recommendedPlan: 'professional',
    recommendedSuite: null,
  },
  {
    id: 'enterprise_intelligence',
    name: 'Enterprise Intelligence™',
    description: 'Organization-level executive intelligence and benchmarking',
    workspace: 'executive',
    category: 'Intelligence',
    owner: 'platform',
    currentPlan: 'enterprise',
    premiumCandidate: false,
    aiComputeRequired: false,
    estimatedComputeCost: 0.00,
    avgTokensPerCall: 0,
    avgResponseTimeMs: 0,
    featureFlag: 'enterprise_intelligence',
    flag: CAPABILITY_FLAGS.ENTERPRISE_ONLY,
    status: CAPABILITY_STATUS.ENTERPRISE,
    retentionImpact: IMPACT.HIGH,
    conversionImpact: IMPACT.LOW,
    customerValue: 80,
    strategicAlignment: 85,
    engineeringComplexity: 60,
    recommendedPlan: 'enterprise',
    recommendedSuite: null,
  },

  // ── Network ──
  {
    id: 'network_feed',
    name: 'Network Feed™',
    description: 'Executive social feed with posts, discussions, and circles',
    workspace: 'network',
    category: 'Network',
    owner: 'platform',
    currentPlan: 'free',
    premiumCandidate: false,
    aiComputeRequired: false,
    estimatedComputeCost: 0.00,
    avgTokensPerCall: 0,
    avgResponseTimeMs: 0,
    featureFlag: 'network_feed',
    flag: CAPABILITY_FLAGS.ENABLED,
    status: CAPABILITY_STATUS.CORE,
    retentionImpact: IMPACT.CRITICAL,
    conversionImpact: IMPACT.LOW,
    customerValue: 65,
    strategicAlignment: 70,
    engineeringComplexity: 55,
    recommendedPlan: 'free',
    recommendedSuite: null,
  },
  {
    id: 'network_mentorship',
    name: 'Executive Mentorship™',
    description: 'AI-matched mentorship connections and guidance tracking',
    workspace: 'network',
    category: 'Network',
    owner: 'platform',
    currentPlan: 'professional',
    premiumCandidate: true,
    aiComputeRequired: true,
    estimatedComputeCost: 0.02,
    avgTokensPerCall: 800,
    avgResponseTimeMs: 1200,
    featureFlag: 'network_mentorship',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.HIGH,
    conversionImpact: IMPACT.MEDIUM,
    customerValue: 76,
    strategicAlignment: 73,
    engineeringComplexity: 42,
    recommendedPlan: 'professional',
    recommendedSuite: null,
  },
  {
    id: 'network_partnerships',
    name: 'Executive Partnerships™',
    description: 'AI-matched partnership marketplace for executive collaborations',
    workspace: 'network',
    category: 'Network',
    owner: 'platform',
    currentPlan: 'executive',
    premiumCandidate: true,
    aiComputeRequired: true,
    estimatedComputeCost: 0.03,
    avgTokensPerCall: 1000,
    avgResponseTimeMs: 1600,
    featureFlag: 'network_partnerships',
    flag: CAPABILITY_FLAGS.PREMIUM_CANDIDATE,
    status: CAPABILITY_STATUS.PREMIUM_CANDIDATE,
    retentionImpact: IMPACT.MEDIUM,
    conversionImpact: IMPACT.MEDIUM,
    customerValue: 73,
    strategicAlignment: 68,
    engineeringComplexity: 48,
    recommendedPlan: 'executive',
    recommendedSuite: null,
  },

  // ── Enterprise ──
  {
    id: 'hr_dashboard',
    name: 'HR Dashboard™',
    description: 'Enterprise HR dashboard for executive talent management',
    workspace: 'enterprise',
    category: 'Enterprise',
    owner: 'enterprise',
    currentPlan: 'enterprise',
    premiumCandidate: false,
    aiComputeRequired: false,
    estimatedComputeCost: 0.00,
    avgTokensPerCall: 0,
    avgResponseTimeMs: 0,
    featureFlag: 'hr_dashboard',
    flag: CAPABILITY_FLAGS.ENTERPRISE_ONLY,
    status: CAPABILITY_STATUS.ENTERPRISE,
    retentionImpact: IMPACT.HIGH,
    conversionImpact: IMPACT.LOW,
    customerValue: 85,
    strategicAlignment: 88,
    engineeringComplexity: 65,
    recommendedPlan: 'enterprise',
    recommendedSuite: null,
  },
  {
    id: 'succession_planning',
    name: 'Succession Planning™',
    description: 'AI-assisted succession planning and talent pipeline',
    workspace: 'enterprise',
    category: 'Enterprise',
    owner: 'enterprise',
    currentPlan: 'enterprise',
    premiumCandidate: false,
    aiComputeRequired: true,
    estimatedComputeCost: 0.08,
    avgTokensPerCall: 2500,
    avgResponseTimeMs: 3200,
    featureFlag: 'succession_planning',
    flag: CAPABILITY_FLAGS.ENTERPRISE_ONLY,
    status: CAPABILITY_STATUS.ENTERPRISE,
    retentionImpact: IMPACT.HIGH,
    conversionImpact: IMPACT.LOW,
    customerValue: 88,
    strategicAlignment: 90,
    engineeringComplexity: 70,
    recommendedPlan: 'enterprise',
    recommendedSuite: null,
  },
  {
    id: 'promotion_readiness',
    name: 'Promotion Readiness™',
    description: 'AI-powered promotion readiness assessment for enterprise talent',
    workspace: 'enterprise',
    category: 'Enterprise',
    owner: 'enterprise',
    currentPlan: 'enterprise',
    premiumCandidate: false,
    aiComputeRequired: true,
    estimatedComputeCost: 0.06,
    avgTokensPerCall: 2000,
    avgResponseTimeMs: 2800,
    featureFlag: 'promotion_readiness',
    flag: CAPABILITY_FLAGS.ENTERPRISE_ONLY,
    status: CAPABILITY_STATUS.ENTERPRISE,
    retentionImpact: IMPACT.HIGH,
    conversionImpact: IMPACT.LOW,
    customerValue: 84,
    strategicAlignment: 87,
    engineeringComplexity: 62,
    recommendedPlan: 'enterprise',
    recommendedSuite: null,
  },
  {
    id: 'sso',
    name: 'Enterprise SSO™',
    description: 'SAML/OIDC single sign-on with SCIM provisioning',
    workspace: 'enterprise',
    category: 'Enterprise',
    owner: 'enterprise',
    currentPlan: 'enterprise',
    premiumCandidate: false,
    aiComputeRequired: false,
    estimatedComputeCost: 0.00,
    avgTokensPerCall: 0,
    avgResponseTimeMs: 0,
    featureFlag: 'sso',
    flag: CAPABILITY_FLAGS.ENTERPRISE_ONLY,
    status: CAPABILITY_STATUS.ENTERPRISE,
    retentionImpact: IMPACT.CRITICAL,
    conversionImpact: IMPACT.LOW,
    customerValue: 82,
    strategicAlignment: 85,
    engineeringComplexity: 75,
    recommendedPlan: 'enterprise',
    recommendedSuite: null,
  },
  {
    id: 'governance_command_center',
    name: 'Governance Command Center™',
    description: 'Enterprise governance, compliance, and audit management',
    workspace: 'enterprise',
    category: 'Enterprise',
    owner: 'enterprise',
    currentPlan: 'enterprise',
    premiumCandidate: false,
    aiComputeRequired: false,
    estimatedComputeCost: 0.00,
    avgTokensPerCall: 0,
    avgResponseTimeMs: 0,
    featureFlag: 'governance_command_center',
    flag: CAPABILITY_FLAGS.ENTERPRISE_ONLY,
    status: CAPABILITY_STATUS.ENTERPRISE,
    retentionImpact: IMPACT.HIGH,
    conversionImpact: IMPACT.LOW,
    customerValue: 80,
    strategicAlignment: 88,
    engineeringComplexity: 68,
    recommendedPlan: 'enterprise',
    recommendedSuite: null,
  },

  // ── Marketplace ──
  {
    id: 'marketplace',
    name: 'Marketplace™',
    description: 'Executive marketplace for companies, services, and bundles',
    workspace: 'executive',
    category: 'Marketplace',
    owner: 'platform',
    currentPlan: 'free',
    premiumCandidate: false,
    aiComputeRequired: false,
    estimatedComputeCost: 0.00,
    avgTokensPerCall: 0,
    avgResponseTimeMs: 0,
    featureFlag: 'marketplace',
    flag: CAPABILITY_FLAGS.BETA,
    status: CAPABILITY_STATUS.EXPERIMENTAL,
    retentionImpact: IMPACT.MEDIUM,
    conversionImpact: IMPACT.MEDIUM,
    customerValue: 60,
    strategicAlignment: 65,
    engineeringComplexity: 55,
    recommendedPlan: 'free',
    recommendedSuite: null,
  },
];

// ============================================================
// Registry Helpers
// ============================================================

export function getCapability(id) {
  return CAPABILITIES.find(c => c.id === id) || null;
}

export function getCapabilitiesByWorkspace(workspace) {
  return CAPABILITIES.filter(c => c.workspace === workspace);
}

export function getCapabilitiesByCategory(category) {
  return CAPABILITIES.filter(c => c.category === category);
}

export function getCapabilitiesByStatus(status) {
  return CAPABILITIES.filter(c => c.status === status);
}

export function getPremiumCandidates() {
  return CAPABILITIES.filter(c => c.premiumCandidate);
}

export function getEnterpriseCapabilities() {
  return CAPABILITIES.filter(c => c.status === CAPABILITY_STATUS.ENTERPRISE);
}

export function getAICapabilities() {
  return CAPABILITIES.filter(c => c.aiComputeRequired);
}

export function isCapabilityVisible(capability, userPlan) {
  const flag = FLAG_META[capability.flag];
  if (!flag) return false;
  if (!flag.visible) return false;
  if (capability.status === CAPABILITY_STATUS.RETIRED) return false;
  return true;
}

export function isCapabilityUsable(capability, userPlan) {
  const flag = FLAG_META[capability.flag];
  if (!flag) return false;
  return flag.usable;
}

export function getImpactLabel(level) {
  return IMPACT_LABEL[level] || 'None';
}

export const CATEGORIES = [...new Set(CAPABILITIES.map(c => c.category))].sort();
export const WORKSPACES = [...new Set(CAPABILITIES.map(c => c.workspace))].sort();