/**
 * EXECLEAD.AI — Platform Validation™ Report Builder
 * ============================================================
 * Builds a complete report definition for the Platform Validation™
 * report by aggregating data from the Governance Pipeline™,
 * Deployment Readiness Engine™, Knowledge Sync Engine™, and
 * Platform Manifest™.
 *
 * Used by <ReportToolbar /> on the Deployment Center page.
 */
import { runGovernancePipeline } from "@/lib/governancePipeline";
import { discoverPlatformAssets, validateKnowledgeSync, buildRegistries } from "@/lib/execKnowledgeSyncEngine";
import { PLATFORM_METADATA, getManifestCoverage } from "@/lib/platformManifest";
import { buildReportId, generateExecAnalysis, REPORT_TYPES } from "@/lib/enterpriseReportEngine";

const STATUS_LABEL = { pass: "Pass", warn: "Warning", fail: "Fail" };
const safe = (v, f = "—") => (v != null && v !== "" ? String(v) : f);
const repairTime = (f) => (f.autoRepairable ? "15-30 min (auto)" : "1-2 hrs (manual)");

export async function buildPlatformValidationReport(reportType = "full_engineering", user = null) {
  const cert = runGovernancePipeline("report");
  const coverage = getManifestCoverage();
  const assets = discoverPlatformAssets();
  const validation = validateKnowledgeSync(assets);
  const registries = buildRegistries(assets, validation);

  const reportId = buildReportId("PVR");
  const now = new Date();
  const passed = cert.stages.filter((s) => s.status === "pass").length;
  const warned = cert.stages.filter((s) => s.status === "warn").length;
  const failed = cert.stages.filter((s) => s.status === "fail").length;

  // ── METADATA ──
  const metadata = [
    { label: "Validation Date", value: now.toLocaleDateString() },
    { label: "Platform Version", value: PLATFORM_METADATA.platformVersion },
    { label: "Configuration Version", value: PLATFORM_METADATA.configVersion || "—" },
    { label: "Build Number", value: PLATFORM_METADATA.buildNumber },
    { label: "Environment", value: PLATFORM_METADATA.environment || "production" },
    { label: "Validation ID", value: reportId },
    { label: "Generated By", value: user?.full_name || user?.email || "System" },
    { label: "Generated Timestamp", value: now.toISOString() },
  ];

  // ── EXECUTIVE SUMMARY ──
  const recommendation = cert.certified
    ? "Platform is certified and production-ready. All critical validation checks have passed."
    : `Platform requires attention: ${cert.failures} critical failure(s) and ${cert.warnings} warning(s) must be resolved before deployment.`;

  const execSummary = {
    id: "exec_summary",
    title: "Executive Summary",
    type: "summary",
    data: {
      metrics: [
        { label: "Overall Score", value: cert.overallGovernanceScore, tone: cert.overallGovernanceScore >= 85 ? "emerald" : "amber" },
        { label: "Certification Status", value: cert.certified ? "Certified" : "Not Certified", tone: cert.certified ? "emerald" : "amber" },
        { label: "Overall Health", value: `${cert.overallGovernanceScore}%`, tone: cert.overallGovernanceScore >= 85 ? "emerald" : "amber" },
        { label: "Failures", value: cert.failures, tone: cert.failures > 0 ? "red" : "emerald" },
        { label: "Warnings", value: cert.warnings, tone: cert.warnings > 0 ? "amber" : "emerald" },
        { label: "Passed Checks", value: passed, tone: "emerald" },
        { label: "Skipped Checks", value: 0, tone: "default" },
        { label: "Architecture Health", value: cert.registryHealth, tone: cert.registryHealth >= 85 ? "emerald" : "amber" },
        { label: "Deployment Readiness", value: cert.deploymentReadiness, tone: cert.deploymentReadiness >= 85 ? "emerald" : "amber" },
        { label: "Enterprise Readiness", value: cert.enterpriseReadiness, tone: cert.enterpriseReadiness >= 85 ? "emerald" : "amber" },
      ],
      recommendation,
    },
  };

  // ── VALIDATION BREAKDOWN ──
  const breakdownRows = cert.stages.map((s) => {
    const errs = s.findings.filter((f) => f.level === "error").length;
    const warns = s.findings.filter((f) => f.level === "warning").length;
    return [
      s.name,
      STATUS_LABEL[s.status] || s.status,
      safe(s.score),
      errs === 0 && warns === 0 ? "Yes" : "—",
      warns,
      errs,
      `${safe(s.duration)}ms`,
    ];
  });

  const validationBreakdown = {
    id: "validation_breakdown",
    title: "Validation Breakdown",
    type: "table",
    data: {
      columns: ["Stage", "Status", "Score", "Passed", "Warnings", "Failures", "Duration"],
      rows: breakdownRows,
    },
  };

  // ── FAILURES ──
  const failures = cert.findings.filter((f) => f.level === "error").map((f) => ({
    id: f.id || f.code,
    severity: "Critical",
    description: f.message,
    affectedComponent: f.affectedModules?.join(", ") || "—",
    rootCause: f.rootCause,
    evidence: f.evidence,
    suggestedFix: f.recommendedAction,
    estimatedRepairTime: repairTime(f),
    engineeringOwner: f.relatedRegistryEntries?.[0] || "Platform Engineering",
    currentStatus: f.autoRepairable ? "Auto Repair Available" : "Requires Review",
  }));

  const failuresSection = {
    id: "failures",
    title: "Failures",
    type: "findings",
    data: { findings: failures },
  };

  // ── WARNINGS ──
  const warnings = cert.findings.filter((f) => f.level === "warning").map((f) => ({
    id: f.id || f.code,
    severity: "warning",
    category: f.code?.replace(/_/g, " ") || "Warning",
    affectedModule: f.affectedModules?.join(", ") || "—",
    impact: f.impact,
    recommendation: f.recommendedAction,
    priority: "Medium",
    autoRepair: f.autoRepairable ? "Yes" : "No",
    description: f.message,
    rootCause: f.rootCause,
    suggestedFix: f.recommendedAction,
    engineeringOwner: f.relatedRegistryEntries?.[0] || "Platform Engineering",
  }));

  const warningsSection = {
    id: "warnings",
    title: "Warnings",
    type: "findings",
    data: { findings: warnings },
  };

  // ── ENGINEERING METRICS ──
  const engineeringMetrics = {
    id: "engineering_metrics",
    title: "Engineering Metrics",
    type: "metrics",
    data: {
      metrics: [
        { label: "Architecture Score", value: cert.registryHealth, tone: cert.registryHealth >= 85 ? "emerald" : "amber" },
        { label: "Platform Stability™", value: cert.platformState, tone: cert.platformState >= 85 ? "emerald" : "amber" },
        { label: "Experience Score™", value: cert.knowledgeHealth, tone: cert.knowledgeHealth >= 85 ? "emerald" : "amber" },
        { label: "Deployment Score™", value: cert.deploymentReadiness, tone: cert.deploymentReadiness >= 85 ? "emerald" : "amber" },
        { label: "Knowledge Score™", value: cert.knowledgeHealth, tone: cert.knowledgeHealth >= 85 ? "emerald" : "amber" },
        { label: "Security Score™", value: cert.manifestHealth, tone: cert.manifestHealth >= 85 ? "emerald" : "amber" },
        { label: "Reliability Score™", value: cert.synchronizationHealth, tone: cert.synchronizationHealth >= 85 ? "emerald" : "amber" },
        { label: "Enterprise Score™", value: cert.enterpriseReadiness, tone: cert.enterpriseReadiness >= 85 ? "emerald" : "amber" },
        { label: "Overall Readiness™", value: cert.overallGovernanceScore, tone: cert.overallGovernanceScore >= 85 ? "emerald" : "amber" },
      ],
    },
  };

  // ── APPENDIX ──
  const appendixRegistries = [
    {
      name: "Platform Metadata",
      count: 1,
      items: [
        `Platform: ${PLATFORM_METADATA.platformName || "EXECLEAD.AI"} v${PLATFORM_METADATA.platformVersion}`,
        `Manifest Version: ${PLATFORM_METADATA.manifestVersion}`,
        `Build: ${PLATFORM_METADATA.buildNumber}`,
        `Environment: ${PLATFORM_METADATA.environment || "production"}`,
        `Route Coverage: ${coverage?.routeCoverage ?? "—"}%`,
      ],
    },
    {
      name: "Framework Versions",
      count: assets.counts.frameworks,
      items: assets.frameworks.map((f) => `${f.name} v${f.version} (${f.source})`),
    },
    {
      name: "Knowledge Packs",
      count: registries.knowledgePack.count,
      items: registries.knowledgePack.items.map((p) => `${p.name} [${p.status}]`),
    },
    {
      name: "Registered Modules",
      count: assets.counts.modules,
      items: assets.modules.map((m) => `${m.id} - ${m.name}`),
    },
    {
      name: "Registered Routes",
      count: assets.counts.routes,
      items: assets.routes.slice(0, 40).map((r) => `${r.path} (${r.name})`),
    },
    {
      name: "Registered Personas",
      count: assets.counts.personas,
      items: assets.personas.map((p) => `${p.name} [${p.source}]`),
    },
    {
      name: "Capability Registry",
      count: registries.capability.count,
      items: registries.capability.items.map((c) => `${c.id} - ${c.name} [${c.status}]`),
    },
    {
      name: "Evidence Registry",
      count: registries.evidence.sources,
      items: [`${registries.evidence.verifiedSources} verified sources`],
    },
    {
      name: "Platform Manifest™",
      count: coverage?.routes ?? 0,
      items: [
        `Modules: ${coverage?.modules ?? 0}`,
        `Routes: ${coverage?.routes ?? 0} (${coverage?.routeCoverage ?? 0}% indexed)`,
        `Workspaces: ${coverage?.workspaces ?? 0}`,
        `Capabilities: ${coverage?.capabilities ?? 0} (${coverage?.activeCapabilities ?? 0} active)`,
        `Feature Flags: ${coverage?.featureFlags ?? 0} (${coverage?.liveFeatures ?? 0} live)`,
      ],
    },
  ];

  const appendix = {
    id: "appendix",
    title: "Appendix",
    type: "appendix",
    data: { registries: appendixRegistries },
  };

  // ── BUILD REPORT DEF (needed for exec analysis context) ──
  const reportDef = {
    reportId,
    reportType,
    title: "Platform Validation Report",
    subtitle: "EXECLEAD.AI Platform Validation™",
    metadata,
    sections: [execSummary, validationBreakdown, failuresSection, warningsSection, engineeringMetrics, appendix],
    execAnalysis: null,
  };

  // ── EXEC™ AI ANALYSIS ──
  const contextSummary = [
    `Report: ${reportDef.title} (${REPORT_TYPES[reportType]?.label})`,
    `Overall Score: ${cert.overallGovernanceScore}/100`,
    `Certified: ${cert.certified ? "Yes" : "No"}`,
    `Failures: ${cert.failures} | Warnings: ${cert.warnings} | Auto-Repairable: ${cert.repairActions}`,
    `Manifest Health: ${cert.manifestHealth} | Registry: ${cert.registryHealth} | Knowledge: ${cert.knowledgeHealth}`,
    `Synchronization: ${cert.synchronizationHealth} | Deployment: ${cert.deploymentReadiness} | Enterprise: ${cert.enterpriseReadiness}`,
    `Stages: ${cert.stages.length} (${passed} passed, ${warned} warnings, ${failed} failures)`,
    `Key Failures: ${failures.slice(0, 5).map((f) => f.description).join("; ") || "None"}`,
    `Key Warnings: ${warnings.slice(0, 5).map((w) => w.description).join("; ") || "None"}`,
    `Route Coverage: ${coverage?.routeCoverage ?? "—"}% | Modules: ${assets.counts.modules} | Routes: ${assets.counts.routes}`,
  ].join("\n");

  const execAnalysis = await generateExecAnalysis(reportDef, contextSummary);
  reportDef.sections.splice(5, 0, { id: "exec_analysis", title: "EXEC™ Analysis", type: "exec_analysis", data: execAnalysis });
  reportDef.execAnalysis = execAnalysis;

  return reportDef;
}