import React, { useRef, useState } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { PARTNER_CATEGORIES } from '@/lib/strategic-partners/partnerConfig';

const required = ['Partner Name','Partner Category','Strategic Role','Priority','Target Region','Target Industry','Strategic Rationale','Initial Status','Initial Stage'];
const parseRow = (line) => { const values=[]; let value='', quoted=false; for(let i=0;i<line.length;i++){const char=line[i];if(char==='"'&&line[i+1]==='"'){value+='"';i++;}else if(char==='"'){quoted=!quoted;}else if(char===','&&!quoted){values.push(value.trim());value='';}else value+=char;} values.push(value.trim()); return values; };
const categoryMap = Object.fromEntries(PARTNER_CATEGORIES.flatMap((item) => [[item.label.toLowerCase(), item.id],[item.id, item.id]]));

export default function PartnerImportDialog({ open, onClose, onImport }) {
  const input = useRef(null); const [rows,setRows]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  const read = async (event) => { const text=await event.target.files?.[0]?.text(); if(!text)return; const lines=text.split(/\r?\n/).filter(Boolean); const headers=parseRow(lines[0]); const missing=required.filter((field)=>!headers.includes(field)); if(missing.length){setError(`Missing columns: ${missing.join(', ')}`);setRows([]);return;} const parsed=lines.slice(1).map((line)=>Object.fromEntries(headers.map((header,index)=>[header,parseRow(line)[index]||'']))); const invalid=parsed.find((row)=>required.some((field)=>!row[field])||!categoryMap[row['Partner Category'].toLowerCase()]||!['P0','P1','P2'].includes(row.Priority)||!['Prospect'].includes(row['Initial Status'])||!['Target','Research'].includes(row['Initial Stage'])); if(invalid){setError('Every row must be complete, use an approved category, P0/P1/P2, Prospect status, and Target or Research stage.');setRows([]);return;} setError('');setRows(parsed.map((row)=>({partnerName:row['Partner Name'],partnerCategory:categoryMap[row['Partner Category'].toLowerCase()],strategicRole:row['Strategic Role'],priority:row.Priority,targetRegion:row['Target Region'],targetIndustry:row['Target Industry'],strategicRationale:row['Strategic Rationale'],partnerStatus:row['Initial Status'],partnershipStage:row['Initial Stage']}))); };
  const submit=async()=>{setLoading(true);await onImport(rows);setLoading(false);setRows([]);onClose();};
  return <Dialog open={open} onOpenChange={(value)=>!value&&onClose()}><DialogContent><DialogHeader><DialogTitle>Import Partner Targets</DialogTitle><DialogDescription>Upload a CSV using the required target columns. Imports cannot mark records active, contracted, in pilot, or negotiation.</DialogDescription></DialogHeader><div className="rounded-lg bg-muted p-3 text-xs text-muted-foreground">Required columns: {required.join(' · ')}</div><input ref={input} type="file" accept=".csv,text/csv" onChange={read} className="min-h-11 w-full rounded-lg border border-input p-2 text-sm"/>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{rows.length>0&&<p className="text-sm text-success">{rows.length} valid target rows ready to import.</p>}<div className="flex justify-end gap-2"><button onClick={onClose} className="min-h-11 rounded-lg border border-border px-4">Cancel</button><button disabled={!rows.length||loading} onClick={submit} className="min-h-11 rounded-lg bg-primary px-4 text-primary-foreground disabled:opacity-50">{loading?'Importing…':`Import ${rows.length || ''} Targets`}</button></div></DialogContent></Dialog>;
}