import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Pencil, Target } from 'lucide-react';
import { categoryLabel } from '@/lib/strategic-partners/partnerConfig';
import { priorityLabel } from '@/lib/strategic-partners/partnerDisplay';

const Fact = ({ label, value }) => <div><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 text-sm text-foreground">{value || '—'}</dd></div>;

export default function TargetPartnerDetail({ partner, onEdit }) {
  return <div className="space-y-6"><Link to="/operations/strategic-partners" className="inline-flex min-h-11 items-center gap-2 text-sm text-muted-foreground"><ArrowLeft size={15}/>Strategic Partner Registry</Link><section className="rounded-2xl border border-primary/25 bg-primary/5 p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-primary"><Target size={15}/>Target Partner</p><h1 className="mt-3 text-3xl font-bold">{partner.partnerName}</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">This company is currently a strategic target and is not yet an active EXECLEAD.AI partner.</p></div><button onClick={onEdit} className="min-h-11 rounded-lg border border-border bg-card px-4"><Pencil size={14} className="mr-2 inline"/>Edit Target</button></div></section><section className="grid gap-5 rounded-xl border border-border bg-card p-5 md:grid-cols-3"><Fact label="Strategic Rationale" value={partner.description}/><Fact label="Target Category" value={categoryLabel(partner.partnerCategory)}/><Fact label="Strategic Role" value={partner.valueProposition}/><Fact label="Priority" value={priorityLabel(partner)}/><Fact label="Potential Value" value={partner.partnerValueProposition}/><Fact label="Target Geography" value={partner.regions?.join(', ')}/><Fact label="Target Industry" value={partner.industries?.join(', ')}/><Fact label="Next Recommended Action" value={partner.nextAction || 'Define outreach plan'}/><Fact label="Relationship Status" value={`${partner.partnerStatus} · ${partner.partnershipStage}`}/></section><section className="rounded-xl border border-border bg-muted/30 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Commercial Integrity</p><p className="mt-1 text-sm text-muted-foreground">TARGET record. No partnership revenue, pipeline, agreement, sponsor, integration, introduction, or announcement is implied.</p></section></div>;
}