import React from "react";
import { ArrowRight, Clock } from "lucide-react";

const selectClass = "mt-1.5 w-full rounded-xl border border-border bg-background px-3 py-2.5 text-sm text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring";
const Range = ({ id, label, value, onChange }) => <label htmlFor={id} className="block text-sm font-medium text-card-foreground">{label}<span className="float-right text-xs text-muted-foreground">{value}/5</span><input id={id} type="range" min="1" max="5" value={value} onChange={(e) => onChange(e.target.value)} className="mt-3 w-full accent-accent-orange" /></label>;

export default function QuickReadinessBaseline({ baseline, onChange, onComplete, onLater, saving }) {
  const set = (key, value) => onChange({ ...baseline, [key]: value });
  const ready = baseline.currentRoleLevel && baseline.teamSize && baseline.executiveAspiration;
  return (<div><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-accent-orange">Quick Readiness Baseline™</p><h2 className="mt-1 text-xl font-bold text-card-foreground">Calibrate your starting point</h2><p className="mt-2 text-sm text-muted-foreground">Six focused inputs initialize your HUD and personalize your first 90 days. This is not the full assessment.</p></div><span className="flex shrink-0 items-center gap-1 text-xs text-muted-foreground"><Clock size={13} /> 3–5 min</span></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium text-card-foreground">Current role level<select value={baseline.currentRoleLevel || ""} onChange={(e) => set("currentRoleLevel", e.target.value)} className={selectClass}><option value="">Select level</option><option value="contributor">Individual contributor</option><option value="manager">Manager</option><option value="senior_manager">Senior Manager</option><option value="director">Director</option><option value="vp">VP</option><option value="c_level">C-Level</option></select></label><label className="text-sm font-medium text-card-foreground">Team size<select value={baseline.teamSize || ""} onChange={(e) => set("teamSize", e.target.value)} className={selectClass}><option value="">Select team size</option><option value="none">No direct reports</option><option value="small">1–5</option><option value="medium">6–20</option><option value="large">21–50</option><option value="enterprise">51+</option></select></label><Range id="strategic-exposure" label="Strategic decision exposure" value={baseline.strategicExposure || 1} onChange={(v) => set("strategicExposure", v)} /><Range id="communication-confidence" label="Communication confidence" value={baseline.communicationConfidence || 1} onChange={(v) => set("communicationConfidence", v)} /><Range id="change-leadership" label="Change leadership experience" value={baseline.changeLeadership || 1} onChange={(v) => set("changeLeadership", v)} /><label className="text-sm font-medium text-card-foreground">Executive aspiration<select value={baseline.executiveAspiration || ""} onChange={(e) => set("executiveAspiration", e.target.value)} className={selectClass}><option value="">Select aspiration</option><option>Manager</option><option>Director</option><option>VP</option><option>C-Level</option></select></label></div><div className="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:justify-between"><button onClick={onLater} className="rounded-xl px-4 py-2.5 text-sm text-muted-foreground hover:bg-secondary">Finish Later</button><button onClick={onComplete} disabled={!ready || saving} className="inline-flex items-center justify-center gap-2 rounded-xl bg-accent-orange px-5 py-2.5 text-sm font-semibold text-accent-orange-foreground disabled:cursor-not-allowed disabled:opacity-40">{saving ? "Calibrating…" : "Complete Baseline"}<ArrowRight size={15} /></button></div></div>);
}