import { base44 } from '@/api/base44Client';
const entities = base44.entities;
const uid = (prefix) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
async function context() { const user = await base44.auth.me(); const orgs = await entities.Organization.list('-created_date', 1); return { user, organizationId: user.organization_id || orgs[0]?.id || 'platform' }; }
async function audit(partnerId, entityName, recordId, action, reason = '') { const { user, organizationId } = await context(); return entities.StrategicPartnerAuditLog.create({ organizationId, auditId: uid('audit'), timestamp: new Date().toISOString(), userId: user.id, userName: user.full_name, partnerId, entityName, recordId, action, reason }); }
export async function loadRegistry() { const [partners, objectives, initiatives, interactions, opportunities, auditLog] = await Promise.all([entities.StrategicPartner.list('-updated_date', 200), entities.PartnerObjective.list('-updated_date', 200), entities.PartnerInitiative.list('-updated_date', 200), entities.PartnerInteraction.list('-date', 200), entities.PartnerOpportunity.list('-updated_date', 200), entities.StrategicPartnerAuditLog.list('-timestamp', 200)]); return { partners, objectives, initiatives, interactions, opportunities, audit: auditLog }; }
const normalizeTarget = (target, organizationId) => ({ organizationId, partnerId: uid('partner'), partnerName: target.partnerName, partnerType: target.partnerType || (target.partnerCategory === 'talent_hr' ? 'Talent / HR' : target.partnerCategory === 'enterprise_distribution' ? 'Enterprise Distribution' : target.partnerCategory === 'strategic_ecosystem' ? 'Strategic Alliance' : 'Technology'), partnerCategory: target.partnerCategory, valueProposition: target.strategicRole, strategicImportance: ({ P0: 'critical', P1: 'high', P2: 'medium' })[target.priority], regions: [target.targetRegion], industries: [target.targetIndustry], description: target.strategicRationale, partnerStatus: 'Prospect', partnershipStage: ['Target', 'Research'].includes(target.partnershipStage) ? target.partnershipStage : 'Target', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });
export async function bulkCreateTargets(targets) { const { user, organizationId } = await context(); const existing = await entities.StrategicPartner.list('-updated_date', 200); const names = new Set(existing.map((partner) => partner.partnerName.trim().toLowerCase())); const records = targets.filter((target) => !names.has(target.partnerName.trim().toLowerCase())).map((target) => normalizeTarget(target, organizationId)); if (!records.length) return { created: 0, skipped: targets.length }; const created = await entities.StrategicPartner.bulkCreate(records); await entities.StrategicPartnerAuditLog.bulkCreate(created.map((record) => ({ organizationId, auditId: uid('audit'), timestamp: new Date().toISOString(), userId: user.id, userName: user.full_name, partnerId: record.partnerId, entityName: 'StrategicPartner', recordId: record.id, action: 'Created', reason: 'Strategic target deployed; no partnership implied' }))); return { created: created.length, skipped: targets.length - created.length }; }
export async function createPartner(values) { const { organizationId } = await context(); const record = await entities.StrategicPartner.create({ ...values, organizationId, partnerId: uid('partner'), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); await audit(record.partnerId, 'StrategicPartner', record.id, 'Created'); return record; }
export async function updatePartner(id, values, reason = '') { const record = await entities.StrategicPartner.update(id, { ...values, updatedAt: new Date().toISOString() }); await audit(record.partnerId, 'StrategicPartner', id, 'Updated', reason); return record; }
async function createRelated(entity, prefix, values, idField, action) { const { organizationId } = await context(); const record = await entities[entity].create({ ...values, organizationId, [idField]: uid(prefix), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); await audit(values.partnerId, entity, record.id, action); return record; }
export const createObjective = (v) => createRelated('PartnerObjective', 'objective', v, 'objectiveId', 'Created');
export const createInitiative = (v) => createRelated('PartnerInitiative', 'initiative', v, 'initiativeId', 'Created');
export const createInteraction = (v) => createRelated('PartnerInteraction', 'interaction', v, 'interactionId', 'Created');
export const createOpportunity = (v) => createRelated('PartnerOpportunity', 'opportunity', v, 'opportunityId', 'Revenue Updated');
export const PartnerService = { loadRegistry, bulkCreateTargets, createPartner, updatePartner, createObjective, createInitiative, createInteraction, createOpportunity };
export default PartnerService;